class MRIntWeaps_ID24CalamityBlade : ID24CalamityBlade // Heatwave Generator
{
	Default{
		Weapon.SlotNumber 7;
		Weapon.SlotPriority 32766;
	}
	
	Const Lay1 = 10;
	Const LLimb = Lay1-2;
	Const RLimb = Lay1-1;
	Const Flash = LLimb-1;
	Const Flare = Flash-1;
	
	Bool MidAir;
	Double FireState, LastFireFrame, FireFrame;
	Vector2 LimbOffset, OldLimbOffset;
	
	MRIntWeaps_Fist Handler;
	int BobState, IdleDelay;
	
	int SwitchAnim, SwitchState;
	
	Override Void DoEffect()
	{
		if(Owner.Player.ReadyWeapon != Self || Health<1)Return;
		
		Handler = MRIntWeaps_Fist(Owner.FindInventory("MRIntWeaps_Fist"));
	}
	
	Override Void PostBeginPlay()
	{
		if(Wads.CheckNumForName("HETFA0", wads.ns_sprites)<0){Destroy();Return;}
		Super.PostBeginPlay();
		if(Owner && Owner.CountInv("ID24CalamityBlade")){
			if(!MRIntW_LoRWeaps)Owner.A_TakeInventory("ID24CalamityBlade");
			Destroy();
			Return;
		}
		SwitchAnim = CRandom(0, 1);
	}
	
	States{
	RLimb:
		H2TO A 1;
		Goto LLimb+1;
	LLimb:
		H1TO # 1;
		#### # 1 {
			int Lay = OverlayId();
			Bool Left = Lay == LLimb;
			Player.GetPSprite(Lay).bAddWeapon = Player.GetPSprite(Lay1).bAddWeapon;
			Player.GetPSprite(Lay).Y = Player.GetPSprite(Lay1).Y + invoker.LimbOffset.Y;
			Player.GetPSprite(Lay).OldY = Player.GetPSprite(Lay1).OldY + invoker.OldLimbOffset.Y;
			Player.GetPSprite(Lay).X = Player.GetPSprite(Lay1).X + ((Left)?-invoker.LimbOffset.X:invoker.LimbOffset.X);
			Player.GetPSprite(Lay).OldX = Player.GetPSprite(Lay1).OldX + ((Left)?-invoker.OldLimbOffset.X:invoker.OldLimbOffset.X);
			Player.GetPSprite(Lay).bInterpolate = Player.GetPSprite(Lay1).bInterpolate;
			
			Double Mid = invoker.FireState%1/.5;
			if(Mid>=1)Mid = Mid-2;

			//Console.Printf(Mid.." "..invoker.FireState.." "..Round(invoker.FireState));
			
			Switch(Round(invoker.FireState)){
				Case 0:
					if(Player.GetPSprite(Lay).Frame != Round(invoker.FireState))Player.GetPSprite(Lay).bInterpolate = false;
					Player.GetPSprite(Lay).Scale = (1, 1) + (.15,.03)*Mid;
	 				Player.GetPSprite(Lay).Rotation = -7.5*Mid;
					if(Left)Player.GetPSprite(Lay).Rotation *= -1;
					Player.GetPSprite(Lay).Frame = Round(invoker.FireState);
					Break;
				Case 1:
					Player.GetPSprite(Lay).Scale = (1,1) + (.075,.03)*Mid;
					Player.GetPSprite(Lay).Rotation = -3*Mid;
					if(Left)Player.GetPSprite(Lay).Rotation *= -1;
					Player.GetPSprite(Lay).Frame = Round(invoker.FireState);
					Break;
				Case 2:
					Player.GetPSprite(Lay).Scale = (1,1) + (.025,.01)*Mid;
					Player.GetPSprite(Lay).Rotation = -2.5*Mid;
					if(Left)Player.GetPSprite(Lay).Rotation *= -1;
					Player.GetPSprite(Lay).Frame = Round(invoker.FireState);
					Break;
				Case 3:
					Player.GetPSprite(Lay).Scale = (1,1) + (.1,.07)*Mid;
					Player.GetPSprite(Lay).Rotation = -5*Mid + CFRandom(-.25, .25);
					if(Left)Player.GetPSprite(Lay).Rotation *= -1;
					Player.GetPSprite(Lay).Frame = Round(invoker.FireState);
					Break;
			}
			
			if(Player.FindPSprite(Flash))
				Player.GetPSprite(OverlayId()).Rotation += -CFRandom(.05, .4)*(invoker.LastFireFrame+1)*(Left?-1:1);
			
			invoker.OldLimbOffset = invoker.LimbOffset;
		}
		Wait;
	
	
	GunRaiseVanilla://Vanilla select animation
		H1TG A 1 {
			A_OverlayPivot(Lay1, .5, 1);
			A_Overlay(LLimb, "LLimb");
			A_Overlay(RLimb, "RLimb");
			A_OverlayFlags(Lay1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay1).FirstTic);
		}
		#### # 1{
			if(Player.GetPSprite(PSP_WEAPON).Y<=32)Player.SetPsprite(Lay1, invoker.FindState("GunWait"));
		}
		Wait;
	GunRaise:
		TNT1 AAA 1 {
			A_OverlayFlags(Lay1, PSPF_ADDWEAPON , false);
			A_OverlayPivot(Lay1, .5, 0);
			invoker.SwitchState = 11;
			
			A_OverlayOffset(Lay1, 0, 110);
			A_Overlay(LLimb, "LLimb", true);
			A_Overlay(RLimb, "RLimb", true);
			
			A_OverlayPivot(LLimb, 1, .5);
			A_OverlayPivot(RLimb, 0, .5);
			
			if(invoker.SwitchAnim){
				invoker.LimbOffset = (-50, 50);
				invoker.FireState = 0;
			}
			else {
				invoker.LimbOffset = (0,0);
				invoker.FireState = 3;
			}
		}
		H1TG A 1;
		#### ####### 1 {
			A_OverlayMoveTo(Lay1, 0, 20, .7);
			A_OverlayFlags(Lay1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay1).FirstTic);
			
			if(invoker.SwitchState<8){
				invoker.LimbOffset.X = 5+(invoker.LimbOffset.X-5)*.6;
			}
			
			if(invoker.SwitchState<9){
				if(invoker.FireState>1){
					invoker.FireState--;
					invoker.FireState = Max(1, invoker.FireState);
				}
				else invoker.FireState *= .5;
			}
			
			invoker.SwitchState--;
		}
		#### # 1 {
			A_OverlayMoveTo(Lay1, 0, 32, .8);
			invoker.LimbOffset *= .9;
			if(invoker.FireState>1){
				invoker.FireState--;
				invoker.FireState = Max(1, invoker.FireState);
			}
			else invoker.FireState *= .5;
			
			invoker.SwitchState--;
		}
		#### ### 1 {
			A_OverlayMoveTo(Lay1, 0, 33, .6);
			invoker.LimbOffset *= .7;
			if(invoker.FireState>1){
				invoker.FireState--;
				invoker.FireState = Max(1, invoker.FireState);
			}
			else invoker.FireState *= .5;
			
			invoker.SwitchState--;
		}
		#### # 1{
			A_OverlayFlags(Lay1, PSPF_ADDWEAPON, true);
			A_OverlayOffset(Lay1, 0, 0, WOF_INTERPOLATE);
			A_OverlayScale(Lay1, 1, 1, WOF_INTERPOLATE);
			A_OverlayRotate(Lay1, 0, WOF_INTERPOLATE);
			Player.GetPSprite(Lay1).OldY -= 32;
			invoker.BobState = 0;
			invoker.SwitchState = 0;
			invoker.LimbOffset *= .7;
			invoker.FireState *= .7;
		}
	GunWait:
		H1TG A 1 {
			if(Player.Cmd.Buttons&BT_ALTATTACK && !(Player.FindPSprite(Flash) && InStateSequence(Player.FindPSprite(Flash).CurState, invoker.FindState("GunFlash"))))invoker.FireState += 1;
			else if(invoker.FireState>1)invoker.FireState -= 1;
			else invoker.FireState *= .5;
			
			invoker.FireState = Clamp(invoker.FireState, 0, 3);
			
			invoker.LimbOffset *= .7;
			
			
			if(invoker.MidAir && Pos.Z <= FloorZ){
				invoker.FireState += abs(invoker.Handler.CurBounce)*.01;
			}
			invoker.MidAir = invoker.Handler.Landed;
			
			
			A_OverlayFlags(Lay1, PSPF_INTERPOLATE, (invoker.Handler && invoker.Handler.Interpolate && !Player.GetPSprite(Lay1).FirstTic));
		}
		Wait;
	GunLowerVanilla:
		H1TG A 1;
		Wait;
	GunLower:
		H1TG A 0 {
			if(invoker.SwitchState<1 && MRIntW_SwitchAnims>1)invoker.SwitchAnim = CRandom(0, 1);
			else {
				Player.GetPSprite(Lay1).Y -= Player.GetPSprite(PSP_WEAPON).Y;
				Player.GetPSprite(Lay1).OldY -= Player.GetPSprite(PSP_WEAPON).OldY;
			}
			A_OverlayFlags(Lay1, PSPF_ADDWEAPON, true);
		}
		#### # 1 {
			Player.GetPSprite(Lay1).Y *= .8;
			if(invoker.SwitchAnim){
				invoker.LimbOffset.X -= CFRandom(.75, 2);
			}
			A_OverlayFlags(Lay1, PSPF_INTERPOLATE, (invoker.Handler && invoker.Handler.Interpolate && !Player.GetPSprite(Lay1).FirstTic));
		}
		#### ## 1 {
			Player.GetPSprite(Lay1).Y *= .8;
			if(invoker.SwitchAnim){
				invoker.LimbOffset.X = -11+(invoker.LimbOffset.X+10)*.6;
			}
			else invoker.FireState += .5;
			A_OverlayFlags(Lay1, PSPF_INTERPOLATE, (invoker.Handler && invoker.Handler.Interpolate && !Player.GetPSprite(Lay1).FirstTic));
		}
		#### # 1 {
			Player.GetPSprite(Lay1).Y *= .8;
			if(invoker.SwitchAnim){
				invoker.LimbOffset.X = -10+(invoker.LimbOffset.X+10)*.7;
				invoker.LimbOffset.Y += CFRandom(4, 6);
			}
			else invoker.FireState += Min(3-invoker.FireState, 1);
		}
		Wait;
		
	GunFire:
		H1TG AAAAAA 1 {
			invoker.FireState += 2;
			invoker.FireState = Min(3, invoker.FireState);
			A_OverlayMoveTo(Lay1, 0, 30, .7);
		}
		H1TG ### 1 {
			if(invoker.FireState>1)invoker.FireState -= .5;
			else invoker.FireState *= .5;
			A_OverlayMoveTo(Lay1, 0, 30, .7);
		}
		H1TG # 1 {
			if(invoker.FireState>1)invoker.FireState -= .5;
			else invoker.FireState *= .5;
			A_OverlayOffset(Flash, 0, -3, WOF_ADD);
		}
		H1TG ########## 1 {
			if(invoker.FireState>1)invoker.FireState -= .5;
			else invoker.FireState *= .5;
			A_OverlayMoveTo(Lay1, 0, 0, .8);
		}
		Goto GunWait;
	
	GunFlash:
		H1TC A 1 BRIGHT{
			A_OverlayFlags(Flash, PSPF_ALPHA|PSPF_RENDERSTYLE, true);
			A_OverlayPivot(Flash, .5, 1);
			invoker.LastFireFrame = -1;
			A_OverlayScale(Flash, 1, 0);
			invoker.FireFrame = 0;
			A_Overlay(Flare, "GunFlashFlare");
		}
		#### # 1 BRIGHT{
			Player.GetPSprite(Flash).Y = Player.GetPSprite(Lay1).Y;
			A_OverlayFlags(Flash, PSPF_INTERPOLATE, !Player.GetPSprite(Flash).FirstTic);
			A_OverlayAlpha(Flash, CFRandom(.9, 1));
			A_OverlayRenderStyle(Flash, STYLE_ADD);
			
			if(!Player.FindPSprite(PSP_FLASH))Return;
			
			int Stayt = -1;
			if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold0Flash")))Stayt = 0;
			else if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold1Flash")))Stayt = 1;
			else if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold2Flash")))Stayt = 2;
			else if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold3Flash")))Stayt = 3;
			else if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold4Flash")))Stayt = 4;
			
			Player.GetPSprite(Flash).Frame = Stayt*4+invoker.FireFrame;
			
			if(!MRIntW_NoMuzzleFlash || GetAge()%6==0)invoker.FireFrame++;
			if(invoker.FireFrame>3)invoker.FireFrame = 0;
			
			if(invoker.LastFireFrame != Stayt){
				Player.GetPSprite(Flash).Scale = (1,.75);
				Player.GetPSprite(Flash).bInterpolate = false;
			}
			else {
				if(Stayt<4)Player.GetPSprite(Flash).Scale.X += .02;
				Player.GetPSprite(Flash).Scale.Y = (MRIntW_NoMuzzleFlash?1:CFRandom(.9, 1.1));
			}
			
			invoker.LastFireFrame = Stayt;
			
			invoker.FireState *= .5;
			
			A_OverlayRotate(LLimb, CFRandom(-.1, .1)*Stayt, WOF_INTERPOLATE);
			A_OverlayRotate(RLimb, CFRandom(-.1, .1)*Stayt, WOF_INTERPOLATE);
			
			if(Stayt<0)Player.SetPsprite(Flash, Null);
		}
		Wait;
	GunFlash2:
		H1TF A 1 BRIGHT{
			A_OverlayPivot(Flash, .5, .8);
			A_OverlayScale(Flash, 1, 1, WOF_INTERPOLATE);
			A_OverlayFlags(Flash, PSPF_INTERPOLATE, !Player.GetPSprite(Flash).FirstTic);
			if(MRIntW_NoMuzzleFlash)A_OverlayRenderStyle(Flash, STYLE_None);
		}
		#### A 1 BRIGHT A_OverlayScale(Flash, 2, 1.1, WOF_INTERPOLATE);
		#### BB 1 BRIGHT;
		#### BBBBBBBBBBBB 1 BRIGHT{
			Player.GetPSprite(Flash).Scale = (.1,.1)+(Player.GetPSprite(Flash).Scale-(.1,.1))*.8;
		}
		Stop;
	GunFlashFlare:
		NSHS B 1 BRIGHT{
			if(!Player.FindPSprite(Flash)){A_ClearOverlays(OverlayId(), OverlayId());Return;}
			A_OverlayTranslation(OverlayId(), "MRIntWParOrange");
			A_OverlayFlags(OverlayId(), PSPF_RENDERSTYLE|PSPF_FORCESTYLE|PSPF_FORCEALPHA, true);
			A_OverlayPivot(OverlayId(), .5, .7);
			
			if(GetRenderStyle()!=STYLE_Normal && GetCVar("r_drawfuzz")!=0){//Not drawing overlays if got partial invisibility and fuzz mode is not set to tranlsucent
				A_OverlayRenderStyle(OverlayID(), STYLE_None);
			}
			else {
				A_OverlayRenderStyle(OverlayId(), STYLE_ADD);
				A_OverlayAlpha(OverlayId(), .3+CFRandom(-.1, .1));
			}
			
			if(!MRIntW_FlashFlare){A_OverlayRenderStyle(OverlayId(), STYLE_NONE);Return;}
			
			int Stayt;
			if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold0Flash")))Stayt = 1;
			else if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold1Flash")))Stayt = 2;
			else if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold2Flash")))Stayt = 3;
			else if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold3Flash")))Stayt = 4;
			else if(InStateSequence(Player.GetPSprite(PSP_FLASH).CurState, invoker.FindState("Hold4Flash")))Stayt = 5;
			else if(InStateSequence(Player.GetPSprite(Flash).CurState, invoker.FindState("GunFlash2")))Stayt = 6;
			
			Vector2 Scale = (.5, 0);
			Double YOffset = 85;
			
			if(Stayt<6){
				if(Stayt>1)YOffset = 76;
				if(Stayt>4)YOffset = 80;
				
				if(Stayt>2)Scale.X = Stayt-1;
				if(Stayt>4)Scale.Y = .2;
				
				Scale = ((Scale.X)*.5+Player.GetPSprite(Flash).Scale.X*1.25, Player.GetPSprite(Flash).Scale.Y*.75+Scale.Y);
			}
			else {
				YOffset = 80+Player.GetPSprite(Flash).Y;
				Scale = (Player.GetPSprite(Flash).Scale.X*1.5, Player.GetPSprite(Flash).Scale.Y)*1.3;
				A_OverlayPivot(OverlayId(), .5, 1);
			}
			
			A_OverlayScale(Flare, Scale.X, Scale.Y, WOF_INTERPOLATE);
			
			Player.GetPSprite(OverlayId()).X = 128 + Player.GetPSprite(Lay1).X;
			Player.GetPSprite(OverlayId()).Y = YOffset + Player.GetPSprite(Lay1).Y;
			Player.GetPSprite(OverlayId()).OldX = 128 + Player.GetPSprite(Lay1).OldX;
			Player.GetPSprite(OverlayId()).OldY = YOffset + Player.GetPSprite(Lay1).OldY;
		}
		Wait;
	
	
	//Default states
	
	Select:
		TNT1 A 0 {
			if(invoker.Dropped)invoker.Dropped.Destroy();
			if(MRIntW_SwitchAnims)A_Overlay(Lay1, "GunRaise");
			else A_Overlay(Lay1, "GunRaiseVanilla");
			Player.GetPSprite(PSP_WEAPON).Y = WEAPONBOTTOM;
			
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETGA0");
		}
	Raise:
		#### A 1 A_Raise();
		Loop;
	Ready:
		TNT1 A 0 {
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETGA0");
		}
		#### A 1 A_WeaponReady();
		Wait;
	Deselect:
		TNT1 A 0 {
			if(Health<1){A_Overlay(Lay1, "GunDie");Return;}
			
			if(MRIntW_SwitchAnims)Player.SetPsprite(Lay1, invoker.FindState("GunLower"));
			else A_Overlay(Lay1, "GunLowerVanilla");
			
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETGA0");
		}
	Lower:
		#### A 1 A_Lower();
		Loop;
	Fire:
	Hold0:
		TNT1 A 0 {
			MBF21_ConsumeAmmo(0);
			A_Overlay(Flash, "GunFlash");
			
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETGA0");
		}
		#### A 0 A_GunFlashTo("Hold0Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		#### A 0 A_CheckAmmo("Hold0FireProjectiles", 0);
		#### A 0 A_RefireTo("Hold1", 0);
		Goto Hold0FireProjectiles;
	Hold1:
		#### A 0 MBF21_ConsumeAmmo(0);
		#### A 0 A_GunFlashTo("Hold1Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		#### A 0 A_CheckAmmo("Hold1FireProjectiles", 0);
		#### A 0 A_RefireTo("Hold2", 0);
		Goto Hold1FireProjectiles;
	Hold2:
		#### A 0 MBF21_ConsumeAmmo(0);
		#### A 0 A_GunFlashTo("Hold2Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		#### A 0 A_CheckAmmo("Hold2FireProjectiles", 0);
		#### A 0 A_RefireTo("Hold3", 0);
		Goto Hold2FireProjectiles;
	Hold3:
		#### A 0 MBF21_ConsumeAmmo(0);
		#### A 0 A_GunFlashTo("Hold3Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		#### A 0 A_CheckAmmo("Hold3FireProjectiles", 0);
		#### A 0 A_RefireTo("Hold4", 0);
		Goto Hold3FireProjectiles;
	Hold4:
		#### A 0 MBF21_ConsumeAmmo(0);
		#### A 0 A_GunFlashTo("Hold4Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		Goto Hold4FireProjectiles;
	Hold4FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -35, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -30, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -25, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -20, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -15, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -10, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 0, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 10, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 15, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 20, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 25, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 30, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 35, 0, 0, 0);
		Goto FireAnim;
	Hold3FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -27.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -22.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -17.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -12.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -7.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -2.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 2.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 7.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 12.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 17.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 22.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 27.5, 0, 0, 0);
		Goto FireAnim;
	Hold2FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -20, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -15, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -10, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 0, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 10, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 15, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 20, 0, 0, 0);
		Goto FireAnim;
	Hold1FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -12.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -7.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -2.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 2.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 7.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 12.5, 0, 0, 0);
		Goto FireAnim;
	Hold0FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 0, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 5, 0, 0, 0);
		Goto FireAnim;
	FireAnim:
		TNT1 A 0 BRIGHT {
			A_StartSound("weapons/calamityblade/shoot", CHAN_WEAPON);
			
			Player.SetPsprite(Lay1, invoker.FindState("GunFire"));
			Player.SetPsprite(Flash, invoker.FindState("GunFlash2"));
			
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETFA0");
		}
		#### A 3 BRIGHT A_GunFlash();
		#### B 5 BRIGHT;
		#### D 4 {
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETGA0");
		}
		#### C 4;
		#### B 4;
		#### A 0 A_ReFire();
		Goto Ready;
	Hold0Flash:
		TNT1 A 6 BRIGHT{
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETCA0");
		}
		#### BCD 5 BRIGHT;
		Goto LightDone;
	Hold1Flash:
		TNT1 A/*E*/ 6 BRIGHT{
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETCA0");
		}
		#### FGH 5 BRIGHT;
		Goto LightDone;
	Hold2Flash:
		TNT1 A/*I*/ 6 BRIGHT{
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETCA0");
		}
		#### JKL 5 BRIGHT;
		Goto LightDone;
	Hold3Flash:
		TNT1 A/*M*/ 6 BRIGHT{
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETCA0");
		}
		#### NOP 5 BRIGHT;
		Goto LightDone;
	Hold4Flash:
		TNT1 A/*Q*/ 6 BRIGHT{
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETCA0");
		}
		#### RST 5 BRIGHT;
		Goto LightDone;
	Flash:
		TNT1 A 3 A_Light1();
		TNT1 A 5 A_Light2();
		Goto LightDone;
	}
	
	Action Void A_IdleAnimation(int Lay = 2)//Idle hand bobbing
	{
		int CVa = GetCVar("MRIntW_IdleAnims");
		
		if(CVa%2==1){
			Bool Bers = (GetCVar("MRIntW_BersShake")>1 && FindInventory("PowerStrength"))||(Health<20 && GetCVar("MRIntW_LowHealthShake"));
			Float Mult = (Bers?2:1);
			if(invoker.BobState>=0){
				A_OverlayOffset(Lay, CFRandom(-.005, .015)*Mult, CFRandom(.01, .02)*Mult, WOF_ADD);
				if(invoker.BobState>90||Player.GetPSprite(Lay).Y>1.35){invoker.BobState = -invoker.BobState;}
				else invoker.BobState+=Mult;
			}
			else {
				A_OverlayOffset(Lay, -CFRandom(-.005, .015)*Mult, -CFRandom(.01, .02)*Mult, WOF_ADD);
				if(Player.GetPSprite(Lay).Y<0){A_OverlayOffset(Lay, 0, 0, WOF_INTERPOLATE);invoker.BobState = 0;}
				else if(!(invoker.BobState>=-1&&Player.GetPSprite(Lay).Y>0))invoker.BobState+=Mult;
			}
			if(Bers && GetAge()%2==0){//Shaking hand if got berserk
				A_OverlayOffset(Lay, CFRandom(-.25, .25), 0, WOF_INTERPOLATE|WOF_KEEPY);
				Player.GetPSprite(Lay).Y += CFRandom(-.25, .25);
				if(Player.GetPSprite(Lay).Y<0){Player.GetPSprite(Lay).Y = 0;invoker.BobState = 0;}
				if(Player.GetPSprite(Lay).Y>1.35){Player.GetPSprite(Lay).Y = 1.35;invoker.BobState = -90;}
			}
		}
		
		if(CVa>1){
			if(MRIntWeaps_Fist(FindInventory("MRIntWeaps_Fist"))){
				if(MRIntWeaps_Fist(FindInventory("MRIntWeaps_Fist")).CurSway.X==0)invoker.IdleDelay++;
				else invoker.IdleDelay = Min(0, invoker.IdleDelay);
			}
		}
	}
	
	Action Void A_BersShake()
	{
		if((GetCVar("MRIntW_BersShake")>1 && FindInventory("PowerStrength"))||(Health<20 && GetCVar("MRIntW_LowHealthShake")))A_OverlayOffset(Lay1, CFRandom(-.25, .25), CFRandom(-.25, .25), WOF_ADD);
	}
	
	Action Void A_OverlayMoveTo(int Lay = -1, Double XTo = 0, Double YTo = 0, Double SpeedX = .8, Double SpeedY = -1)
	{
		if(Lay == -1)Lay = OverlayId();
		if(SpeedY == -1)SpeedY = SpeedX;
		Player.GetPSprite(Lay).X = XTo + (Player.GetPSprite(Lay).X - XTo)*SpeedX;
		Player.GetPSprite(Lay).Y = YTo + (Player.GetPSprite(Lay).Y - YTo)*SpeedY;
	}
	
	Action Void A_DoVanillaDisplay()
	{
		if(!MRIntW_DisplayVanilla)Return;
		
		A_OverlayFlags(OverlayId(), PSPF_RENDERSTYLE|PSPF_ALPHA, true);
		
		if(GetRenderStyle()==STYLE_NORMAL){
			A_OverlayRenderStyle(OverlayId(), STYLE_TRANSLUCENT);
			Player.GetPSprite(OverlayId()).Alpha = Min(Player.GetPSprite(OverlayId()).Alpha, .5);
		}
	}
}