class MRIntWeaps_ID24CalamityBlade : ID24CalamityBlade // Heatwave Generator
{
	Default{
		Weapon.SlotNumber 7;
		Weapon.SlotPriority 32766;
	}
	
	Const Lay1 = 10;
	Const LLimb = Lay1-2;
	Const RLimb = Lay1-1;
	
	int BobState, IdleDelay;
	
	int SwitchAnim, SwitchState;
	
	Override Void PostBeginPlay()
	{
		if(Wads.CheckNumForName("HETFA0", wads.ns_sprites)<0){Destroy();Return;}
		Super.PostBeginPlay();
		if(Owner && Owner.CountInv("ID24CalamityBlade"))Destroy();
	}
	
	States{
	
	GunRaise:
		TNT1 AAA 1 {
			A_OverlayFlags(Lay1, PSPF_ADDWEAPON , false);
			A_OverlayPivot(Lay1, .5, 0);
			//A_OverlayOffset(Lay1, invoker.SwitchAnim?-41:41, 110);
			//A_OverlayScale(Lay1, 1.4, 1.1);
			//A_OverlayRotate(Lay1, invoker.SwitchAnim?2:-2);
			invoker.SwitchState = 11;
			
			A_OverlayOffset(Lay1, 0, 110);
			A_Overlay(LLimb, "LLimb");
			A_Overlay(RLimb, "RLimb");
			
			A_OverlayPivot(LLimb, 1, .5);
			A_OverlayPivot(RLimb, 0, .5);
		}
		H1TG A 1;
		#### ######## 1 {
			A_OverlayMoveTo(Lay1, 0, 20, .7);
			A_OverlayFlags(Lay1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay1).FirstTic);
		}
		#### # 1 {
			A_OverlayMoveTo(Lay1, 0, 32, .5);
			A_OverlayScale(LLimb, 1.2, 1.2, WOF_INTERPOLATE);
			A_OverlayScale(RLimb, 1.2, 1.2, WOF_INTERPOLATE);
			A_OverlayRotate(LLimb, 12, WOF_INTERPOLATE);
			A_OverlayRotate(RLimb, -12, WOF_INTERPOLATE);
		}
		#### ## 1 {
			A_OverlayMoveTo(Lay1, 0, 32, .5);
			Player.GetPSprite(LLimb).Scale.X = 1+(Player.GetPSprite(LLimb).Scale.X-1)*.5;
			Player.GetPSprite(RLimb).Scale.X = 1+(Player.GetPSprite(LLimb).Scale.X-1)*.5;
			Player.GetPSprite(LLimb).Rotation *= .5;
			Player.GetPSprite(RLimb).Rotation *= .5;
		}
		#### # 1{
			A_OverlayFlags(Lay1, PSPF_ADDWEAPON, true);
			A_OverlayOffset(Lay1, 0, 0, WOF_INTERPOLATE);
			A_OverlayScale(Lay1, 1, 1, WOF_INTERPOLATE);
			A_OverlayRotate(Lay1, 0, WOF_INTERPOLATE);
			Player.GetPSprite(Lay1).OldY -= 32;
			invoker.BobState = 0;
			invoker.SwitchState = 0;
			A_OverlayScale(LLimb, 1, 1, WOF_INTERPOLATE);
			A_OverlayScale(RLimb, 1, 1, WOF_INTERPOLATE);
			A_OverlayRotate(LLimb, 0, WOF_INTERPOLATE);
			A_OverlayRotate(RLimb, 0, WOF_INTERPOLATE);
		}
	GunWait:
		H1TG A 1;
		Wait;
	GunLower:
		TNT1 A 1;
		Wait;
	
	RLimb:
		H2TO A 1;
		Goto LLimb+1;
	LLimb:
		H1TO # 1;
		#### # 1 {
			Player.GetPSprite(OverlayId()).bAddWeapon = Player.GetPSprite(Lay1).bAddWeapon;
			Player.GetPSprite(OverlayId()).Y = Player.GetPSprite(Lay1).Y;
			Player.GetPSprite(OverlayId()).OldY = Player.GetPSprite(Lay1).OldY;
			Player.GetPSprite(OverlayId()).X = Player.GetPSprite(Lay1).X;
			Player.GetPSprite(OverlayId()).OldX = Player.GetPSprite(Lay1).OldX;
			Player.GetPSprite(OverlayId()).bInterpolate = Player.GetPSprite(Lay1).bInterpolate;
		}
		Wait;
	
	
	//Default states
	
	Select:
		TNT1 A 0 {
			if(invoker.Dropped)invoker.Dropped.Destroy();
			if(MRIntW_SwitchAnims)A_Overlay(Lay1, "GunRaise");
			else A_Overlay(Lay1, "GunRaiseVanilla");
			Player.GetPSprite(PSP_WEAPON).Y = WEAPONBOTTOM;
			
			if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("HETGA0");
		}
	Raise:
		TNT1 A 1 A_Raise();
		Loop;
	Ready:
		TNT1 A 1 A_WeaponReady();
		Loop;
	Deselect:
		TNT1 A 1 A_Lower();
		Loop;
	Fire:
	Hold0:
		TNT1 A 0 MBF21_ConsumeAmmo(0);
		#### A 0 A_GunFlashTo("Hold0Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		#### A 0 A_CheckAmmo("Hold0FireProjectiles", 0);
		#### A 0 A_RefireTo("Hold1", 0);
		Goto Hold0FireProjectiles;
	Hold1:
		#### A 0 MBF21_ConsumeAmmo(0);
		#### A 0 A_GunFlashTo("Hold1Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		#### A 0 A_CheckAmmo("Hold1FireProjectiles", 0);
		#### A 0 A_RefireTo("Hold2", 0);
		Goto Hold1FireProjectiles;
	Hold2:
		#### A 0 MBF21_ConsumeAmmo(0);
		#### A 0 A_GunFlashTo("Hold2Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		#### A 0 A_CheckAmmo("Hold2FireProjectiles", 0);
		#### A 0 A_RefireTo("Hold3", 0);
		Goto Hold2FireProjectiles;
	Hold3:
		#### A 0 MBF21_ConsumeAmmo(0);
		#### A 0 A_GunFlashTo("Hold3Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		#### A 0 A_CheckAmmo("Hold3FireProjectiles", 0);
		#### A 0 A_RefireTo("Hold4", 0);
		Goto Hold3FireProjectiles;
	Hold4:
		#### A 0 MBF21_ConsumeAmmo(0);
		#### A 0 A_GunFlashTo("Hold4Flash", 1);
		#### A 20 A_StartSound("weapons/calamityblade/charge", CHAN_WEAPON);
		Goto Hold4FireProjectiles;
	Hold4FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -35, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -30, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -25, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -20, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -15, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -10, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 0, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 10, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 15, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 20, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 25, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 30, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 35, 0, 0, 0);
		Goto FireAnim;
	Hold3FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -27.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -22.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -17.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -12.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -7.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -2.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 2.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 7.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 12.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 17.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 22.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 27.5, 0, 0, 0);
		Goto FireAnim;
	Hold2FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -20, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -15, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -10, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 0, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 10, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 15, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 20, 0, 0, 0);
		Goto FireAnim;
	Hold1FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -12.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -7.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -2.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 2.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 7.5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 12.5, 0, 0, 0);
		Goto FireAnim;
	Hold0FireProjectiles:
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", -5, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 0, 0, 0, 0);
		HETF A 0 BRIGHT MBF21_WeaponProjectile("ID24IncineratorProjectile", 5, 0, 0, 0);
		Goto FireAnim;
	FireAnim:
		TNT1 A 0 BRIGHT A_StartSound("weapons/calamityblade/shoot", CHAN_WEAPON);
		#### A 3 BRIGHT A_GunFlash();
		#### B 5 BRIGHT;
		#### D 4;
		#### C 4;
		#### B 4;
		#### A 0 A_ReFire();
		Goto Ready;
	Hold0Flash:
		TNT1 A 6 BRIGHT;
		#### BCD 5 BRIGHT;
		Goto LightDone;
	Hold1Flash:
		TNT1 A/*E*/ 6 BRIGHT;
		#### FGH 5 BRIGHT;
		Goto LightDone;
	Hold2Flash:
		TNT1 A/*I*/ 6 BRIGHT;
		#### JKL 5 BRIGHT;
		Goto LightDone;
	Hold3Flash:
		TNT1 A/*M*/ 6 BRIGHT;
		#### NOP 5 BRIGHT;
		Goto LightDone;
	Hold4Flash:
		TNT1 A/*Q*/ 6 BRIGHT;
		#### RST 5 BRIGHT;
		Goto LightDone;
	Flash:
		TNT1 A 3 A_Light1();
		TNT1 A 5 A_Light2();
		Goto LightDone;
	}
	
	Action Void A_IdleAnimation(int Lay = 2)//Idle hand bobbing
	{
		int CVa = GetCVar("MRIntW_IdleAnims");
		
		if(CVa%2==1){
			Bool Bers = (GetCVar("MRIntW_BersShake")>1 && FindInventory("PowerStrength"))||(Health<20 && GetCVar("MRIntW_LowHealthShake"));
			Float Mult = (Bers?2:1);
			if(invoker.BobState>=0){
				A_OverlayOffset(Lay, CFRandom(-.005, .015)*Mult, CFRandom(.01, .02)*Mult, WOF_ADD);
				if(invoker.BobState>90||Player.GetPSprite(Lay).Y>1.35){invoker.BobState = -invoker.BobState;}
				else invoker.BobState+=Mult;
			}
			else {
				A_OverlayOffset(Lay, -CFRandom(-.005, .015)*Mult, -CFRandom(.01, .02)*Mult, WOF_ADD);
				if(Player.GetPSprite(Lay).Y<0){A_OverlayOffset(Lay, 0, 0, WOF_INTERPOLATE);invoker.BobState = 0;}
				else if(!(invoker.BobState>=-1&&Player.GetPSprite(Lay).Y>0))invoker.BobState+=Mult;
			}
			if(Bers && GetAge()%2==0){//Shaking hand if got berserk
				A_OverlayOffset(Lay, CFRandom(-.25, .25), 0, WOF_INTERPOLATE|WOF_KEEPY);
				Player.GetPSprite(Lay).Y += CFRandom(-.25, .25);
				if(Player.GetPSprite(Lay).Y<0){Player.GetPSprite(Lay).Y = 0;invoker.BobState = 0;}
				if(Player.GetPSprite(Lay).Y>1.35){Player.GetPSprite(Lay).Y = 1.35;invoker.BobState = -90;}
			}
		}
		
		if(CVa>1){
			if(MRIntWeaps_Fist(FindInventory("MRIntWeaps_Fist"))){
				if(MRIntWeaps_Fist(FindInventory("MRIntWeaps_Fist")).CurSway.X==0)invoker.IdleDelay++;
				else invoker.IdleDelay = Min(0, invoker.IdleDelay);
			}
		}
	}
	
	Action Void A_BersShake()
	{
		if((GetCVar("MRIntW_BersShake")>1 && FindInventory("PowerStrength"))||(Health<20 && GetCVar("MRIntW_LowHealthShake")))A_OverlayOffset(Lay1, CFRandom(-.25, .25), CFRandom(-.25, .25), WOF_ADD);
	}
	
	Action Void A_OverlayMoveTo(int Lay = -1, Double XTo = 0, Double YTo = 0, Double SpeedX = .8, Double SpeedY = -1)
	{
		if(Lay == -1)Lay = OverlayId();
		if(SpeedY == -1)SpeedY = SpeedX;
		Player.GetPSprite(Lay).X = XTo + (Player.GetPSprite(Lay).X - XTo)*SpeedX;
		Player.GetPSprite(Lay).Y = YTo + (Player.GetPSprite(Lay).Y - YTo)*SpeedY;
	}
	
	Action Void A_DoVanillaDisplay()
	{
		if(!MRIntW_DisplayVanilla)Return;
		
		A_OverlayFlags(OverlayId(), PSPF_RENDERSTYLE|PSPF_ALPHA, true);
		
		if(GetRenderStyle()==STYLE_NORMAL){
			A_OverlayRenderStyle(OverlayId(), STYLE_TRANSLUCENT);
			Player.GetPSprite(OverlayId()).Alpha = Min(Player.GetPSprite(OverlayId()).Alpha, .5);
		}
	}
}