Extend Class MRIntWeaps_Pistol
{
	//Recoil animation parameters
	Vector2 RecOfst, LastPos;
	Double RecScal, LastScal;
	
	States{
		RifleRaise:
			TNT1 A 0 {invoker.SwitchAnim = CRandom(0, 1);}
			TNT1 AAAA 1 {
				A_DoVanillaDisplay();
				if(invoker.Dropped)invoker.Dropped.Destroy();
				A_OverlayFlags(Lay1, PSPF_ADDWEAPON , false);
				A_OverlayPivot(Lay1, .5, 1);
				A_OverlayOffset(Lay1, invoker.SwitchAnim?-50:50, 80);
				A_OverlayScale(Lay1, .6, .6);
				A_OverlayRotate(Lay1, -10);
				invoker.SwitchState = 12;
			}
			R1FG A 1{
				A_GlovesColor(1);
				A_OverlayFlags(Lay1, PSPF_INTERPOLATE, false);
			}
			#### AAAAAA 1 {
				A_OverlayFlags(Lay1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay1).FirstTic);
				A_OverlayOffset(Lay1, invoker.SwitchAnim?7:-7, -9, WOF_ADD);
				A_OverlayScale(Lay1, .06, .06, WOF_ADD);
				A_OverlayRotate(Lay1, 1, WOF_ADD);
				invoker.SwitchState--;
				
				if(invoker.ReloadR && invoker.SwitchState>9)A_StartSound("MRIntW/PistolReload", CHAN_AUTO, pitch:i_timescale*CFRandom(.95, 1.05));
			}
			#### AA 1{
				A_OverlayOffset(Lay1, invoker.SwitchAnim?5:-5, 5, WOF_ADD);
				A_OverlayRotate(Lay1, 2, WOF_ADD);
				A_OverlayScale(Lay1, .02, .02, WOF_ADD);
				invoker.SwitchState--;
			}
			#### A 1{
				A_OverlayScale(Lay1, 0, -.025, WOF_ADD);
				A_OverlayOffset(Lay1, invoker.SwitchAnim?1:-1, 3, WOF_ADD);
				A_OverlayRotate(Lay1, .5, WOF_ADD);
				invoker.SwitchState--;
			}
			#### AA 1{
				A_OverlayOffset(Lay1, invoker.SwitchAnim?-2:2, -2, WOF_ADD);
				A_OverlayRotate(Lay1, -.25, WOF_ADD);
				invoker.SwitchState--;
			}
			#### A 0 {if(invoker.ReloadR)A_StartSound("MRIntW/PistolReload", CHAN_AUTO, pitch:i_timescale*CFRandom(1.16, 1.2));invoker.ReloadR = false;}
			#### A 1 {
				A_OverlayOffset(Lay1, 0, 32, WOF_INTERPOLATE);
				A_OverlayScale(Lay1, 0, .025, WOF_ADD);
				
				invoker.SwitchState = 0;
			}
			#### A 1 {
				A_OverlayFlags(Lay1, PSPF_ADDWEAPON , true);
				A_OverlayOffset(Lay1, 0, 0);
				A_OverlayScale(Lay1, 1, 1, WOF_INTERPOLATE);
				A_OverlayRotate(Lay1, 0, WOF_INTERPOLATE);
				
				A_GlovesColor(1);
			}
		RifleWait:
			R1FG A 1 {
				invoker.Catch = false;
				A_OverlayPivot(Lay1, .5, 0);
				A_GlovesColor(1);
				A_IdleAnimation(Lay1);
			}
			#### # 0 A_JumpIf(invoker.IsRifle!=GetCVar("MRIntW_Rifle"), "RifleLower");
			#### # 0 {if(MRIntW_BobRangeZ==0)A_OverlayFlags(Lay1, PSPF_INTERPOLATE, false);}
			#### # 0 A_JumpIf(invoker.IdleDelay>35 && abs(invoker.BobState)<2, "GunIdle1");
			Loop;
		RifleLower:
			R1FG A 1 {
				A_DoVanillaDisplay();
				A_OverlayFlags(Lay1, PSPF_ADDWEAPON, false);
				A_OverlayOffset(Lay1, Player.GetPSprite(PSP_WEAPON).OldX, invoker.SwitchState<1?Player.GetPSprite(PSP_WEAPON).OldY:32);
				A_OverlayRotate(Lay1, 0);
				A_OverlayScale(Lay1, 1, 1);
				A_OverlayPivot(Lay1, .5, 1);
				if(invoker.SwitchState<1)invoker.SwitchAnim = CRandom(0, 1);
				else {invoker.SwitchState--;A_SetTics(0);}
				
				A_GlovesColor(1);
			}
			#### ## 1 {
				A_OverlayOffset(Lay1, invoker.SwitchAnim?5:-5, -5, WOF_ADD);
				A_OverlayRotate(Lay1, invoker.SwitchAnim?-2:2, WOF_ADD);
				A_OverlayScale(Lay1, -.025, -.025, WOF_ADD);
				
				if(invoker.SwitchState>1){invoker.SwitchState--;A_SetTics(0);}
			}
			#### # 1 {
				A_OverlayOffset(Lay1, invoker.SwitchAnim?1:-1, -1, WOF_ADD);
				A_OverlayScale(Lay1, -.015, -.015, WOF_ADD);
				
				if(invoker.SwitchState>1){invoker.SwitchState--;A_SetTics(0);}
			}
			#### ########## 1 {
				A_OverlayOffset(Lay1, invoker.SwitchAnim?-7:7, 7, WOF_ADD);
				A_OverlayRotate(Lay1, invoker.SwitchAnim?-2:2, WOF_ADD);
				
				if(invoker.SwitchState>1){invoker.SwitchState--;A_SetTics(0);}
			}
			#### # 0 A_OverlayFlags(Lay1, PSPF_INTERPOLATE, false);
			#### # 0 A_JumpIf(Player.GetPSprite(PSP_WEAPON).Y<=40, "GunRaise");
			Stop;

		RifleFire:
			R1FG A 0{
				A_DoVanillaDisplay();
				if(invoker.LastScal == 0){
					invoker.LastScal = 1;
					invoker.LastPos = (0,0);
				}
				A_OverlayPivot(Lay1, CFRandom(.45, .6), CFRandom(.4, .6));
				A_OverlayOffset(Lay1, invoker.LastPos.X, invoker.LastPos.Y, WOF_INTERPOLATE);
				A_OverlayRotate(Lay1, 0, WOF_INTERPOLATE);
				A_OverlayScale(Lay1, invoker.LastScal, invoker.LastScal, WOF_INTERPOLATE);
				
				A_GlovesColor(1);
			}
			#### # 0 A_JumpIf(GetCVar("MRIntW_InstantFire")||MRIntW_FastPistol, 5);
			#### A 1;
			#### A 1 A_OverlayOffset(Lay1, 0, -1, WOF_ADD);
			#### AA 1 A_OverlayOffset(Lay1, 0, 1, WOF_ADD);
			#### A 1;//Shot
			#### # 0{
				if(MRIntW_ScreenShake){
					Double Amnt = MRIntW_ScreenShakeAmount;
					A_QuakeEx(.05*Amnt,0,.15*Amnt, 5, 0, .5, "", QF_RELATIVE|QF_SCALEDOWN|QF_WAVE, 15,0,10, rollIntensity: .1*Amnt, rollwave: 1);
				}
				invoker.RecRot = (Player.GetPSprite(Lay1).Pivot.X-.5)*invoker.ShotPower;
			}
			#### A 1 {
				A_OverlayFlags(Lay1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay1).FirstTic);
				Vector2 Scal = (.15+.01*invoker.ShotPower, 0);
				Scal.Y = Scal.X*1.5;
				Vector2 Ofst = (0, 11+2*invoker.ShotPower);
				A_OverlayScale(Lay1, Scal.X, Scal.Y, WOF_ADD);
				A_OverlayOffset(Lay1, Ofst.X, Ofst.Y, WOF_ADD);
				A_OverlayRotate(Lay1, invoker.RecRot, WOF_ADD);
				
				A_OverlayScale(Lay2, Scal.X, Scal.Y, WOF_ADD);
				A_OverlayOffset(Lay2, Ofst.X, Ofst.Y, WOF_ADD);
				A_OverlayRotate(Lay2, invoker.RecRot, WOF_ADD);
				
				Ofst *= .4;
				A_OverlayOffset(Lay3, Ofst.X, Ofst.Y, WOF_ADD);
				
				A_FireSmoke(-.3-Player.GetPSprite(Lay1).Y*.015, .8);
			}
			#### A 1 {
				Vector2 Scal = (.025+.004*invoker.ShotPower, 0);
				Scal.Y = Scal.X*1.5;
				Vector2 Ofst = (0, 3+invoker.ShotPower*.75);
				A_OverlayScale(Lay1, Scal.X, Scal.Y, WOF_ADD);
				A_OverlayOffset(Lay1, Ofst.X, Ofst.Y, WOF_ADD);
				A_OverlayRotate(Lay1, invoker.RecRot*.5, WOF_ADD);
				
				A_OverlayScale(Lay2, Scal.X, Scal.Y, WOF_ADD);
				A_OverlayOffset(Lay2, Ofst.X, Ofst.Y, WOF_ADD);
				A_OverlayRotate(Lay2, invoker.RecRot*.5, WOF_ADD);
				
				Ofst *= .4;
				A_OverlayOffset(Lay3, Ofst.X, Ofst.Y, WOF_ADD);
				
				A_FireSmoke(-.3-Player.GetPSprite(Lay1).Y*.015, .8);
			}
			#### A 1{
				Vector2 Scal = (.015+.004*invoker.ShotPower, 0);
				Scal.Y = Scal.X*1.5;
				Vector2 Ofst = (0, 1.5+.4*invoker.ShotPower);
				A_OverlayScale(Lay1, Scal.X, Scal.Y, WOF_ADD);
				A_OverlayOffset(Lay1, Ofst.X, Ofst.Y, WOF_ADD);
				A_OverlayRotate(Lay1, invoker.RecRot*.5, WOF_ADD);
				
				A_OverlayScale(Lay2, Scal.X, Scal.Y, WOF_ADD);
				A_OverlayOffset(Lay2, Ofst.X, Ofst.Y, WOF_ADD);
				A_OverlayRotate(Lay2, invoker.RecRot*.5, WOF_ADD);
				
				Ofst *= .4;
				A_OverlayOffset(Lay3, Ofst.X, Ofst.Y, WOF_ADD);
				
				A_FireSmoke(-.3-Player.GetPSprite(Lay1).Y*.015, .8);
				
				if(!GetCVar("MRIntW_Casings"))Return;
				int index;
				For(index=0;index<invoker.Casings.Size()+1;index++){
					if(index>=invoker.Casings.Size()){index=-1;Break;}
					if(!invoker.Casings[index]){invoker.Casings[index] = true;Break;}
				}

				if(index<invoker.Casings.Size() && index>-1){
					A_Overlay(PSP_FLASH+10+index, "CasingLay");
					invoker.CasingDir[index] = CFRandom(-.7, 1.5);
					A_OverlayOffset(PSP_FLASH+10+index, 187+Player.GetPSprite(PSP_WEAPON).OldX, 157+Player.GetPSprite(PSP_WEAPON).OldY);
					A_OverlayScale(PSP_FLASH+10+index, .8, .8);
				}
				A_FireSmoke(-.3-Player.GetPSprite(Lay1).Y*.015, .8);
			}
			#### AA 1{
				Vector2 Scal = (.001+.007*invoker.ShotPower, 0);
				Scal.Y = Scal.X*2;
				A_OverlayScale(Lay1, Scal.X, Scal.Y, WOF_ADD);
				A_OverlayRotate(Lay1, invoker.RecRot*.5, WOF_ADD);
				
				A_OverlayScale(Lay2, Scal.X, Scal.Y, WOF_ADD);
				A_OverlayRotate(Lay2, invoker.RecRot*.5, WOF_ADD);
			}
			#### # 0 {
				invoker.RecOfst = (CFRandom(-4, 4), CFRandom(-2, 4));
				invoker.RecScal = CFRandom(.95, .98);
			}
			#### AAA 1{
				Float Recover = CFRandom(.6, .7);
				A_OverlayMoveTo(Lay1, invoker.RecOfst.X, invoker.RecOfst.Y, Recover);
				Player.GetPSprite(Lay1).Scale = (invoker.RecScal,invoker.RecScal)+(Player.GetPSprite(Lay1).Scale-(invoker.RecScal,invoker.RecScal))*Recover;
			
				invoker.LastPos = (Player.GetPSprite(Lay1).X, Player.GetPSprite(Lay1).Y);
				invoker.LastScal = Player.GetPSprite(Lay1).Scale.X;
			}
			#### A 1{
				Float Recover = CFRandom(.8, .9);
				A_OverlayMoveTo(Lay1, invoker.RecOfst.X, invoker.RecOfst.Y, Recover);
				Player.GetPSprite(Lay1).Scale = (invoker.RecScal,invoker.RecScal)+(Player.GetPSprite(Lay1).Scale-(invoker.RecScal,invoker.RecScal))*Recover;
			
				invoker.LastPos = (Player.GetPSprite(Lay1).X, Player.GetPSprite(Lay1).Y);
				invoker.LastScal = Player.GetPSprite(Lay1).Scale.X;
			}
			#### AAAA 1{
				Player.GetPSprite(Lay1).Scale = (1,1)+(Player.GetPSprite(Lay1).Scale-(1,1))*.4;
				A_OverlayMoveTo(Lay1, 0, 0, .4);
				Player.GetPSprite(Lay1).Rotation *= .4;
				
				invoker.LastPos = (Player.GetPSprite(Lay1).X, Player.GetPSprite(Lay1).Y);
				invoker.LastScal = Player.GetPSprite(Lay1).Scale.X;
			}
			#### A 1{
				A_OverlayScale(Lay1, 1, 1, WOF_INTERPOLATE);
				A_OverlayOffset(Lay1, 0, 0, WOF_INTERPOLATE);
				A_OverlayRotate(Lay1, 0, WOF_INTERPOLATE);
			}
			Goto GunWait;
		RifleFlash:
			RIFF A 1 BRIGHT {
				A_OverlayOffset(Lay2, Player.GetPSprite(Lay1).X, Player.GetPSprite(Lay1).Y);
				Player.GetPSprite(Lay1).Scale = Player.GetPSprite(Lay1).Scale;
				A_OverlayFlags(Lay2, PSPF_RENDERSTYLE|PSPF_ALPHA, true);
				A_OverlayRenderStyle(Lay2, STYLE_ColorAdd);
				Player.GetPSprite(OverlayId()).Pivot = Player.GetPSprite(Lay1).Pivot;
				if(GetCVar("MRIntW_NoMuzzleFlash"))A_OverlayRenderStyle(OverlayId(), STYLE_None);
			}
			RIFF BCD 1 BRIGHT;
			Stop;
		
		RifleCoolIdle:
			R1FG A 0{
				A_OverlayPivot(Lay1, .7, 0);
				Switch(CRandom(0, 10))
				{
					Case 1:Return ResolveState("RifleCoolIdleBFG");
					Case 2:Return ResolveState("RifleCoolIdleRandom");
					Case 3:Return ResolveState("RifleCoolIdleStroke");
				}
				
				Return ResolveState(Null);
			}
			#### # 0 A_StartSound("weapons/shotgr", CHAN_WEAPON, pitch:CFRandom(.97, 1.02)*i_timescale);
			#### ## 1 {
				A_OverlayMoveTo(Lay1, 15, 30, .5);
				Player.GetPSprite(Lay1).Scale = (1.4,1.4)+(Player.GetPSprite(Lay1).Scale-(1.4,1.4))*.5;
				Player.GetPSprite(Lay1).Rotation = 10+(Player.GetPSprite(Lay1).Rotation-10)*.5;
			}
			#### # 0 {
				int index;
				For(index=0;index<invoker.Casings.Size()+1;index++){
					if(index>=invoker.Casings.Size()){index=-1;Break;}
					if(!invoker.Casings[index]){invoker.Casings[index] = true;Break;}
				}

				if(index<invoker.Casings.Size() && index>-1){
					A_Overlay(PSP_FLASH+10+index, "CasingLay");
					invoker.CasingDir[index] = CFRandom(-.7, 1.5);
					A_OverlayOffset(PSP_FLASH+10+index, 172+Player.GetPSprite(PSP_WEAPON).OldX+Player.GetPSprite(Lay1).X, 130+Player.GetPSprite(Lay1).Y+Player.GetPSprite(PSP_WEAPON).OldY);
					A_OverlayScale(PSP_FLASH+10+index, .8, .8);
				}
			}
			#### ## 1{
				A_OverlayMoveTo(Lay1, 5, 10, .5);
				Player.GetPSprite(Lay1).Scale = (1.35,1.35)+(Player.GetPSprite(Lay1).Scale-(1.35,1.35))*.5;
				Player.GetPSprite(Lay1).Rotation = 10+(Player.GetPSprite(Lay1).Rotation-10)*.5;
			}
			#### #### 1 {
				A_OverlayMoveTo(Lay1, 0, 0, .6);
				Player.GetPSprite(Lay1).Scale = (1,1)+(Player.GetPSprite(Lay1).Scale-(1,1))*.6;
				Player.GetPSprite(Lay1).Rotation *= .6;
			}
			Goto GunWait;
		RifleCoolIdleBFG:
			R1FG A 40 {
				Float Pit = CFRandom(.4, 1.5);
				A_StartSound("MRIntW/BFGFireStart", CHAN_AUTO, CHANF_MAYBE_LOCAL, pitch:Pit*i_timescale);
				A_SetTics(40/Pit);
			}
			Goto RifleCoolIdleBlank;
		RifleCoolIdleRandom:
			R1FG A 1 {
				A_StartSound(CRandomPick(CRandom(1, 23), CRandom(225, 639)), CHAN_AUTO, CHANF_MAYBE_LOCAL, pitch: CFRandom(.2, 4));
			}
		RifleCoolIdleBlank:
			R1FG A 10{
				int index;
				For(index=0;index<invoker.Casings.Size()+1;index++){
					if(index>=invoker.Casings.Size()){index=-1;Break;}
					if(!invoker.Casings[index]){invoker.Casings[index] = true;Break;}
				}

				if(index<invoker.Casings.Size() && index>-1){
					A_Overlay(PSP_FLASH+10+index, "CasingLay");
					invoker.CasingDir[index] = CFRandom(-.7, 1.5);
					A_OverlayOffset(PSP_FLASH+10+index, 182+Player.GetPSprite(PSP_WEAPON).OldX, 152+Player.GetPSprite(PSP_WEAPON).OldY);
					A_OverlayScale(PSP_FLASH+10+index, .8, .8);
				}
			}
			Goto GunWait;
		
		RifleCoolIdleStroke:
			R1FG A 1 {
				invoker.spriteAngle = CFRandom(5, 20);
				A_OverlayMoveTo(Lay1, CFRandom(-2, 2), CFRandom(3, 5), .7);
				A_StartSound("*usefail", CHAN_WEAPON, CHANF_MAYBE_LOCAL, pitch:CFRandom(.95, 1));
			}
			#### ########### 1 {
				A_OverlayMoveTo(Lay1, -invoker.SpriteAngle*.5, -invoker.SpriteAngle, .7);
				Float Pitch = Player.GetPSprite(Lay1).Y/(-invoker.SpriteAngle);
				A_SoundPitch(CHAN_WEAPON, 1+Pitch);
			}
			#### # 1 {
				A_OverlayMoveTo(Lay1, invoker.SpriteAngle*.5, invoker.SpriteAngle*2, .2);
				A_OverlayScale(Lay1, 1-invoker.SpriteAngle*.005, 1+invoker.SpriteAngle*.05, WOF_INTERPOLATE);
				A_SoundPitch(CHAN_WEAPON, 1);
			}
			#### # 1 {
				A_OverlayMoveTo(Lay1, invoker.SpriteAngle*.5, invoker.SpriteAngle*2, .2);
				A_OverlayScale(Lay1, 1-invoker.SpriteAngle*.005, 1+invoker.SpriteAngle*.005, WOF_INTERPOLATE);
				invoker.ScaleX = true;
				
				int index;
				For(index=0;index<invoker.Casings.Size()+1;index++){
					if(index>=invoker.Casings.Size()){index=-1;Break;}
					if(!invoker.Casings[index]){invoker.Casings[index] = true;Break;}
				}

				if(index<invoker.Casings.Size() && index>-1){
					A_Overlay(PSP_FLASH+10+index, "CasingLay");
					invoker.CasingDir[index] = CFRandom(-.7, 1.5);
					A_OverlayOffset(PSP_FLASH+10+index, 182+Player.GetPSprite(PSP_WEAPON).OldX+Player.GetPSprite(Lay1).X, 120+Player.GetPSprite(Lay1).Y+Player.GetPSprite(PSP_WEAPON).OldY);
					A_OverlayScale(PSP_FLASH+10+index, .8, .8);
				}
				
				A_StartSound("weapons/bfgx", CHAN_AUTO, CHANF_MAYBE_LOCAL, pitch:CFRandom(1.5, 2));
			}
			#### # 1 {
				A_OverlayMoveTo(Lay1, 0, 0, .95);
				
				if(invoker.ScaleX){
					if(Player.GetPSprite(Lay1).Scale.X>=1+invoker.SpriteAngle*.03){
						invoker.ScaleX = false;
						invoker.SpriteAngle *= .9;
					}
					Player.GetPSprite(Lay1).Scale = (1+invoker.SpriteAngle*.05,1-invoker.SpriteAngle*.025)+(Player.GetPSprite(Lay1).Scale-(1+invoker.SpriteAngle*.05,1-invoker.SpriteAngle*.025))*.4;
				}
				else {
					if(Player.GetPSprite(Lay1).Scale.X<=1-invoker.SpriteAngle*.03){
						invoker.ScaleX = true;
						invoker.SpriteAngle *= .9;
					}
					Player.GetPSprite(Lay1).Scale = (1-invoker.SpriteAngle*.05,1+invoker.SpriteAngle*.05)+(Player.GetPSprite(Lay1).Scale-(1-invoker.SpriteAngle*.05,1+invoker.SpriteAngle*.05))*.4;
				}
				
				if(invoker.SpriteAngle<.1){
					invoker.Catch = false;
					invoker.SpriteAngle = 0;
					Player.SetPsprite(Lay1, invoker.FindState("GunWait"));
				}
			}
			Wait;
	}
	
	Bool ScaleX;
}