class MRIntWeaps_RocketLauncher : RocketLauncher Replaces RocketLauncher
{
	Default
	{
		Weapon.SlotNumber 5;
	}
	
	Const Lay1 = 2;//Main layer
	Const Lay2 = PSP_FLASH+1;//Gun flash
	Const Lay3 = -2;//Gun flash (explosion, behind the barrel)
	Const LightLay = PSP_FLASH+2;
	Const LayHand = -3;
	
	int BobState, IdleDelay, Muzzle, Explosions;
	Double RecoilDir;
	
	Float Recoil;
	Override Void DoEffect()
	{
		if(Recoil>0){
			Double Recover = .125*Owner.GetCVar("MRIntW_RecoilRecover");
			Recoil -= Recover;
			Owner.A_SetPitch(Owner.Pitch+Recover*Owner.GetCVar("MRIntW_RecoilAmount"));
		}
		
		MuzzleSmoke();
		
		if(!Owner.Player || Owner.Player.ReadyWeapon != Self || Health<1)Return;
		
		if(!Owner.Player.FindPSprite(PSP_WEAPON) || !InStateSequence(Owner.Player.FindPSprite(PSP_WEAPON).CurState, FindState("Ready")))Return;
		
		if(Owner.Player.Cmd.Buttons&BT_RELOAD && !Owner.Player.FindPSprite(LayHand))Owner.Player.SetPsprite(Lay1, FindState("GunShowingHand"));
		
		Owner.Player.GetPSprite(Lay1).Frame = Muzzle;
				
		if(Owner.Player.Cmd.Buttons&BT_ALTATTACK)Muzzle++;
		else if(Muzzle>0)Muzzle--;
		
		if(Muzzle>2)Muzzle = 2;
	}
	
	Vector2 RecOfst;
	Double RecScal;
	
	Action Void A_GlovesColor()
	{
		Let Feest = MRIntWeaps_Fist(FindInventory("MRIntWeaps_Fist"));
		if(!Feest)Return;
		
		Player.GetPSprite(OverlayId()).Translation = Feest.GlovesTrans;
	}
	
	Bool Reload;
	Override Void PostBeginPlay()
	{
		Super.PostBeginPlay();
		if(MRIntW_ReloadAnims>1)Reload = true;
	}
	
	int SwitchAnim, SwitchState;
	
	States{
		GunRaiseVanilla://Vanilla select animation
			MI1G C 1 {
				if(Player.GetPSprite(PSP_WEAPON).Y<=32)Player.SetPsprite(Lay1, invoker.FindState("GunWait"));
			}
			Wait;
		GunLowerVanilla://Vanilla deselect animation
			MI1G A 1;
			Wait;
		GunRaise:
			TNT1 A 0 A_JumpIf(invoker.Reload, "GunRaiseReload");
			TNT1 A 0{
				if(MRIntW_SwitchAnims>1)invoker.SwitchAnim = CRandom(0, 1);
			}
			TNT1 AAA 1 {
				A_OverlayFlags(Lay1, PSPF_ADDWEAPON , false);
				A_OverlayPivot(Lay1, .5, .5);
				A_OverlayOffset(Lay1, invoker.SwitchAnim?-61:61, 80);
				A_OverlayScale(Lay1, .5, .5);
				A_OverlayRotate(Lay1, invoker.SwitchAnim?20:-20);
				invoker.SwitchState = 12;
			}
			MI1G C 1;
			MI1G CCCCCCCC 1 {
				int XMove = invoker.SwitchAnim?8:-8;
				A_OverlayMoveTo(Lay1, XMove, 32-9, .8, .5);
				A_OverlayScale(Lay1, .05, .05, WOF_ADD);
				A_OverlayRotate(Lay1, invoker.SwitchAnim?-2:2, WOF_ADD);
				invoker.SwitchState--;
			}
			MI1G CCC 1 {
				int XMove = invoker.SwitchAnim?3:-3;
				A_OverlayMoveTo(Lay1, XMove, 35, .8, .5);
				A_OverlayScale(Lay1, 1, 1, WOF_INTERPOLATE);
				A_OverlayRotate(Lay1, invoker.SwitchAnim?-1.5:1.5, WOF_ADD);
				invoker.SwitchState--;
			}
			MI1G C 1{
				A_OverlayOffset(Lay1, 0, 36, WOF_INTERPOLATE);
				A_OverlayScale(Lay1, 1, 1, WOF_INTERPOLATE);
				A_OverlayRotate(Lay1, 0, WOF_INTERPOLATE);
				invoker.Muzzle = 2;
				invoker.BobState = 0;
				invoker.SwitchState = 0;
			}
			#### # 0 {A_OverlayFlags(Lay1, PSPF_ADDWEAPON, true);A_OverlayOffset(Lay1, 0, 0);}
			MI1G CCCCCC 1 {
				Player.GetPSprite(Lay1).Y *= 1;
				Player.GetPSprite(Lay1).Frame = invoker.Muzzle;
				
				if(invoker.Muzzle>0)invoker.Muzzle--;
			}
		GunWait:
			MI1G # 1 {
				A_OverlayPivot(Lay1, .5, 0);
				A_IdleAnimation(Lay1);
			}
			#### # 0 {if(MRIntW_BobRangeZ==0)A_OverlayFlags(Lay1, PSPF_INTERPOLATE, false);}
			#### # 0 A_JumpIf(invoker.IdleDelay>35 && GetCVar("MRIntW_IdleAnims")>1 && abs(invoker.BobState)<2, "GunIdle1");
			Loop;
		GunLower:
			#### # 0 A_JumpIf(invoker.SwitchAnim>1, "GunLowerReload");
			MI1G A 1 {
				invoker.IdleDelay = Min(invoker.IdleDelay, 0);
				if(invoker.SwitchState>0){invoker.SwitchState--;A_SetTics(0);}
				else if(MRIntW_SwitchAnims>1)invoker.SwitchAnim = CRandom(0, 1);
				A_OverlayFlags(Lay1, PSPF_ADDWEAPON, false);
				A_OverlayPivot(Lay1, .5, .5);
				A_OverlayOffset(Lay1, Player.GetPSprite(PSP_WEAPON).OldX, invoker.SwitchState<1?Player.GetPSprite(PSP_WEAPON).OldY:32);
				A_OverlayRotate(Lay1, 0);
				A_OverlayScale(Lay1, 1, 1);
			}
			MI1G ### 1 {
				A_OverlayOffset(Lay1, invoker.SwitchAnim?-6:6, -4, WOF_ADD);
				A_OverlayRotate(Lay1, invoker.SwitchAnim?4.2:-4.2, WOF_ADD);
				
				if(invoker.SwitchState>0){invoker.SwitchState--;A_SetTics(0);}
			}
			MI1G # 1 {
				A_OverlayOffset(Lay1, invoker.SwitchAnim?-5:5, 7, WOF_ADD);
				A_OverlayScale(Lay1, -.05, -.05, WOF_ADD);
				A_OverlayRotate(Lay1, invoker.SwitchAnim?1.4:-1.4, WOF_ADD);

				if(invoker.SwitchState>0){invoker.SwitchState--;A_SetTics(0);}
			}
			Wait;
		GunRaiseReload:
			MI1G CC 1{
				A_DoVanillaDisplay();
				invoker.SwitchAnim = 2;
				A_GlovesColor();
				A_OverlayFlags(Lay1, PSPF_ADDWEAPON, false);
				A_OverlayPivot(Lay1, .5, 1);
				A_OverlayOffset(Lay1, 84, 120);
				A_OverlayScale(Lay1, 2.3, 1.5);
				A_OverlayPivot(Lay1, .5, .5);
			}
			MI1G C 1 {
				A_StartSound("MRIntW/RLLoad", CHAN_AUTO, Pitch:.4);
				A_StartSound("weapons/shotgr", CHAN_AUTO, Pitch:.9);
				Player.GetPSprite(Lay1).Scale = (1.05,.95)+(Player.GetPSprite(Lay1).Scale-(1.05,.95))*.7;
				A_OverlayMoveTo(Lay1, 0, 20, .7);
				A_OverlayFlags(Lay1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay1).FirstTic);
			}
			#### CCCC 1 {
				Player.GetPSprite(Lay1).Scale = (1.05,.95)+(Player.GetPSprite(Lay1).Scale-(1.05,.95))*.7;
				A_OverlayMoveTo(Lay1, 0, 20, .7);
			}
			#### BA 1 {
				Player.GetPSprite(Lay1).Scale = (1.05,.95)+(Player.GetPSprite(Lay1).Scale-(1.05,.95))*.7;
				A_OverlayMoveTo(Lay1, 0, 20, .7);
			}
			#### ## 1 {
				invoker.Reload = false;
				Player.GetPSprite(Lay1).Scale = (1.2,1.1)+(Player.GetPSprite(Lay1).Scale-(1.2,1.1))*.5;
				A_OverlayMoveTo(Lay1, 0, 52, .5);
			}
			#### ##### 1 {
				Player.GetPSprite(Lay1).Scale = (1,1)+(Player.GetPSprite(Lay1).Scale-(1,1))*.7;
				A_OverlayMoveTo(Lay1, 0, 32, .7);
			}
			#### # 1 {
				A_OverlayFlags(Lay1, PSPF_ADDWEAPON, true);
				Player.GetPSprite(Lay1).OldY -= 32;
				Player.GetPSprite(Lay1).Y -= 32;
				A_OverlayMoveTo(Lay1, 0, 0, .6);
				Player.GetPSprite(Lay1).Scale = (1,1)+(Player.GetPSprite(Lay1).Scale-(1,1))*.6;
				invoker.SwitchAnim = 0;
				invoker.SwitchState = 0;
			}
			Goto GunWait;
		GunLowerReload:
			#### # 1 {
				A_OverlayMoveTo(Lay1, 50, 120, .8);
				A_OverlayScale(Lay1, -.15, -.15, WOF_ADD);
				A_OverlayRotate(Lay1, -1, WOF_ADD);
			}
			Wait;
		
		GunIdle1:
			#### # 0 {
				A_OverlayPivot(Lay1, .5, 0);
				invoker.BobState = 0;
				invoker.IdleDelay = CRandom(-10, -3)*70;
				if((GetCVar("MRIntW_BersShake")>1 && FindInventory("PowerStrength"))||(Health<20 && GetCVar("MRIntW_LowHealthShake")))invoker.IdleDelay = CRandom(1, -3)*35;
			}
			#### # 0 A_JumpIf(CRandom(0, 255)<100, "GunIdle2");
			#### AAAA 1 {A_Overlayoffset(Lay1, -.15, .05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AA 1 {A_OverlayOffset(Lay1, -.1, .05, WOF_ADD);A_OverlayRotate(Lay1, -.1, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AAA 1 {A_OverlayOffset(Lay1, .15, -.1, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AA 1 {A_OverlayOffset(Lay1, .15, -.025, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### A 1 {A_OverlayOffset(Lay1, .1, .0, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AA 1 {A_OverlayOffset(Lay1, .1, .025, WOF_ADD);A_OverlayRotate(Lay1, .05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AAA 1 {A_OverlayOffset(Lay1, .025, .05, WOF_ADD);A_OverlayRotate(Lay1, .05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AA 1 {A_OverlayOffset(Lay1, -.05, -.1, WOF_ADD);A_OverlayRotate(Lay1, -.05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### A 1 {A_OverlayOffset(Lay1, .0, .05, WOF_ADD);A_OverlayRotate(Lay1, .05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### A 2 {
				A_OverlayRotate(Lay1, 0, WOF_INTERPOLATE);
				A_Overlayoffset(Lay1, 0, 0, WOF_INTERPOLATE);
				A_BersShake();
				A_SetTics(CRandom(1,2));
			}
			#### # 0 A_JumpIf(CRandom(0, 10)<4, "GunIdle2");
			#### # 0 A_JumpIf(CRandom(0, 40)==1, "GunIdle1");
			Goto GunWait;
		GunIdle2:
			#### A 1 {A_Overlayoffset(Lay1, .0, .05, WOF_ADD);A_OverlayRotate(Lay1, -.05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AA 1 {A_Overlayoffset(Lay1, .05, -.1, WOF_ADD);A_OverlayRotate(Lay1, .05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AAA 1 {A_Overlayoffset(Lay1, -.025, .05, WOF_ADD);A_OverlayRotate(Lay1, -.05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AA 1 {A_Overlayoffset(Lay1, -.1, .025, WOF_ADD);A_OverlayRotate(Lay1, -.05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### A 1 {A_Overlayoffset(Lay1, -.1, .0, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AA 1 {A_Overlayoffset(Lay1, -.15, -.025, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AAA 1 {A_Overlayoffset(Lay1, -.15, -.1, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AA 1 {A_Overlayoffset(Lay1, .1, .05, WOF_ADD);A_OverlayRotate(Lay1, .1, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			#### AAAA 1 {A_Overlayoffset(Lay1, .15, .05, WOF_ADD);A_BersShake(); A_SetTics(CRandom(1,2));}
			Goto GunWait;
			
		GunFire:
			MI1G A 0 {
				A_OverlayPivot(Lay1, .5, .5);
				if(!Player.GetPSprite(Lay1).bAddWeapon){
					Player.GetPSprite(Lay1).bAddWeapon = true;
					Player.GetPSprite(Lay1).Y -= 32;
					Player.GetPSprite(Lay1).OldY -= 32;
				}
			}
			#### # 0 A_JumpIf(GetCVar("MRIntW_InstantFire"), 7);
			MI1G AAABBCC 1 {A_OverlayOffset(Lay1, 0, .5, WOF_ADD);A_OverlayScale(Lay1, .01, .01, WOF_ADD);}
			#### # 0 A_Overlay(Lay2, "GunFlash");
			MI1G C 1 {
				invoker.Fire += 20;
				A_OverlayPivot(Lay1, .5, 0);
				A_OverlayPivot(Lay2, .5, 0);
				Player.GetPSprite(Lay2).Scale = (1,1);
				Player.GetPSprite(Lay2).Rotation = 0;
				invoker.RecoilDir = CFRandom(-2, 2);
			}
			MI1G CC 1 {//Shot
				invoker.Fire += 20;
				A_OverlayScale(Lay1, .4, .4, WOF_ADD);
				A_OverlayOffset(Lay1, invoker.RecoilDir, 2, WOF_ADD);
				A_OverlayRotate(Lay1, -invoker.RecoilDir, WOF_ADD);
				
				A_OverlayScale(Lay2, .4, .4, WOF_ADD);
				A_OverlayOffset(Lay2, invoker.RecoilDir, 2, WOF_ADD);
				A_OverlayRotate(Lay2, -invoker.RecoilDir, WOF_ADD);
				A_OverlayFlags(Lay2, PSPF_INTERPOLATE, false);
				
				A_FireSmoke();
			}
			#### # 0{
				if(MRIntW_ScreenShake){
					Double Amnt = MRIntW_ScreenShakeAmount;
					A_QuakeEx(.5*Amnt,0,.5*Amnt, 14, 0, .5, "", QF_RELATIVE|QF_SCALEDOWN|QF_WAVE, 5,0,2, rollIntensity: .15*Amnt, rollwave: 5);
				}
			}
			MI1G CC 1{
				invoker.Fire += 20;
				A_OverlayFlags(Lay1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay1).FirstTic);
				A_OverlayScale(Lay1, .15, .15, WOF_ADD);
				A_OverlayOffset(Lay1, invoker.RecoilDir*.5, 7, WOF_ADD);
				
				A_FireSmoke();
			}
			MI1G C 1{
				invoker.Fire += 20;
				invoker.RecOfst = (CFRandom(-4, 4), CFRandom(-2, 4));
				invoker.RecScal = CFRandom(.95, .98);
				
				A_FireSmoke();
			}
			MI1G CCCCB 1{
				invoker.Fire++;
				Float Recover = CFRandom(.6, .7);
				A_OverlayMoveTo(Lay1, invoker.RecOfst.X, invoker.RecOfst.Y, Recover);
				Player.GetPSprite(Lay1).Scale = (invoker.RecScal,invoker.RecScal)+(Player.GetPSprite(Lay1).Scale-(invoker.RecScal,invoker.RecScal))*Recover;
				Player.GetPSprite(Lay1).Rotation *= Recover;
			}
			MI1G AAAA 1{
				Float Recover = CFRandom(.6, .7);
				A_OverlayMoveTo(Lay1, 0, 0, Recover);
				Player.GetPSprite(Lay1).Scale = (1,1)+(Player.GetPSprite(Lay1).Scale-(1,1))*Recover;
				Player.GetPSprite(Lay1).Rotation *= Recover;
			}
			#### A 1{
				A_OverlayOffset(Lay1, 0, 0, WOF_INTERPOLATE);
				A_OverlayScale(Lay1, 1, 1, WOF_INTERPOLATE);
				A_OverlayRotate(Lay1, 0, WOF_INTERPOLATE);
			}
			Goto GunWait;
			
		GunFlash:
			MI1F A 1 BRIGHT {
				A_OverlayFlags(Lay2, PSPF_RENDERSTYLE|PSPF_ALPHA, true);
				A_OverlayRenderStyle(Lay2, STYLE_ColorAdd);
				if(GetCVar("MRIntW_NoMuzzleFlash"))A_OverlayRenderStyle(OverlayId(), STYLE_None);
			}
			MI1F B 1 BRIGHT;
			#### # 0 {
				A_Overlay(Lay3-invoker.Explosions, "GunFlash2");
				A_OverlayOffset(Lay3-invoker.Explosions, Player.GetPSprite(Lay2).X, Player.GetPSprite(Lay2).Y);
				invoker.Explosions++;
			}
			Stop;
		GunFlash2:
			MI1F C 1 BRIGHT {
				A_OverlayPivot(OverlayId(), .5, .5);
				A_OverlayFlags(OverlayId(), PSPF_RENDERSTYLE|PSPF_ALPHA|PSPF_FORCESTYLE|PSPF_FORCEALPHA, true);
				Player.GetPSprite(OverlayId()).Alpha = .7;
				A_OverlayRenderStyle(OverlayId(), STYLE_ADD);
				A_OverlayScale(Overlayid(), 1, 1);
				if(GetCVar("MRIntW_NoMuzzleFlash"))A_OverlayRenderStyle(OverlayId(), STYLE_None);
			}
			MI1F DD 1 BRIGHT A_OverlayScale(OverlayId(), .1, .1, WOF_ADD);
			#### # 0 A_OverlayScale(OverlayId(), 1, 1);
			MI1F E 1 BRIGHT;
			MI1F E 1 BRIGHT {A_OverlayScale(OverlayId(), .015, .015, WOF_ADD);A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE|PSPF_FORCESTYLE|PSPF_FORCEALPHA, true);}
			MI1F EEEE 1 BRIGHT {
				A_OverlayScale(OverlayId(), .025, .025, WOF_ADD);
				A_OverlayRenderStyle(OverlayId(), STYLE_ADD);
				Player.GetPSprite(OverlayId()).Alpha -= .2;
				if(GetCVar("MRIntW_NoMuzzleFlash")||Player.GetPSprite(OverlayId()).Alpha<=0)A_OverlayRenderStyle(OverlayId(), STYLE_None);
			}
			#### # 0 {invoker.Explosions--;}
			Stop;
		
		
		GunShowingHand:
			MI1G A 0 A_Overlay(LayHand, "HandShowing");
			MI1G # 1 {
				A_OverlayMoveTo(Lay1, 50, 20, .9);
				Player.GetPSprite(Lay1).Rotation = 10 + (Player.GetPSprite(Lay1).Rotation-10)*.9;
				if(!Player.GetPSprite(Lay1).bAddWeapon){
					Player.GetPSprite(Lay1).bAddWeapon = true;
					Player.GetPSprite(Lay1).Y -= 32;
					PlayeR.GetPSprite(Lay1).OldY -= 32;
				}
			}
			#### # 0 A_JumpIf(abs(Player.GetPSprite(Lay1).X - 50)<1 && abs(Player.GetPSprite(Lay1).Y - 20)<1, 1);
			Goto GunShowingHand+1;
			#### ################################ 1 {
				A_OverlayMoveTo(Lay1, 50+CFRandom(-1, 2), 20+CFRandom(0, 3), .95);
			}
		GunUnshowingHand:
			#### # 1 {
				A_OverlayMoveTo(Lay1, 0, 0, .95);
				Player.GetPSprite(Lay1).Rotation *= .95;
			}
			#### # 0 A_JumpIf(abs(Player.GetPSprite(Lay1).X)<1 && abs(Player.GetPSprite(Lay1).Y)<1, "GunWait");
			Loop;
			
		HandShowing:
			MRD1 G 1 {
				A_DoVanillaDisplay();
				A_GlovesColor();
				A_OverlayFlags(LayHand, PSPF_MIRROR, true);
				A_OverlayPivot(LayHand, 1, 1);
				Player.GetPSprite(LayHand).X = 180;
				Player.GetPSprite(LayHand).Y = 80;
				A_OverlayRotate(LayHand, -30);
				A_OverlayScale(LayHand, .9, .9);
			}
			#### ####################################################### 1 {
				Player.GetPSprite(LayHand).Rotation *= .95;
				A_OverlayMoveTo(LayHand, 240, -10, .95);
				A_OverlayFlags(LayHand, PSPF_INTERPOLATE, !Player.GetPSprite(LayHand).FirstTic);
			}
		HandBackoff:
			#### ################################ 1 {
				if(InStateSequence(Player.GetPSprite(Lay1).CurState, invoker.FindState("GunFire"))){
					Player.GetPSprite(LayHand).Rotation = 30 + (Player.GetPSprite(LayHand).Rotation-30)*.8;
					A_OverlayMoveTo(LayHand, 240, 120, .8);
				}
				else {
					Player.GetPSprite(LayHand).Rotation = -60 + (Player.GetPSprite(LayHand).Rotation+60)*.98;
					A_OverlayMoveTo(LayHand, 180, 120, .98);
				}
			}
			Stop;
			
		
		//Default states
		
		Select:
			TNT1 A 0 {
				if(invoker.Dropped)invoker.Dropped.Destroy();
				if(MRIntW_SwitchAnims)A_Overlay(Lay1, "GunRaise");
				else A_Overlay(Lay1, "GunRaiseVanilla");
				Player.GetPSprite(PSP_WEAPON).Y = WEAPONBOTTOM;
				
				if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("MISGA0");
			}
		Raise:
			#### A 1 A_Raise();
			Loop;
		Deselect:
			TNT1 A 0 {
				if(Health<1){A_Overlay(Lay1, "GunDie");Return;}
				if(invoker.SwitchAnim>1){
					Player.SetPsprite(Lay1, invoker.FindState("GunLowerReload"));
				}
				else {
					if(MRIntW_SwitchAnims)A_Overlay(Lay1, "GunLower");
					else A_Overlay(Lay1, "GunLowerVanilla");
				}
				//Player.GetPSprite(PSP_WEAPON).Y = 32;
				
				if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("MISGA0");
			}
		Lower:
			#### A 1 A_Lower();
			Loop;
		Ready:
			TNT1 A 0 {
				if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("MISGA0");
			}
			#### A 1 {
				if(MRIntW_BobRangeZ!=0){
					Double BobZ = MRIntWeaps_Fist.GetBobZ(invoker, .5);
					A_OverlayScale(Lay1, 1+BobZ, 1+BobZ, WOF_INTERPOLATE);
					A_OverlayFlags(Lay1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay1).FirstTic);
				}
				A_WeaponReady();
			}
			Wait;
		Fire:
			TNT1 B 8 {
				if(!MRIntW_Lighting)A_GunFlash("Flash");
				Player.SetPsprite(Lay1, invoker.FindState("GunFire"));
				if(Player.FindPSprite(LayHand))Player.SetPsprite(LayHand, invoker.FindState("HandBackoff"));
				if(GetCVar("MRIntW_InstantFire"))A_SetTics(2);
				
				if(MRIntW_DisplayVanilla)Player.GetPSprite(PSP_WEAPON).Sprite = GetSpriteIndex("MISGA0");
			}
			#### B 12 {
				if(MRIntW_RocketSmoke)invoker.IncreaseSmoke();
				Actor a = A_FireProjectile("Rocket");
				if(a){
					a.A_StopSound();
					Let b = New('MRIntWeaps_PlayerProjectileParticles');
					b.Master = a;
					b.Type = 0;
				}
				A_StartSound("MRIntW/RLFire", CHAN_AUTO, pitch:i_timescale);
				
				if(GetCVar("MRIntW_Recoil")){invoker.Recoil=2.5;A_SetPitch(Pitch-2.5*GetCVar("MRIntW_RecoilAmount"), GetCVar("MRIntW_RecoilRecover")?0:SPF_INTERPOLATE);}//Recoil
				
				if(CountInv(invoker.AmmoType1)<1 && MRIntW_ReloadAnims%2==1)invoker.Reload = true;
			}
			#### A 6 {if(!GetCVar("MRIntW_InstantFire"))A_SetTics(0);else if(Player.GetPSprite(Lay1).Tics<4)A_WeaponReady(WRF_NOFIRE);}
			#### B 0 A_ReFire();
			Goto Ready;	
		Flash:
			TNT1 A 3 {
				A_Light1();
				
				if(MRIntW_DisplayVanilla)Player.GetPSprite(OverlayId()).Sprite = GetSpriteIndex("MISFA0");
			}
			#### B 4;
			#### CD 4 A_Light2();
			Goto LightDone;
	}
	
	Action Void A_IdleAnimation(int Lay = 2)//Idle hand bobbing
	{
		int CVa = GetCVar("MRIntW_IdleAnims");
		
		if(CVa%2==1){
			Bool Bers = (GetCVar("MRIntW_BersShake")>1 && FindInventory("PowerStrength"))||(Health<20 && GetCVar("MRIntW_LowHealthShake"));
			Float Mult = (Bers?2:1);
			if(invoker.BobState>=0){
				A_OverlayOffset(Lay, CFRandom(-.005, .015)*Mult, CFRandom(.01, .02)*Mult, WOF_ADD);
				if(invoker.BobState>90||Player.GetPSprite(Lay).Y>1.35){invoker.BobState = -invoker.BobState;}
				else invoker.BobState+=Mult;
			}
			else {
				A_OverlayOffset(Lay, -CFRandom(-.005, .015)*Mult, -CFRandom(.01, .02)*Mult, WOF_ADD);
				if(Player.GetPSprite(Lay).Y<0){A_OverlayOffset(Lay, 0, 0, WOF_INTERPOLATE);invoker.BobState = 0;}
				else if(!(invoker.BobState>=-1&&Player.GetPSprite(Lay).Y>0))invoker.BobState+=Mult;
			}
			if(Bers && GetAge()%2==0){//Shaking hand if got berserk
				A_OverlayOffset(Lay, CFRandom(-.25, .25), 0, WOF_INTERPOLATE|WOF_KEEPY);
				Player.GetPSprite(Lay).Y += CFRandom(-.25, .25);
				if(Player.GetPSprite(Lay).Y<0){Player.GetPSprite(Lay).Y = 0;invoker.BobState = 0;}
				if(Player.GetPSprite(Lay).Y>1.35){Player.GetPSprite(Lay).Y = 1.35;invoker.BobState = -90;}
			}
		}
		
		if(CVa>1){
			if(MRIntWeaps_Fist(FindInventory("MRIntWeaps_Fist"))){
				if(abs(MRIntWeaps_Fist(FindInventory("MRIntWeaps_Fist")).CurSway.X)<.0001)invoker.IdleDelay++;
				else invoker.IdleDelay = Min(0, invoker.IdleDelay);
			}
		}
	}
	
	Action Void A_BersShake()
	{
		if((GetCVar("MRIntW_BersShake")>1 && FindInventory("PowerStrength"))||(Health<20 && GetCVar("MRIntW_LowHealthShake")))A_OverlayOffset(Lay1, CFRandom(-.25, .25), CFRandom(-.25, .25), WOF_ADD);
	}
	
	Action Void A_OverlayMoveTo(int Lay = -1, Double XTo = 0, Double YTo = 0, Double SpeedX = .8, Double SpeedY = -1)
	{
		if(Lay == -1)Lay = OverlayId();
		if(SpeedY == -1)SpeedY = SpeedX;
		Player.GetPSprite(Lay).X = XTo + (Player.GetPSprite(Lay).X - XTo)*SpeedX;
		Player.GetPSprite(Lay).Y = YTo + (Player.GetPSprite(Lay).Y - YTo)*SpeedY;
	}
	
	Action Void A_DoVanillaDisplay()
	{
		if(!MRIntW_DisplayVanilla)Return;
		
		A_OverlayFlags(OverlayId(), PSPF_RENDERSTYLE|PSPF_ALPHA, true);
		
		if(GetRenderStyle()==STYLE_NORMAL){
			A_OverlayRenderStyle(OverlayId(), STYLE_TRANSLUCENT);
			Player.GetPSprite(OverlayId()).Alpha = Min(Player.GetPSprite(OverlayId()).Alpha, .5);
		}
	}
}