Extend Class MRIntWeaps_Fist
{
	Actor LineTarg;
	
	Action Void A_CopyMaster(int Master, int Lay=0, Vector2 AddOffset=(0,0), Double AddAngle=0)
	{
		if(Lay==0)Lay = OverlayId();
		
		Player.GetPSprite(Lay).X = Player.GetPSprite(Master).X + AddOffset.X;
		Player.GetPSprite(Lay).Y = Player.GetPSprite(Master).Y + AddOffset.Y;
		Player.GetPSprite(Lay).OldX = Player.GetPSprite(Master).OldX + AddOffset.X;
		Player.GetPSprite(Lay).OldY = Player.GetPSprite(Master).OldY + AddOffset.Y;
		
		if(Player.GetPSprite(Master).bFlip != Player.GetPSprite(Lay).bFlip)Player.GetPSprite(Lay).Rotation = -Player.GetPSprite(Master).Rotation - AddAngle;
		else Player.GetPSprite(Lay).Rotation = Player.GetPSprite(Master).Rotation + AddAngle;
		Player.GetPSprite(Lay).bInterpolate = Player.GetPSprite(Master).bInterpolate;
	}
	
	States
	{
		//Manual idle animations
		SecndHandCoolIdle:
			PUN1 A 1 {
				A_SetHandsSprite();
				A_OverlayPivot(OverlayId(), .5, .5);
				A_OverlayFlags(OverlayId(), PSPF_MIRROR|PSPF_FLIP, GetCVar("MRIntW_RightPunch"));
				Player.GetPSprite(OverlayId()).Translation = invoker.GlovesTrans;
				invoker.SecndHand = (0,0);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()).FirstTic);
				if(Player.FindPSprite(MainLay))Player.SetPsprite(MainLay, invoker.FindState("MainHandCoolIdle"));
				else Player.SetPsprite(MainLay, invoker.FindState("MainHandCoolIdlePre"));
				
				invoker.IdleState = 1;
			}
			#### # 0 {
				if(GetCVar("MRIntW_Braindead") && (Health==67 || (FindInventory("BasicArmor") && FindInventory("BasicArmor").Amount==67) || int(Level.Time/35)%67==0))Return ResolveState("SecndHandCoolIdle666");
				
				/*if(Health==69 || Health==169 || (FindInventory("BasicArmor") && (FindInventory("BasicArmor").Amount==69 || FindInventory("BasicArmor").Amount==169)) || int(Level.Time/35)%69==0)Return ResolveState("SecndHandCoolIdleRomero");
				
				invoker.LineTarg = Null;
				FLineTraceData CheckAct;
				Double PZ = height * .5 - floorclip + Player.mo.AttackZOffset*player.crouchFactor;
				LineTrace(Angle, 1500, Pitch, 0, PZ, 0, 0, CheckAct);
				
				if(CheckAct.HitActor != Null){
					if(CheckAct.HitActor.Target && CheckAct.HitActor.Target != Self)invoker.LineTarg = CheckAct.HitActor;
				
					if(invoker.LineTarg)Return ResolveState("SecndHandInfight");
				}*/
				
				/*Switch(CRandom(1, 1))
				{
					Case 1:
						Return ResolveState("SecndHandCoolIdle666");
				}*/
				Return ResolveState(Null);
			}
		//Fist bump
			#### E 1 {
				A_OverlayFlags(OverlayId(), PSPF_FLIP, !GetCVar("MRIntW_RightPunch"));
				A_OverlayScale(OverlayId(), 1.35, 1.35);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, false);
				Player.GetPSprite(OverlayId()).OldX = 260;
				Player.GetPSprite(OverlayId()).OldY = -10;
				
				Player.GetPSprite(OverlayId()).X = Player.GetPSprite(OverlayId()).OldX+CFRandom(9, 14);
				Player.GetPSprite(OverlayId()).Y = Player.GetPSprite(OverlayId()).OldY+CFRandom(-2, 2);
			}
			#### # 1 {
				A_StartSound("MRIntW/FistSwing", CHAN_AUTO, CHANF_LOCAL, .5, pitch:CFRandom(.9, 1.1)*i_timescale);
				A_OverlayOffset(OverlayId(), 265+20, -10+CFRandom(-4, 4), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.31, 1.35, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), -30, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), 1.25, 1.3, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_StartSound("MRIntW/FistPuch", CHAN_AUTO, CHANF_LOCAL, CFRandom(.5, .55), pitch: CFRandom(1.45, 1.55)*i_timescale);
				A_OverlayOffset(OverlayId(), 265 -50, -10+CFRandom(-2, 2), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.1, CFRandom(1.4, 1.45), WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 265 -50, -10+CFRandom(-1, 1), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.17, 1.4, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 265 -50, -10, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.2, 1.37, WOF_INTERPOLATE);
			}
			#### # 2 {
				A_OverlayOffset(OverlayId(), 265 -50, -10, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.25, 1.35, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(6, 8), -3, WOF_ADD);
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
				A_OverlayRotate(OverlayId(), 2, WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(18, 24), -3, WOF_ADD);
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
				A_OverlayRotate(OverlayId(), 2, WOF_ADD);
			}
			#### # 2 {
				A_StartSound("MRIntW/FistSwing", CHAN_AUTO, CHANF_LOCAL, .5, pitch:CFRandom(.9, 1.1)*i_timescale);
				A_OverlayOffset(OverlayId(), 265+CFRandom(50, 63), -10-9, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), -CFRandom(28, 34), 3, WOF_ADD);
				A_OverlayScale(OverlayId(), CFRandom(.03, .05), -CFRandom(.01, .02), WOF_ADD);
				A_OverlayRotate(OverlayId(), -4, WOF_ADD);
			}
			#### # 1 {
				A_StartSound("MRIntW/FistPuch", CHAN_AUTO, CHANF_Local, CFRandom(.5, .55), pitch: CFRandom(1.45, 1.55)*i_timescale);
				A_OverlayOffset(OverlayId(), 265 -50, -10+CFRandom(-3, 3), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.08, 1.37, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 265 -50, -10+CFRandom(-1, 1), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.15, 1.36, WOF_INTERPOLATE);
			}
			#### # 4 {
				A_OverlayOffset(OverlayId(), 265 -50, -10, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.2, 1.35, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(6, 8), 4, WOF_ADD);
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId(), CFRandom(16, 19), 4, WOF_ADD);
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
			}
			#### # 0 {
					A_OverlayOffset(OverlayId(), 0, 0);
					A_OverlayScale(OverlayId(), 1, 1);
			}
			Goto SecndHandWait;
		//Fist bump second hand
		MainHandCoolIdle:
			PUN1 C 1 {
				A_OverlayOffset(OverlayId(), invoker.MainHand.X, invoker.MainHand.Y);
				A_SetHandsSprite();
				A_OverlayPivot(OverlayId(), 1, .5);
				A_OverlayFlags(OverlayId(), PSPF_MIRROR|PSPF_FLIP, GetCVar("MRIntW_RightPunch"));
				Player.GetPSprite(OverlayId()).Translation = invoker.GlovesTrans;
				invoker.MainHand = (0,0);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()).FirstTic);
			}
			#### H 1 {
				A_OverlayOffset(OverlayId(), CFRandom(5, 7), CFRandom(-1, 1), WOF_ADD);
				A_OverlayScale(OverlayId(), -.05, CFRandom(.01, .02), WOF_ADD);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()).FirstTic);
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId(), CFRandom(5, 7), CFRandom(-1, 1), WOF_ADD);
				A_OverlayScale(OverlayId(), -.05, CFRandom(.01, .02), WOF_ADD);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()).FirstTic);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 30, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .75, 1.1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(29, 31), 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .7, 1.05, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(29, 31), 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .73, 1.075, WOF_INTERPOLATE);
			}
			#### # 2 {
				A_OverlayOffset(OverlayId(), 30, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .75, 1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), -.0001, CFRandom(.005, .01), WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), -.002, CFRandom(.005, .01), WOF_ADD);
			}
			#### # 2 {
				A_OverlayOffset(OverlayId(), 20, CFRandom(-2, 2), WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), CFRandom(.03, .05), -CFRandom(.01, .02), WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 30, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .67, 1.1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(29, 31), 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .7, 1.05, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(29, 31), 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .73, 1.075, WOF_INTERPOLATE);
			}
			#### # 5 {
				A_SetTics(CRandom(3, 5));
				A_OverlayOffset(OverlayId(), 30, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .75, 1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), .1, CFRandom(.005, .01), WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), .1, CFRandom(.005, .01), WOF_ADD);
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId(), -10, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), 1, 1, WOF_INTERPOLATE);
			}
			#### # 1 A_OverlayOffset(OverlayId(), 0, 0, WOF_INTERPOLATE);
			#### # 0 A_JumpIf(GetCVar("MRIntW_SecondFist")||(CountInv("PowerStrength") && GetCVar("MRIntW_BersShake")), "MainHandWait");
		MainHandCoolIdleEnd:
			#### ###### 1 A_OverlayOffset(OverlayId(), -10, 10, WOF_ADD);
			Stop;
			
		SecndHandInfight:
			PUN1 D 1 {
				A_OverlayFlags(OverlayId(), PSPF_MIRROR|PSPF_FLIP, GetCVar("MRIntW_RightPunch"));
				A_SetHandsSprite();
				Player.GetPSprite(SecndLay).Translation = invoker.GlovesTrans;
				A_OverlayPivot(OverlayId(), 1, .2);
				A_OverlayRotate(OverlayId(), 90);
			}
			#### # 0 {
				A_Overlay(MainLay+1, "SecndHandInfightOver");
				A_Overlay(MainLay, "InfightActor");
				
				A_Overlay(MainLay+2, "MainHandInfight");
				A_Overlay(MainLay+4, "SecndHandInfightOver");
				A_Overlay(MainLay+3, "InfightActor");
			}
			#### # 1 {
				A_OverlayOffset(SecndLay, 0, -40, WOF_INTERPOLATE);
				A_OverlayOffset(MainLay+2, 0, -40, WOF_INTERPOLATE);
			}
		SecndHandInfightLoop:
			#### # 1{
				if(!invoker.LineTarg || !invoker.LineTarg.Target || invoker.LineTarg.Health<1 || invoker.LineTarg.Target.Health<1){
					A_Overlay(SecndLay, "SecndHandWait");
					A_ClearOverlays(MainLay, MainLay+4);
				}
				
				if(
					!Player.FindPSprite(OverlayId()+6) && Player.GetPSprite(OverlayId()).Frame != 10 && (
					InStateSequence(invoker.LineTarg.CurState, invoker.LineTarg.FindState("Missile"))||
					InStateSequence(invoker.LineTarg.CurState, invoker.LineTarg.FindState("Melee")))
				)Player.SetPsprite(OverlayId()+6, invoker.FindState("HandInfightAttack"));
				
				if(
					!Player.FindPSprite(MainLay+2+6) && Player.GetPSprite(MainLay+2).Frame != 10 && (
					InStateSequence(invoker.LineTarg.Target.CurState, invoker.LineTarg.Target.FindState("Missile"))||
					InStateSequence(invoker.LineTarg.Target.CurState, invoker.LineTarg.Target.FindState("Melee")))
				)Player.SetPsprite(MainLay+2+6, invoker.FindState("HandInfightAttack"));
				
			}
			Wait;
		HandInfightAttack:
			#### ### 1 {
				A_OverlayOffset(OverlayId()-6, -4, -15, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, -4, WOF_ADD);
				
				A_OverlayFlags(OverlayId()-6, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-6).FirstTic);
				A_OverlayFlags(OverlayId()-4, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-4).FirstTic);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (90, 190), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, -2, -4, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, -2, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (90, 190), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1;
			#### ## 1 {
				A_OverlayOffset(OverlayId()-6, 50, 20, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, 10, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (90, 190), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, 5, 8, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, 3, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (90, 190), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, 2, 3, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, -1, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (90, 190), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, -3, -2, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, -1, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (90, 190), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ##### 1 {
				Player.GetPSprite(OverlayId()-6).X *= CFRandom(.6, .7);
				Player.GetPSprite(OverlayId()-6).Y = -40+(Player.GetPSprite(OverlayId()-6).Y+40)*CFRandom(.6, .7);
				A_OverlayRotate(OverlayId()-6, -1.5, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (90, 190), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 10 {
				A_OverlayRotate(OverlayId()-6, .5, WOF_ADD);
				A_OverlayOffseT(OverlayId()-6, 0, -40, WOF_INTERPOLATE);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (90, 190), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			Stop;
		SecndHandInfightOver:
			PUN1 A 0 {
				Player.GetPSprite(OverlayId()).Sprite = Player.GetPSprite(OverlayId()-2).Sprite;
				Player.GetPSprite(OverlayId()).Frame = Player.GetPSprite(OverlayId()-2).Frame + 5;
				Player.GetPSprite(OverlayId()).Translation = invoker.GlovesTrans;
				Player.GetPSprite(OverlayId()).Pivot = Player.GetPSprite(OverlayId()-2).Pivot;
			}
			#### # 1 {
				int Lay = OverlayId();
				A_CopyMaster(Lay-2);
				Player.GetPSprite(Lay).bMirror = Player.GetPSprite(Lay-2).bMirror;
				Player.GetPSprite(Lay).bFlip = Player.GetPSprite(Lay-2).bFlip;
			}
			Wait;
		MainHandInfight:
			PUN1 E 1 {
				A_OverlayFlags(OverlayId(), PSPF_MIRROR|PSPF_FLIP, !GetCVar("MRIntW_RightPunch"));
				A_SetHandsSprite();
				Player.GetPSprite(OverlayId()).Translation = invoker.GlovesTrans;
				A_OverlayPivot(OverlayId(), 1, .2);
				A_OverlayRotate(OverlayId(), 90);
			}
			#### # 1;
			Wait;
			
		InfightActor:
			TNT1 A 1 {
				int Lay = OverlayId();
				
				Let Act = invoker.LineTarg;
				if(Lay>MainLay+1)Act = invoker.LineTarg.Target;
				
				if(!Act){
					A_ClearOverlays(Lay, Lay);
					Return;
				}
				Let Stayt = Act.FindState("Spawn");
				TextureId Sprit = Stayt.GetSpriteTexture(0);
				
				int Akhtung;
				While(!Sprit.IsValid()){
					Stayt = Stayt.NextState;
					Sprit = Stayt.GetSpriteTexture(0);
					Akhtung++;
					
					if(Akhtung>2500)Break;
				}
				
				if(!Sprit.IsValid()){
					A_ClearOverlays(Lay, Lay);
					Return;
				}
				
				Vector2 Scale = Texman.GetScaledSize(Sprit);
				Scale.Y = Texman.CheckRealHeight(Sprit);
				
				Double Fit;
				if(Scale.X>Scale.Y)Fit = 55/Scale.X;
				else Fit = 50/Scale.Y;
				
				Console.Printf("Scale: "..Fit);
				
				Player.GetPSprite(Lay).Sprite = Stayt.Sprite;
				Player.GetPSprite(Lay).Frame = Stayt.Frame;
				Player.GetPSprite(Lay).Scale *= Fit;
				A_OverlayPivot(Lay, .5, 1);
				
				if(Scale.X>Scale.Y){
					A_ClearOverlays(Lay+1, Lay+1);
					Player.GetPSprite(Lay-1).Frame = 10;
				}
			}
			#### # 1{
				int Lay = OverlayId();
				A_CopyMaster(Lay-1, Lay, (90, 190), -90);
				Player.GetPSprite(Lay).bMirror = Player.GetPSprite(Lay-1).bMirror;
				
				if(Player.GetPSprite(Lay-1).Frame==10 && GetAge()%10==0){
					Let Act = invoker.LineTarg;
					if(Lay>MainLay+1)Act = invoker.LineTarg.Target;
					
					Player.GetPSprite(Lay).Sprite = Act.Sprite;
					Player.GetPSprite(Lay).Frame = Act.Frame;
				}
				//Player.GetPSprite(Lay).bFlip = Player.GetPSprite(Lay-1).bFlip;
			}
			Wait;
		
		
		//Nobody will like this one
		SecndHandCoolIdle666:
			#### # 0{
				if(Player.FindPSprite(MainLay))Player.SetPsprite(MainLay, invoker.FindState("MainHandWait"));
			}
			#### ######### 1 {
				A_OverlayOffset(SecndLay, -2, 5, WOF_ADD);
				A_OverlayOffset(MainLay, 2, 5, WOF_ADD);
			}
			TNT1 A 10 A_SetTics(CRandom(35, 40));
			MRD1 G 1 {
				A_Overlay(MainLay, "MainHandCoolIdle666");
				
				A_OverlayPivot(MainLay, .5, .5);
				Player.GetPSprite(MainLay).Translation = invoker.GlovesTrans;
				
				A_OverlayOffset(MainLay, 50, 68);
				A_OverlayFlags(MainLay, PSPF_MIRROR|PSPF_FLIP, GetCVar("MRIntW_RightPunch"));
				
				A_OverlayFlags(SecndLay, PSPF_FLIP, !GetCVar("MRIntW_RightPunch"));
				A_OverlayOffset(SecndLay, 200, 68);
				
				A_OverlayFlags(SecndLay, PSPF_INTERPOLATE, false);
				A_OverlayFlags(MainLay, PSPF_INTERPOLATE, false);
			}
			#### ############################ 1 {
				Player.GetPSprite(SecndLay).Y *= .9;
				Player.GetPSprite(MainLay).Y *= .9;
			}
			#### # 1 {
				A_SetTics(CRandom(6, 7));
				A_OverlayOffset(SecndLay, 200, 0, WOF_INTERPOLATE);
				A_OverlayOffset(MainLay, 50, 0, WOF_INTERPOLATE);
				invoker.IdleState = .99;
			}
		Hell:
			#### # 1 {
				Player.GetPSprite(SecndLay).Y = -50+(Player.GetPSprite(SecndLay).Y+50)*(1-invoker.IdleState);
				Player.GetPSprite(MainLay).Y = 20+(Player.GetPSprite(MainLay).Y-20)*(1-invoker.IdleState);
				if(Player.GetPSprite(MainLay).Y < 19.5*invoker.IdleState)Player.SetPsprite(SecndLay, Player.GetPSprite(SecndLay).CurState);
			}
			#### # 1;
			#### # 1 {
				Player.GetPSprite(MainLay).Y = -50+(Player.GetPSprite(MainLay).Y+50)*(1-invoker.IdleState);
				Player.GetPSprite(SecndLay).Y = 20+(Player.GetPSprite(SecndLay).Y-20)*(1-invoker.IdleState);
				if(Player.GetPSprite(SecndLay).Y < 19.5*invoker.IdleState)Player.SetPsprite(SecndLay, Player.GetPSprite(SecndLay).CurState);
			}
			#### # 1;
			#### # 0 {invoker.IdleState *= .9;}
			#### # 0 A_JumpIf(invoker.IdleState<.001, 1);
			Goto Hell;
			#### ### 1 {
				Player.GetPSprite(MainLay).Y *= .6;
				Player.GetPSprite(SecndLay).Y *= .6;
			}
			#### ###################### 1 {
				A_OverlayOffseT(SecndLay, 0, 5, WOF_ADD);
				A_OverlayOffseT(MainLay, 0, 5, WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffseT(SecndLay, 0, 70, WOF_INTERPOLATE);
				A_OverlayOffseT(MainLay, 0, 70, WOF_INTERPOLATE);
			}
			TNT1 A 7 A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, false);
			Goto SecndHandRaise;
			
		MainHandCoolIdle666:
			MRD1 G 1;
			Wait;
	}
}