/*
	Misc. weapon and player every-tic actions
*/

Extend Class MRIntWeaps_Fist
{
	Weapon Weap;
	Bool Allowed, OfstAdd;
	PSPrite PSP;
	
	Void DoMisc()
	{
		Weap = Owner.Player.ReadyWeapon;
		if(!Weap||!Owner.Player.FindPSprite(PSP_WEAPON))Return;
		PSP = Owner.Player.GetPSprite(PSP_WEAPON);
		Allowed = (!InStateSequence(PSP.curState, Weap.GetDownState()) && !InStateSequence(PSP.CurState, Weap.FindState("Select")));
		
		OfstAdd = false;
		
		Weap.BobStyle = MRIntW_BobStyle;
		Weap.BobRangeX = MRIntW_BobRangeX;
		Weap.BobRangeY = MRIntW_BobRangeY;
		
		if(MRIntW_VanillaFireBob)DoVanillaFiringBob();
		
		if(MRIntW_BaseOffset)DoBaseOffset();
		
		if(MRIntW_DamageShake)DoDamageShake();
		
		if(LowerGun || MRIntW_RunKey>0)DoGunLower();
		
		if(MRIntW_Bounce)DoBounce();
		
		if(MRIntW_WeaponSway)DoSway(MRIntW_WeaponSwayStyle);
	}
	
	Vector2 FireBob, OldFireBob;
	Double BobInter;
	Void DoVanillaFiringBob()
	{
		if(
			InStateSequence(PSP.CurState, Weap.FindState("Fire"))||
			InStateSequence(PSP.CurState, Weap.FindState("Select"))||
			InStateSequence(PSP.CurState, Weap.FindState("Deselect"))
		){
			PSP.X = FireBob.X;
			if(Owner.Player.FindPSprite(2) && Owner.Player.FindPSprite(2).bMirror)PSP.X = -FireBob.X;
			if(InStateSequence(PSP.CurState, Weap.FindState("Fire")))PSP.Y = 32+FireBob.Y;
			
			PSP.OldX = PSP.X;
			if(InStateSequence(PSP.CurState, Weap.FindState("Fire")))PSP.OldY = PSP.Y;
			
			OldFireBob = FireBob;
			BobInter = 1;
			
			OfstAdd = true;
		}
		else {
			FireBob = PlayerPawn(Owner).BobWeapon(2);
			if(BobInter>0 && OldFireBob.Length()>0){
				if(InStateSequence(PSP.CurState, Weap.FindState("Ready"))){
					PSP.X = -FireBob.X*BobInter;
					PSP.X += OldFireBob.X*BobInter;
					if(Owner.Player.FindPSprite(2) && Owner.Player.FindPSprite(2).bMirror){
						PSP.X = FireBob.X*BobInter;
						PSP.X -= OldFireBob.X*BobInter;
					}
					PSP.Y = -FireBob.Y*BobInter+32;
					PSP.Y += OldFireBob.Y*BobInter;
					
					if(BobInter==1){
						PSP.OldX = PSP.X;
						PSP.OldY = PSP.Y;
					}
					
					BobInter *= .6;
					if(BobInter<.1){
						OldFireBob = (0,0);
						BobInter = 0;
					}
					
					OfstAdd = true;
				}
				else OldFireBob = (0,0);
			}
			else BobInter = 0;
		}
	}
	
	Void DoBaseOffset()
	{
		if(OfstAdd){
			PSP.X += MRIntW_BaseOffsetX;
			PSP.OldX = PSP.X;
			if(Allowed){
				PSP.Y += MRIntW_BaseOffsetY;
				PSP.OldY = PSP.Y;
			}
		}
		else {
			PSP.X = MRIntW_BaseOffsetX;
			if(Allowed)PSP.Y = 32+MRIntW_BaseOffsetY;
			OfstAdd = true;
		}
	}
	
	int DamageShake, PlrLastHealth;
	Void DoDamageShake()
	{
		if(DamageShake>0){
			Double Shake = DamageShake;
			Shake *= .1;
			
			if(!OfstAdd){
				PSP.X = GetAge()%2==0?Shake:-Shake;
				if(Allowed)PSP.Y = 32+Shake*CFRandom(0, 1);
				OfstAdd = true;
			}
			else {
				PSP.X += GetAge()%2==0?Shake:-Shake;
				if(Allowed)PSP.Y += Shake*CFRandom(0, 1);
			}
			
			DamageShake -= 4;
			if(DamageShake<0)DamageShake = 0;
		}
		
		if(Owner.Health<PlrLastHealth){
			DamageShake = PlrLastHealth - Max(0, Owner.Health);
		}
		
		PlrLastHealth = Max(0, Owner.Health);
	}
	
	Bool LowerGun;
	Double RunKey;
	Void DoGunLower()
	{
		if(Allowed){
			Bool Invert = MRIntW_RunKey>1;
			Bool Pressing = (Owner.Player.Cmd.Buttons&BT_SPEED) || LowerGun;
			if(LowerGun && Owner.Player.Cmd.Buttons&BT_SPEED)Pressing = !Pressing;
			
			if(Pressing != Invert){
				if(RunKey<1)RunKey += Max(.05, (1-RunKey)*.1);
			}
			else {
				if(RunKey>.01)RunKey *= .8;
				else RunKey = 0;
			}
			
			if(!OfstAdd)PSP.Y = 32+RunKey*26;
			else {
				PSP.Y += RunKey*26;
				PSP.OldY = PSP.Y;
			}
			OfstAdd = true;
		}
		else RunKey = 0;
	}
	
	Double CurBounce, BounceStrength;
	Bool Bouncing, Landed;
	Void DoBounce()
	{
		Bool Clear = MRIntW_Bounce>1;//Weapon only goes down
		
		Bouncing = false;
		
		if(Owner.Pos.Z > Owner.FloorZ){
			BounceStrength = Owner.Vel.Z;//Move weapon based on vertical velocity (going down - move up, going up - move down)
			CurBounce += (Clear?Max(0, (abs(BounceStrength) + CurBounce))*.4 : (BounceStrength - CurBounce)*.5);
			if(Clear) CurBounce = Min(40, CurBounce);
			else CurBounce = Clamp(CurBounce, -abs(Weap.FloatSpeed*6.5), 20);
			Bouncing = true;
			Landed = true;
		}
		else if(abs(BounceStrength)>0){
			if(Clear && Landed)BounceStrength = -CurBounce;
			
			if(CurBounce<-BounceStrength)CurBounce -= BounceStrength*.5;
			
			else {
				BounceStrength *= .7;
				if(abs(BounceStrength)<.05)BounceStrength = 0;
				CurBounce = -BounceStrength;
			}
			
			Bouncing = true;
			
			if(Landed){//Camera shake on landing
				Landed = false;
				if(abs(CurBounce)>4 && MRIntW_ScreenShake>2)Owner.A_QuakeEx(1*Min(20, abs(CurBounce)),0,0, Clamp(abs(CurBounce)*2, 1, 20), 0, .5, "", QF_RELATIVE|QF_SCALEDOWN|QF_SCALEUP|QF_WAVE, 2,0,0, rollIntensity: .1*Min(30, abs(CurBounce)), rollwave: 2);
			}
		}
		
		if(Bouncing && Allowed){
			if(Clear){
				if(!OfstAdd)PSP.Y = 32 + CurBounce;
				else {
					PSP.Y += CurBounce;
					PSP.OldY = PSP.Y;
				}
				OfstAdd = true;
			}
			else {
				if(!OfstAdd)PSP.Y = 32 + CurBounce*.5;
				else {
					PSP.Y += CurBounce*.5;
					PSP.OldY = PSP.Y;
				}
				OfstAdd = true;
			}
		}
	}
	
	Vector2 CurSway, Sway;
	int GoingY;
	Float GoingX;
	Void DoSway(int Style)
	{
		Double Target;
		Switch(Style)
		{
			Case 0://Half Life 2
				Target = Sin(Owner.Pitch)*10;
				
				if(InStateSequence(PSP.CurState, weap.FindState("Fire")))Sway.X *= .8;
				
				Sway.Y *= .8;
				
				{
					Vector2 Add = (Owner.Player.Cmd.Yaw, Owner.Player.Cmd.Pitch)*.0025;
					if(abs(Owner.Pitch)>89)Add.Y -= Owner.Player.Cmd.Pitch*.0025;
					
					if((GoingY>0 && Add.X<0)||
						(GoingY<0 && Add.X>0))GoingX = 0;
					else GoingX += .15;
					
					GoingX = Min(1-Max(0, abs(Sway.X)-10)/31, GoingX);
										
					if(Add.X>0)GoingY = 1;
					else GoingY = -1;
										
					Sway += Add*GoingX;
				}
				
				Sway.X = Clamp(Sway.X, -40, 40);
				Sway.Y = Clamp(Sway.Y, -50, 50);
				
				CurSway.Y += (Target - CurSway.Y)*.25;
								
				if(OfstAdd){
					PSP.X += (Sway.X-PSP.X)*.5;
					PSP.OldX = PSP.X;
					if(Allowed){
						PSP.Y += ((CurSway.Y + Sway.Y)-PSP.Y+32)*.5;
						PSP.OldY = PSP.Y = Max(32-abs(Weap.FloatSpeed*6.5), PSP.Y);
					}
				}
				else {
					PSP.X = PSP.X+(Sway.X-PSP.X)*.5;
					if(Allowed)PSP.Y = Max(32-abs(Weap.FloatSpeed*6.5), 32 + CurSway.Y + Sway.Y);
					OfstAdd = true;
				}
				
				if(!Allowed)CurSway.Y = 0;
				
				Break;
			Case 1://Battlefront 2015
				
				Float Mult = 1;
				
				Switch(Owner.Player.ReadyWeapon.GetClassName()){
					Case 'MRIntWeaps_Fist':
						Mult = .3;
						Break;
					Case 'MRIntWeaps_Pistol':
						Mult = -.5;
						Break;
					Case 'MRIntWeaps_Shotgun':
					Case 'MRIntWeaps_PlasmaRifle':
						Mult = .8;
						Break;
					Case 'MRIntWeaps_SuperShotgun':
						Mult = 1;
						Break;
					Case 'MRIntWeaps_Chaingun':
						Mult = .4;
						Break;
					Case 'MRIntWeaps_RocketLauncher':
						Mult = .5;
						Break;
					Case 'MRIntWeaps_BFG9000':
						Mult = .1;
						Break;
				}
				
				Target = -Sin(Owner.Pitch)*20;

				Sway.Y += (Target - CurSway.Y)*.1;
				Sway.Y = Clamp(Sway.Y, -5, 5);
				
				if((Sway.Y<0 && CurSway.Y<Target)||
					(Sway.Y>0 && CurSway.Y>Target))Sway.Y *= .2*abs(Mult);
				
				CurSway.Y += Sway.Y;
				
				Target = Owner.Player.Cmd.Yaw*.01*Mult;
				
				Float Add = (Target - CurSway.X);
				
				if(Target==0){
					if(GoingX<1)GoingX += .1*abs(Mult*.5);
					Add *= GoingX*.25;
				}
				else {
					Add *= .1;
					GoingX = 0;
				}
				Sway.X += Add;
				
				if((Sway.X<0 && CurSway.X<Target)||
					(Sway.X>0 && CurSway.X>Target))Sway.X *= .05;
				
				CurSway.X += Sway.X;

				
				if(OfstAdd){
					PSP.X += (CurSway.X - PSP.X)*.5;
					PSP.OldX = PSP.X;
					if(Allowed){
						PSP.Y += (CurSway.Y - PSP.Y +32)*.5;
						PSP.OldY = PSP.Y = Max(32-abs(Weap.FloatSpeed*6.5), PSP.Y);
					}
				}
				else {
					PSP.OldX = PSP.X = PSP.X+(CurSway.X - PSP.X)*.5;
					if(Allowed)PSP.Y = Max(32-abs(Weap.FloatSpeed*6.5), 32 + CurSway.Y);
					OfstAdd = true;
				}
				if(!Allowed)CurSway.Y = 0;
				
				Break;
		}
	}
	
	
	
	
	Clearscope Static Double GetBobZ(Weapon Weap, Double Center = .5)
	{
		PlayerPawn Plr = PlayerPawn(Weap.Owner);
		
		Double Range = MRIntW_BobRangeZ;
		int bobstyle = Weap.BobStyle;
		double angle = (Weap.BobSpeed*128 * Plr.player.GetWBobSpeed() * 35 /	TICRATE*(Level.maptime)) * (360. / 8192.);

		// [RH] Smooth transitions between bobbing and not-bobbing frames.
		// This also fixes the bug where you can "stick" a weapon off-center by
		// shooting it when it's at the peak of its swing.
		Double R;

		// The weapon bobbing intensity while firing can be adjusted by the player.
		double BobIntensity = ((Plr.player.WeaponState & WF_WEAPONBOBBING) ? 1. : Plr.player.GetWBobFire())*.01;

		if (Plr.curbob != 0)
		{
			double bobVal = Plr.player.bob;
			
			bobVal = Plr.prevBob;
			//[SP] Added in decorate player.viewbob checks
			double bob = (bobVal * BobIntensity * Range * Plr.ViewBob);
			switch (bobstyle)
			{
			case Bob_Normal:
				R = Bob * (Center - abs(Sin(angle)));
				break;

			case Bob_Inverse:
				R = bob * (Center - abs(sin(angle)));
				break;

			case Bob_Alpha:
				R = bob * (Center - abs(sin(angle)));
				break;

			case Bob_InverseAlpha:
				R = bob * (Center - abs(sin(angle)));
				break;

			case Bob_Smooth:
				R = 0.5f * (bob * (Center - (cos(angle * 2))));
				break;

			case Bob_InverseSmooth:
				R = 0.5f * (bob * (Center + (cos(angle * 2))));
			}
		}
		else
		{
			r = 0;
		}
		
		Return R;
	}
}