Class MRIntWeaps_MainMenu: MRIntWeaps_ListMenuMain
{
	Override void Init(Menu parent, ListMenuDescriptor desc)
	{
		Super.Init(parent, desc);
		
		FPSScale = MRIntW_LastFPS;
		
		if(!MRIntW_SmoothUiLogo || !Interpolate)Return;
		
		For(int i=0;i<mDesc.mItems.Size();i++)
		{
			Let Item = ListMenuItemStaticPatch(mDesc.mItems[i]);
			if(!Item || Texman.GetName(Item.mTexture) != "M_DOOM")Continue;
			
			mDesc.mItems[i] = New('ListMenuItemMR_Doom');
			ListMenuItemMR_Doom(mDesc.mItems[i]).Init(mDesc, 94, 2, Texman.CheckForTexture("M_DOOM"));
			ListMenuItemMR_Doom(mDesc.mItems[i]).FPSScale = FPSScale;
		}
	}
		
	Override Void OnDestroy()
	{
		Super.OnDestroy();
		
		CVar.FindCVar("MRIntW_LastFPS").SetFloat(FPSScale);
	}
}

Class ListMenuItemMR_Doom: ListMenuItemStaticPatch
{
	Bool Tick, Dead;
	int Stayt, IntroVar;
	Double Scale, Scale2, SubVel, SubAccel, SubRot;
	Vector2 M_DoomPos, SubPos;
	Array<MRIntWeaps_MainMenuActor> Actors;
	MRIntWeaps_MainMenuHand Hand;
	Double FPSScale;
	int Frames, Ticks;
	
	void Init(ListMenuDescriptor desc, double x, double y, TextureID patch, bool centered = false, String substitute = "")
	{
		Super.Init(desc, x, y, patch);
		
		IntroVar = CRandom(0, 2);
		SubRot = 25;
		
		int w = desc ? desc.DisplayWidth() : ListMenuDescriptor.CleanScale;
		int h = desc ? desc.DisplayHeight() : -1;
		
		Double Width = w;
		Double Height = h;
		Double DefScale = 1;
		if(w == ListMenuDescriptor.CleanScale){
			Width = Screen.GetWidth();
			Height = Screen.GetHeight();
			DefScale = 3;
		}

		Switch(IntroVar){
			Case 0:
				Scale = 1;
				Break;
			Case 1:
				Scale = DefScale;
				M_DoomPos = (Width*.7, 0);
				Break;
			Case 2:
				Scale = DefScale;
				M_DoomPos = (0, -Height*.5);
				Break;
		}
		
		Tick = true;
		
		Dead = Players[ConsolePlayer].mo && Players[ConsolePlayer].mo.Health<1;
		
		if(Dead){
			CVar.FindCVar("MRIntW_MenuState").SetInt(2);
			Scale = DefScale;
			M_DoomPos = (0, Height*CFRandom(1.05, 1.1));
			SubPos = (0,0);
			Scale2 = 1;
			IntroVar = 0;
			Stayt = 36;
		}
		
		
		else if(MRIntW_MenuState>1)CVar.FindCVar("MRIntW_MenuState").SetInt(0);
		
		if(Hand)Hand.Destroy();
	}
	
	Override Void Ticker()
	{
		Super.Ticker();
		
		if(Tick)Stayt++;
		Tick = false;
		
		Ticks++;
		if(Ticks%35==0){
			Ticks = 0;
			FPSScale = Frames;
			FPSScale /= 60;
			if(FPSScale<2)FPSScale = 1;
			Frames = 0;
		}
	}
	
	override void Draw(bool selected, ListMenuDescriptor desc)
	{
		Frames++;
		if (!mTexture.Exists())
		{
			return;
		}
		
		int w = desc ? desc.DisplayWidth() : ListMenuDescriptor.CleanScale;
		int h = desc ? desc.DisplayHeight() : -1;
		Double DefScale = 1;
		Double Width = w;
		Double Height = h;
		if(w == ListMenuDescriptor.CleanScale){
			Width = Screen.GetWidth();
			Height = Screen.GetHeight();
			DefScale = 3;
		}
		
		Vector2 vec = TexMan.GetScaledSize(mTexture);
		Vector2 MOfst = Texman.GetScaledOffset(mTexture);
		
		if(Stayt<2+18){
			Switch(Stayt){
				Default:
					Tick = True;
					Break;
				Case 2:
					Tick = false;
					if(M_DoomPos.Length()<40)Scale = (DefScale*1.4)+(Scale-(DefScale*1.4))*Min(.99, .5*((FPSScale-1)*.1+1));
					M_DoomPos *= Min(.99, .6*((FPSScale-1)*.1+1));
					if(abs(Scale-(DefScale*1.4))<.2 && M_DoomPos.Length()<3)Stayt++;
					Break;
				Case 3:
					Tick = false;
					M_DoomPos = (0, 0);
					Scale = DefScale+(Scale-DefScale)*Min(.99, .7*((FPSScale-1)*.1+1));
					if(abs(Scale-DefScale)<.01){
						IntroVar = CRandom(0, 1);
						Stayt++;
					}
					Break;
			}
		}
		if(Dead){
			if(M_DoomPos.Y<Height*.01)M_DoomPos.Y *= Min(.99, .9*((FPSScale-1)*.1+1));
			else M_DoomPos.Y -= Min(M_DoomPos.Y, Height*.001/FPSScale);
			
			if(M_DoomPos.Y<.1)Dead = false;
		}
		//M_Doom
		if(w == ListMenuDescriptor.CleanScale)Screen.DrawTexture(mTexture, true, Width*.5 -vec.X*Scale*.5 + M_DoomPos.X + MOfst.X*Scale, Height*.5 -vec.Y*Scale*.5 - vec.Y*DefScale*1.2 + M_DoomPos.Y + MOfst.Y*Scale
			,DTA_DestWidthF, vec.X*Scale
			,DTA_DestHeightF, vec.Y*Scale
			,DTA_FullscreenScale, FSMode_ScaleToFit43
		);
		else Screen.DrawTexture(mTexture, true, Width*.5 -vec.X*Scale*.5 + M_DoomPos.X + MOfst.X*Scale, Height*.5 -vec.Y*Scale*.5 - 70 + M_DoomPos.Y + MOfst.Y*Scale
			,DTA_DestWidthF, vec.X*Scale
			,DTA_DestHeightF, vec.Y*Scale
			,DTA_VirtualWidth, w, DTA_VirtualHeight, h, DTA_FullscreenScale, FSMode_ScaleToFit43
		);
		
		if(Stayt>=2+18 || MRIntW_MenuState>1){
			TextureId SubTex = Texman.CheckForTexture("MR_DOOM");
			
			Vector2 SubSize = Texman.GetScaledSize(SubTex);
			
			Bool SubFlipX, SubFlipY;
			
			
			Switch(MRIntW_MenuState){
				Case 0:
				{
					if(Stayt<2+21){
						Switch(Stayt){
							Default:
								Tick = true;
								Break;
							Case 2+19:
								Tick = false;
								Scale2 = 2;
								Stayt++;
								Break;
							Case 2+20:
								Scale2 = 1+(Scale2-1)*Min(.99, .4*((FPSScale-1)*.1+1));
								if(abs(Scale2-1)<.01)Stayt++;
								Break;
						}
					}
					else {
						Tick = true;
						if(IntroVar){
							if(Stayt>35*10){
								if(Stayt<35*12){
									Float Add = (-90 - SubRot);//Speed is based on how far the current position is from the target position
									
									if(SubAccel<1)SubAccel += .1/FPSScale;//Increasing speed
									Add *= SubAccel*.1;
									SubVel += Add/FPSScale;
									
									if((SubVel<0 && SubRot+SubVel<=-90)||
										(SubVel>0 && SubRot+SubVel>=-90)){//Wobbling
											SubVel *= .8;
									}
									
									SubRot += SubVel;
								}
								else {
									SubRot -= SubPos.Y*.01/FPSScale;
									SubPos.Y += (1+SubPos.Y*.5)/FPSScale;
								}
							}
							else {
								SubAccel = SubVel = 0;
								SubRot = 25;
							}
						}
						else {
							if(Stayt>35*10){
								if(Stayt<35*11)SubRot = 25+CFRandom(-.01, .01)*(Stayt-60*10);
								else {
									if(Stayt==60*12)SubRot -= 20/FPSScale;
									SubRot -= SubPos.Y*.1/FPSScale;
									SubPos.Y += (1+SubPos.Y*.5)/FPSScale;
								}
							}
						}
						
						if(SubPos.Y>Screen.GetHeight()*.8){
							CVar.FindCVar("MRIntW_MenuState").SetInt(1);
							Stayt = 3+19;
							IntroVar = CRandom(0, 1);
						}
					}
				}
				Break;
				Case 1:
				{
					if(!IntroVar){
						if(Stayt<36)Switch(Stayt){
							Default:
								Tick = true;
								Break;
							Case 35:
								Tick = false;
								if(!Hand){
									Hand = New('MRIntWeaps_MainMenuHand');
									Hand.Pos = (0, -Height*.8);
									SubRot = 25;
									Scale2 = 1;
									Hand.Height = Height;
									Hand.PartOf = Self;
									SubPos = (0, Hand.Pos.Y);
								}
								
								else {
									Hand.Tick();
									
									if(!Hand){
										SubPos *= 0;
										Stayt++;
										CVar.FindCVar("MRIntW_MenuState").SetInt(2);
									}
									else if(Hand.Stayt<1)SubPos.Y = Hand.Pos.Y;
								}
								Break;
						}
					}
					else {
						Float Targ;
						Switch(Stayt){
							Default:
								if(Stayt>48){
									SubFlipX = true;
									SubFlipY = true;
								}
								Tick = true;
								Break;
							Case 35:
								SubRot = 90 - 20;
								SubPos = (Width*CFRandom(-.3, .3), -(Height*.5 - vec.Y*DefScale*.8 +SubSize.Y*.5) + Height + SubSize.X*3);
								Stayt++;
								Break;
							Case 36:
								Tick = false;
								Targ = -(Height*.5 - vec.Y*DefScale*.8 +SubSize.Y*.5) + Height;
								SubPos.Y = (Targ)+(SubPos.Y-Targ)*Min(.99, .6*((FPSScale-1)*.1+1));
								if(abs(SubPos.Y-Targ)<1)Stayt++;
								Break;
							Case 37:
								Targ = -(Height*.5 - vec.Y*DefScale*.8 +SubSize.Y*.5) + Height + SubSize.X*.1;
								SubPos.Y = (Targ)+(SubPos.Y-Targ)*Min(.99, .9*((FPSScale-1)*.1+1));
								if(abs(SubPos.Y-Targ)<.1)Stayt++;
								Break;
							Case 47:
								Targ = -(Height*.5 - vec.Y*DefScale*.8 +SubSize.Y*.5) + Height + (SubSize.X*4.4*Height/1080);
								SubPos.Y = (Targ)+(SubPos.Y-Targ)*Min(.99, .7*((FPSScale-1)*.1+1));
								if(abs(SubPos.Y-Targ)<.1){
									Stayt++;
									if(CRandom(0, 3)==0){
										Stayt = 25;
										IntroVar = 0;
										SubPos.X = 0;
									}
									else SubPos.X = Width*CFRandom(-.4, .4);
								}
								Break;
							Case 48:
								SubFlipX = true;
								SubRot = 90 + 20;
								Targ = -(Height*.5 - vec.Y*DefScale*.8 +SubSize.Y*.5) + Height + SubSize.X*.1;
								SubPos.Y = (Targ)+(SubPos.Y-Targ)*Min(.99, .9*((FPSScale-1)*.1+1));
								if(abs(SubPos.Y-Targ)<3)Stayt++;
								Break;
							Case 60:
								SubFlipX = true;
								Tick = false;
								Targ = -(Height*.5 - vec.Y*DefScale*.8 +SubSize.Y*.5) + Height + (SubSize.X*4.4*Height/1080);
								SubPos.Y = (Targ)+(SubPos.Y-Targ)*Min(.99, .7*((FPSScale-1)*.1+1));
								if(abs(SubPos.Y-Targ)<.1){
									Stayt = 25;
									SubPos.X = 0;
									SubPos.Y = -(Height*.5 - vec.Y*DefScale*.8 +SubSize.Y*.5) + Height + (SubSize.X*4.4*Height/1080);
									IntroVar = 0;
								}
								Break;
								
						}
					}
				}
				Break;
				Case 2:
				{
					Scale2 = 1;
					SubRot = 25;
					SubPos = (0,0);
					if(Stayt>22)Tick = false;
				}
				Break;
			}
			
			if(w == ListMenuDescriptor.CleanScale)Screen.DrawTexture(SubTex, true, Width*.5 + Vec.X -SubSize.X*.5*Scale2 + SubPos.X + M_DoomPos.X, Height*.5 - vec.Y*DefScale*.8 +SubSize.Y*.5*Scale2 + SubPos.Y + M_DoomPos.Y
				,DTA_DestWidthF, SubSize.X*Scale*.85*Scale2
				,DTA_DestHeightF, SubSize.Y*Scale*.85*Scale2
				,DTA_Rotate, SubRot
				,DTA_FlipY, SubFlipX
			);
			else Screen.DrawTexture(SubTex, true, Width*.5 + Vec.X*Scale*.5 -SubSize.X*.5*Scale2 + SubPos.X + M_DoomPos.X, Height*.5 - Vec.Y*DefScale*.8 +SubSize.Y*.5*Scale2 + SubPos.Y + M_DoomPos.Y
				,DTA_DestWidthF, SubSize.X*Scale*.85*Scale2
				,DTA_DestHeightF, SubSize.Y*Scale*.85*Scale2
				,DTA_Rotate, SubRot
				,DTA_FlipY, SubFlipX
				,DTA_VirtualWidth, w, DTA_VirtualHeight, h, DTA_FullscreenScale, FSMode_ScaleToFit43
			);
			
			if(Hand){
				TextureId Sprt = (Hand.Stayt<1?Texman.CheckForTexture("MRD1D0"):Texman.CheckForTexture("MRD1C0"));
				Vector2 HandSize = Texman.GetScaledSize(Sprt);
				
				if(w == ListMenuDescriptor.CleanScale)Screen.DrawTexture(Sprt, true, Width*.5 + Vec.X + Hand.Pos.X - 100*4, Height*.5 - vec.Y*DefScale*.8 + Hand.Pos.Y - 275*4
					,DTA_FlipY, true
					,DTA_DestWidthF, HandSize.X*4
					,DTA_DestHeightF, HandSize.Y*4
					,DTA_TranslationIndex, Hand.Trans
				);
				else Screen.DrawTexture(Sprt, true, width*.5-HandSize.X +40 + Vec.X*Scale*.5, height*.5-HandSize.Y -vec.Y*DefScale*.8 + Hand.Pos.Y -122
					,DTA_FlipY, true
					,DTA_DestWidthF, HandSize.X
					,DTA_DestHeightF, HandSize.Y
					,DTA_TranslationIndex, Hand.Trans
					,DTA_VirtualWidth, W, DTA_VirtualHeight, H, DTA_FullscreenScale, FSMode_ScaleToFit43
				);
			}
		}
	}
	
	Override Void OnDestroy()
	{
		Super.OnDestroy();
		if(Hand)Hand.Destroy();
	}
}

Class MRIntWeaps_MainMenuActor: Object Ui
{
	TextureId Sprt;
	int Stayt;
	Bool FlipX, FlipY;
	Double OldRot, Rot;
	Vector2 Prev, Pos, Vel, OldScale, Scale;
	Virtual Void Tick(){}
}

Class MRIntWeaps_MainMenuHand: Object Ui
{
	Static Const String Translations[] = {
		"MRIntWGlovesClassic", "MRIntWGlovesBlack", "MRIntWGlovesBrown", "MRIntWGlovesGreen",
		"MRIntWGlovesRed", "MRIntWGlovesGrey", "MRIntWGlovesBlue"
	};
	
	ListMenuItemMR_Doom PartOf;
	Vector2 Pos;
	int Stayt, Trans;
	Double YSpeed, Height;
	
	Void Tick()
	{
		if(Stayt<1){
			if(Pos.Y<=-Height*.8){
				if(CRandom(-Translations.Size(), -5)==-5 && Players[ConsolePlayer].mo && MRIntWeaps_Fist(Players[ConsolePlayer].mo.FindInventory("MRIntWeaps_Fist"))){
					Trans = MRIntWeaps_Fist(Players[ConsolePlayer].mo.FindInventory("MRIntWeaps_Fist")).GlovesTrans;
				}
				else Trans = Translation.GetId(Translations[CRandom(0, Translations.Size()-1)]);
				
				YSpeed = CFRandom(.7, .93);
			}
			Pos.Y *= Min(.99, YSpeed*((PartOf.FPSScale-1)*.08+1));
			if(abs(Pos.Y)<1)Stayt++;
		}
		else if(Stayt<20){
			Stayt++;
		}
		else {
			Pos.Y -= (abs(Pos.Y)*CFRandom(.4, .6)+1)/PartOf.FPSScale;
			if(Pos.Y<-Height*.8){
				Destroy();
			}
		}
	}
}


class OptionMenuItemMRIntWeaps_ModSubMenu: OptionMenuItemSubmenu
{
	Name mType, ActualType;
	int Weaps, LastWeap, LastTick;
	Bool WasSelected, Selected, PlayingAnim;
	Array<Double> ChPs, ChPYs, ChVs, ChVYs;
	Array<String> Chars;
	Double FPSScale;
	int Frames, Ticks;
	Vector2 Pos, Vel, Accel, Targ;
		
	OptionMenuItemSubmenu Init(String label, Name command, String Type)
	{
		Super.init(label, command);
		ActualType = mType = Type.MakeLower();
		
		Weaps = 5;
		if(Wads.CheckNumForName("SGN2A0", wads.ns_sprites)<0)Weaps--;
		LastWeap = CRandom(1, Weaps);
		
		FPSScale = MRIntW_LastFPS;
		return self;
	}
	
	int MRDrawLabel(int indent, int y, int color, bool grayed = false)
	{
		String label = Stringtable.Localize(mLabel);
		
		int x;
		int w = Menu.OptionWidth(label) * CleanXfac_1;
		if (!mCentered) x = indent - w;
		else x = (screen.GetWidth() - w) / 2;
		
		if(!PlayingAnim){
			Menu.DrawOptionText(x, y, color, label, grayed);
			Return X;
		}
		
		Switch(mType){
			Case 'jump':
			{
				if(Chars.Size()<1){
					For(int i=0;i<label.Length();){
						int Chr, Next;
						[Chr, Next] = label.GetNextCodePoint(i);
						
						Chars.Push(String.Format("%c", Chr));
						ChVs.Push(CFRandom(0, 2)/((FPSScale-1)*.2+1));
						ChPs.Push(0);
						
						i = Next;
					}
				}
				int overlay = grayed? Color(96,48,0,0) : 0;
				
				int Pos = 0;
				
				Font Fnt = Menu.OptionFont();
				
				Bool AllLanded = true;
				
				For(int i=0;i<Chars.Size();i++){
					if(abs(ChVs[i])>0){
						ChVs[i] -= .1/FPSScale;
						ChPs[i] += ChVs[i];
						AllLanded = false;
					}
					if(ChPs[i]<=0){
						ChPs[i] = ChVs[i] = 0;
					}
					
					screen.DrawText(Fnt, Color, x+Pos, y-ChPs[i], Chars[i], DTA_CleanNoMove_1, true, DTA_ColorOverlay, overlay);
					
					Pos += Fnt.StringWidth(Chars[i]) * CleanXfac_1;
				}
				
				PlayingAnim = !AllLanded;
			}Break;
			Case 'particles':
			{
				if(Chars.Size()<1){
					For(float i=0;i<label.Length();){
						int Chr, Next;
						[Chr, Next] = label.GetNextCodePoint(i);
						
						Chars.Push(String.Format("%c", Chr));
						ChVs.Push((((i-label.Length()*.5)/label.Length()*.5)*20)/FPSScale);
						ChVYs.Push(CFRandom(20, 25));
						ChPs.Push(0);
						ChPYs.Push(0);
						
						i = Next;
					}
				}
				int overlay = grayed? Color(96,48,0,0) : 0;
				
				int Pos = 0;
				
				Font Fnt = Menu.OptionFont();
				
				Bool AllLanded = true;
				
				For(int i=0;i<Chars.Size();i++){
					
					if(Accel.X==0){
						if(ChPYs[i]/FPSScale<-Screen.GetHeight())Continue;
						
						ChVYs[i] -= 1.3/FPSScale;
						ChPs[i] += ChVs[i];
						ChPYs[i] += ChVYs[i];
						AllLanded = false;
					}
					else {
						if(ChPYs[i]>-.01){
							ChPYs[i] == 0;
						}
						else {
							ChPYs[i] *= CFRandom(.65, .75)*((FPSScale-1)*.1+1);
							ChPs[i] *= .7*((FPSScale-1)*.1+1);
							AllLanded = false;
						}
					}
					
					screen.DrawText(Fnt, Color, x+Pos+ChPs[i], y-ChPYs[i]/FPSScale, Chars[i], DTA_CleanNoMove_1, true, DTA_ColorOverlay, overlay);
					
					Pos += Fnt.StringWidth(Chars[i]) * CleanXfac_1;
				}
				
				if(Accel.X==0 && AllLanded)Accel.X = 1;
				else PlayingAnim = !AllLanded;
			}Break;
			Case 'movex':
				if(Targ.Length()==0 && Pos.Length()==0 && Vel.Length()==0){
					Targ.X = CRandomPick(-1, 1);
					Targ.X = Targ.X*CFRandom(2, 8);
				}
			Case 'move':
			{
				if(Targ.Length()==0 && Pos.Length()==0 && Vel.Length()==0){
					Targ = (CRandomPick(-1, 1), CRandomPick(-1, 1));
					Targ = (Targ.X*CFRandom(2, 8), Targ.Y*CFRandom(2, 8));
				}
				
				Vector2 Add = Targ - Pos;//Speed is based on how far the current position is from the target position
									
				if(Accel.X<1)Accel.X += .1/FPSScale;//Increasing speed
				if(Accel.Y<1)Accel.Y += .1/FPSScale;//Increasing speed
				Add.X *= Accel.X*.1;
				Add.Y *= Accel.Y*.1;
				Vel.X += Add.X/FPSScale;
				Vel.Y += Add.Y/FPSScale;
				
				Bool Targ0 = true;
				if((Vel.X<0 && Pos.X+Vel.X<=Targ.X)||
					(Vel.X>0 && Pos.X+Vel.X>=Targ.X)){//Wobbling
						Vel.X *= .8;
				}
				else Targ0 = false;
				if((Vel.Y<0 && Pos.Y+Vel.Y<=Targ.Y)||
					(Vel.Y>0 && Pos.Y+Vel.Y>=Targ.Y)){//Wobbling
						Vel.Y *= .8;
				}
				else if(Vel.Y != 0)Targ0 = false;
				
				if(Targ0)Targ *= 0;
				
				Pos += Vel;
				
				if(Targ.Length()==0 && Pos.Length()<.01)PlayingAnim = false;
				
				int overlay = grayed? Color(96,48,0,0) : 0;
				screen.DrawText(Menu.OptionFont(), Color, x+Pos.X, y+Pos.Y, label, DTA_CleanNoMove_1, true, DTA_ColorOverlay, overlay);
			}Break;
			Case 'weapons':
			{
				if(ChPs.Size()<3 && ((gametic%20==0 && LastTick != Ticks) || ChPs.Size()<1) && Selected){
					LastTick = Ticks;
					ChPs.Push(0);
					Chars.Push("MR_WMA"..LastWeap);
					if(LastWeap<Weaps)LastWeap++;
					else LastWeap = 1;
				}
				
				Bool GotOne = false;
				For(int i=0;i<ChPs.Size();i++){
					Double Pos;
					Double Angle;
					
					ChPs[i]++;
					if(ChPs[i]>60*7*FPSScale){
						if(!Selected)Continue;
						
						ChPs[i] = 0;
						Chars[i] = "MR_WMA"..LastWeap;
						if(LastWeap<Weaps)LastWeap++;
						else LastWeap = 1;
					}
					else {
						if(ChPs[i]>60*6.8*FPSScale){
							if(i<2)Pos = (1-(ChPs[i]-60*6.8*FPSScale)/(60*.2*FPSScale))*90;
							if(i!=1)Angle = (1-(ChPs[i]-60*6.8*FPSScale)/(60*.2*FPSScale))*35;
						}
						else if(ChPs[i]>20*FPSScale){
							if(i<2)Pos = 90;
							if(i!=1) Angle = 35;
						}
						else {
							if(i<2)Pos = (ChPs[i]/(20*FPSScale))*90;
							if(i!=1) Angle = (ChPs[i]/(20*FPSScale))*35;
						}
						if(i>1)Angle *= -1;
					}
					
					GotOne = true;
					
					Screen.DrawTexture(Texman.CheckForTexture(Chars[i]), true, i>0?(x-Pos*Cos(Angle)+85):x+85, y+Pos*.3*Sin(Angle), DTA_CleanNoMove_1, true, DTA_ROTATE, Angle);
				}
				
				if(!GotOne){
					ChPs.Clear();
					Chars.Clear();
					PlayingAnim = false;
				}
				
				Menu.DrawOptionText(x, y, color, label, grayed);
			}Break;
			Case 'sound':
			{
				if(Pos.Y == 0 && Vel.Y == 0)Vel.Y = CFRandom(3, 4)/((FPSScale-1)*.2+1);
				
				Pos.Y += Vel.Y;
				Vel.Y -= .6/FPSScale;
				
				if(Pos.Y<=0){
					PlayingAnim = false;
					Vel.Y = Pos.Y = 0;
				}
				
				int overlay = grayed? Color(96,48,0,0) : 0;
				screen.DrawText(Menu.OptionFont(), Color, x, y-Pos.Y, label, DTA_CleanNoMove_1, true, DTA_ColorOverlay, overlay);
			}Break;
		}

		return x;
	}
	
	Override Void Ticker()
	{
		Super.Ticker();
		
		if(WasSelected != Selected && Selected && !PlayingAnim){
			if(!MRIntW_SmoothUiOptions)Return;
			Chars.Clear();
			ChVs.Clear();
			ChVYs.Clear();
			ChPs.Clear();
			ChPYs.Clear();
			Targ = Accel = Vel = Pos *= 0;
			if(mType=='sound')S_StartSound(CRandomPick(CRandom(1, 23), CRandom(225, 639)), CHAN_AUTO, CHANF_UI, .5);
			if(ActualType=='random'){
				Switch(CRandom(0, 2)){
					Case 0:mType = 'jump';Break;
					Case 1:mType = 'particles';Break;
					Case 2:mType = 'move';Break;
				}
			}
			PlayingAnim = true;
		}
		
		else if(WasSelected != Selected && !Selected && mType=='weapons'){
			For(int i=0;i<ChPs.Size();i++){
				if(ChPs[i]>60*6.8*FPSScale)Continue;
				if(ChPs[i]<20*FPSScale){
					ChPs[i] = 60*6.8*FPSScale+(20*FPSScale-ChPs[i])*.5;
				}
				else ChPs[i] += Min(60*6.81*FPSScale-ChPs[i], 60*5.5*FPSScale);
			}
		}
		
		WasSelected = Selected;
		
		if(Ticks%35==0){
			Ticks = 0;
			FPSScale = Frames;
			FPSScale /= 60;
			if(FPSScale<2)FPSScale = 1;
			Frames = 0;
		}
		Ticks++;
		LastTick = -1;
	}
	
	override int Draw(OptionMenuDescriptor desc, int y, int indent, bool selected)
	{
		Frames++;
		Self.Selected = Selected;
		
		int x = MRDrawLabel(indent, y, selected? OptionMenuSettings.mFontColorSelection : OptionMenuSettings.mFontColorMore);
		
		if (mCentered)
		{
			return x - 16*CleanXfac_1;
		}
		return indent;
	}
}