/*
	Settings pressets menu
*/

Class MRIntWeaps_PressetsMenu: OptionMenu
{
	Static Const String CVarsId[] = {//Syntax: "CVarname CVarIndex" (to prevent future updates from breaking pressets)
		"MRIntW_Casings 0", "MRIntW_CasingsRandom 1", "MRIntW_CasingsAmount 2", "MRIntW_CasingsVolume 3", "MRIntW_CasingsLowRes 4",
		"MRIntW_CasingsClusteringReduce 5", "MRIntW_Smoke 6", "MRIntW_FlowingSmoke 7", "MRIntW_FlowingSmokeLength 8", "MRIntW_FlowingSmokeAlpha 9",
		"MRIntW_FlowingSmokeMaxTime 10", "MRIntW_FlowingSmokePrecision 11", "MRIntW_BobStyle 12", "MRIntW_BobRangeX 13", 
		"MRIntW_BobRangeY 14", "MRIntW_BobRangeZ 15", "MRIntW_VanillaFireBob 16", "MRIntW_Bounce 17", "MRIntW_DamageShake 18", "MRIntW_IdleAnims 19", 
		"MRIntW_ReloadAnims 82", "MRIntW_Recoil 20", "MRIntW_RecoilAmount 21", "MRIntW_RecoilRecover 22", "MRIntW_ScreenShake 68", "MRIntW_ScreenShakeAmount 69",
		"MRIntW_Lighting 23", "MRIntW_InstantFire 24", "MRIntW_FastPistol 25", "MRIntW_BetterAlert 26", "MRIntW_GlovesColor 27", 
		"MRIntW_GlovesColorShade 28", "MRIntW_GlovesColorLight 29", "MRIntW_GlovesColorTemp 30", "MRIntW_Epilepsy 31", 
		"MRIntW_NoMuzzleFlash 32", "MRIntW_FlashFlare 33", "MRIntW_ShotgunsRecoil 34", "MRIntW_BareHands 35", "MRIntW_GloveStrip 36", 
		"MRIntW_BersShake 37", "MRIntW_LowHealthShake 38", "MRIntW_RightPunch 39", "MRIntW_SecondFist 40", "MRIntW_FinishPunch 41", "MRIntW_MissPunch 91",
		"MRIntW_FinishPunchChance 42", "MRIntW_SurfacePunchRecoil 43", "MRIntW_PunchingFist 44", "MRIntW_ChainsawStart 45", "MRIntW_ChainsawCutting 46", 
		"MRIntW_ChainsawCuttingWall 47", "MRIntW_ChainsawSmoke 48", "MRIntW_LHand 49", "MRIntW_PistolSHand 67", "MRIntW_Rifle 50", "MRIntW_ShotgunSmoke 51",
		"MRIntW_ShotgunSparks 52", "MRIntW_ShotgunPumpAngle 53", "MRIntW_ShotgunPumpRandom 54", "MRIntW_ShotgunPumpRandRotation 55",
		"MRIntW_SSGSmoke 56", "MRIntW_SSGSparks 57", "MRIntW_ChaingunFixed 58", "MRIntW_ChaingunCounterClock 59", "MRIntW_ChaingunSpeed 60",
		"MRIntW_ChaingunStopTime 61", "MRIntW_ChaingunMaxSmokes 62", "MRIntW_RocketSmoke 63", "MRIntW_PlasmaParticles 64", "MRIntW_BFGParticles 65",
		"wbobspeed 66", "wbobfire 99", "MRIntW_PlayerParticles 70", "MRIntW_PlayerWhichParticles 71", "MRIntW_PlayerParticlesAmount 72", "MRIntW_MonsterParticles 100",
		"MRIntW_MonsterWhichParticles 73", "MRIntW_MonsterWhichParticles2 74", "MRIntW_MonsterParticlesAmount 75", "MRIntW_MonsterParticleCustom 88", 
		"MRIntW_DecorationParticles 76", "MRIntW_DecorationWhichParticles 77", "MRIntW_DecorationParticlesAmount 78", "MRIntW_TeleportParticles 79", 
		"MRIntW_TeleportParticlesStyle 80", "MRIntW_TeleportParticlesStyleMonsters 81", "MRIntW_AltLightnings 83", "MRIntW_ChainsawBlood 84", "MRIntW_ChainsawBloodLife 85", 
		"MRIntW_ChainsawVolume 86", "MRIntW_ChainsawRandomPitch 87", "MRIntW_ParticleFlies 89", "MRIntW_ParticleFliesVolume 90", "MRIntW_SSGHandless 92", 
		"MRIntW_LongTermSmoke 93", "MRIntW_LoRWeaps 94", "MRIntW_InciniSmoke 95", "MRIntW_ParticleTexture 96", "MRIntW_ParticleSmokeTexture 97", "MRIntW_SwitchAnims 98",
		"MRIntW_RunKey 101", "MRIntW_BaseOffset 102", "MRIntW_BaseOffsetX 103", "MRIntW_BaseOffsetY 104", "MRIntW_WeaponSway 105", "MRIntW_WeaponSwayStyle 106",
		"MRIntW_SavedWbobFire 107", "MRIntW_RespawnParticles 108", "MRIntW_QuickSwitch 109", "MRIntW_PlasmaSkipLight 110", "MRIntW_FlowingSmokeBioTexture 111"
	};
	
	//Presset CVar syntax: "[Index] Value,[Index] Value,"
	
	Void WriteSettingsPresset()
	{
		Array<String> CVars;
		
		For(int i=0;i<CVarsId.Size();i++)CVars.Push("");
		
		For(int i=0;i<CVarsId.Size();i++){
			String CVa = CVarsId[i];
			int Index = CVa.Mid(CVa.IndexOf(" ")+1).ToInt();
			CVa = CVa.Left(CVa.IndexOf(" "));
			CVars[Index] = CVa;
		}
		
		if(MRIntW_Debug){
			For(int i=0;i<CVars.Size();i++)Console.Printf(i..": "..CVars[i]);
		}
						
		String Presset;
		
		For(int i=0;i<CVars.Size();i++){
			if(!CVar.FindCVar(CVars[i]))Continue;
			String Write = "["..i.."] ";
			String Value;
			Switch(CVar.FindCVar(CVars[i]).GetRealType()){
				Default:
				Case CVar.CVAR_Bool:
				Case CVar.CVAR_Int:
					Value = ""..CVar.FindCVar(CVars[i]).GetInt();
					Break;
				Case CVar.CVar_Float:
					Value = ""..CVar.FindCVar(CVars[i]).GetFloat();
					Break;
				Case CVar.CVar_Color:
					Color Col = CVar.FindCVar(CVars[i]).GetInt();
					Value = Col.R.." "..Col.G.." "..Col.B;
					Break;
			}
			
			Write = Write..Value..",";
			
			Presset = Presset..Write;
		}
		
		if(CVar.FindCVar("MRIntW_PressetCust"..MRIntW_WhichPresset))CVar.FindCVar("MRIntW_PressetCust"..MRIntW_WhichPresset).SetString(Presset);
	}
	
	Void ApplySettingsPresset()
	{
		if(!CVar.FindCVar("MRIntW_PressetCust"..MRIntW_WhichPresset) || CVar.FindCVar("MRIntW_PressetCust"..MRIntW_WhichPresset).GetString()=="")Return;
		
		Array<String> CVars;
		
		For(int i=0;i<CVarsId.Size();i++)CVars.Push("");
		
		For(int i=0;i<CVarsId.Size();i++){
			String CVa = CVarsId[i];
			int Index = CVa.Mid(CVa.IndexOf(" ")+1).ToInt();
			CVa = CVa.Left(CVa.IndexOf(" "));
			CVars[Index] = CVa;
		}
		
		Array<String> PresCVars;
		For(int i=0;i<CVarsId.Size();i++)PresCVars.Push("");
		
		String Presset = CVar.FindCVar("MRIntW_PressetCust"..MRIntW_WhichPresset).GetString();
		
		While(Presset.IndexOf(",")>-1){
			String CVa = Presset.Mid(Presset.IndexOf("[")+1);
			CVa = CVa.Left(CVa.IndexOf(","));
			int Index = CVa.Left(CVa.IndexOf("]")).ToInt();
			String Value = CVa.Mid(CVa.IndexOf("] ")+2);
			
			PresCVars[Index] = Value;
			
			Presset = Presset.Mid(Presset.IndexOf(",")+1);
		}
				
		For(int i=0;i<PresCVars.Size();i++){
			Let CVa = CVar.FindCVar(CVars[i]);
			if(PresCVars[i]=="" || !CVa)Continue;
			
			String PresCVar = PresCVars[i];
			
			Switch(CVa.GetRealType()){
				Default:
				Case CVar.CVAR_Bool:
				Case CVar.CVAR_Int:
					CVa.SetInt(PresCVar.ToInt());
					Break;
				Case CVar.CVar_Float:
					CVa.SetFloat(PresCVar.ToDouble());
					Break;
				Case CVar.CVar_Color:
					int Cols[3];
					String Colr = PresCVar.Left(PresCVar.IndexOf(" "));
					Cols[0] = Colr.ToInt();
					Colr = PresCVar.Mid(PresCVar.IndexOf(" ")+1);
					Colr = Colr.Left(Colr.IndexOf(" "));
					Cols[1] = Colr.ToInt();
					Colr = PresCVar.Mid(PresCVar.IndexOf(" ", 1)+1);
					Cols[2] = Colr.ToInt();
					CVa.SetInt(Color(Cols[0],Cols[1],Cols[2]));
					Break;
			}
		}
	}
}

Class OptionMenuItemMRIntWeaps_WritePresset: OptionMenuItemSubMenu
{
	String mPrompt;
	
	OptionMenuItemMRIntWeaps_WritePresset Init(String label, String prompt = "")
	{
		Super.Init(label, prompt);
		mPrompt = prompt;
		return self;
	}

	Override Bool Activate()
	{
		String msg = mPrompt.Length() > 0 ? mPrompt : "$SAFEMESSAGE";
		msg = StringTable.Localize(msg);
		String actionLabel = StringTable.localize(mLabel);

		String FullString;
		FullString = String.Format("%s%s%s\n\n%s", TEXTCOLOR_WHITE, actionLabel, TEXTCOLOR_NORMAL, msg);
		Menu.StartMessage(FullString, 0);
		return true;
	}
	
	override bool MenuEvent (int mkey, bool fromcontroller)
	{
		if (mkey == Menu.MKEY_MBYes)
		{
			ActuallyActivate();
			return true;
		}
		return Super.MenuEvent(mkey, fromcontroller);
	}
	
	Virtual Void ActuallyActivate()
	{
		if(!MRIntWeaps_PressetsMenu(Menu.GetCurrentMenu().mParentMenu))Return;
		
		MRIntWeaps_PressetsMenu(Menu.GetCurrentMenu().mParentMenu).WriteSettingsPresset();
	}
}

Class OptionMenuItemMRIntWeaps_ReadPresset: OptionMenuItemMRIntWeaps_WritePresset
{
	Override Void ActuallyActivate()
	{
		if(!MRIntWeaps_PressetsMenu(Menu.GetCurrentMenu().mParentMenu))Return;

		MRIntWeaps_PressetsMenu(Menu.GetCurrentMenu().mParentMenu).ApplySettingsPresset();
	}
}

Class MRIntWeaps_ViewPressetMenu: MRIntWeaps_PressetsMenu
{
	Override Void Init(Menu Parent, OptionMenuDescriptor Desc)
	{
		Super.Init(Parent, Desc);
		
		Desc.mTitle = String.Format(StringTable.Localize("$MRIntW_ViewingPresset"), MRIntW_WhichPresset);
		
		FillMenu(MRIntW_WhichPresset);
	}
	
	Void FillMenu(int Which)
	{
		mDesc.mItems.Clear();
		mDesc.mItems.Push(New('OptionMenuItemStaticText'));
				
		if(!CVar.FindCVar("MRIntW_PressetCust"..Which) || CVar.FindCVar("MRIntW_PressetCust"..Which).GetString()==""){
						
			Let Temp = New('OptionMenuItemStaticText');
			Temp.mLabel = "$MRIntW_EmptyPresset";
			Temp.mCentered = true;
			Temp.mColor = Color(255,255,0);
			
			mDesc.mItems.Push(Temp);
			Return;
		}
		
		Array<String> CVars;
		
		For(int i=0;i<CVarsId.Size();i++)CVars.Push("");
		
		For(int i=0;i<CVarsId.Size();i++){
			String CVa = CVarsId[i];
			int Index = CVa.Mid(CVa.IndexOf(" ")+1).ToInt();
			CVa = CVa.Left(CVa.IndexOf(" "));
			CVars[Index] = CVa;
		}
		
		Array<String> PresCVars;
		For(int i=0;i<CVarsId.Size();i++)PresCVars.Push("");
		
		String Presset = CVar.FindCVar("MRIntW_PressetCust"..MRIntW_WhichPresset).GetString();
		
		While(Presset.IndexOf(",")>-1){
			String CVa = Presset.Mid(Presset.IndexOf("[")+1);
			CVa = CVa.Left(CVa.IndexOf(","));
			int Index = CVa.Left(CVa.IndexOf("]")).ToInt();
			String Value = CVa.Mid(CVa.IndexOf("] ")+2);
			
			PresCVars[Index] = Value;
			
			Presset = Presset.Mid(Presset.IndexOf(",")+1);
		}
		
		int SpaceLeng = 0;
		For(int i=0;i<PresCVars.Size();i++){
			Let CVa = CVar.FindCVar(CVars[i]);
			if(PresCVars[i]=="" || !CVa)Continue;
			
			String Compare = StringTable.Localize("$"..CVars[i]).."  ";
			if(CVa.GetRealType()==CVar.CVar_Bool)Compare = Compare..(PresCVars[i].ToInt()?StringTable.Localize("$TXT_YES"):StringTable.Localize("$TXT_NO"));
			else if(StringTable.Localize("$"..CVars[i]..PresCVars[i]) != CVars[i]..PresCVars[i])Compare = Compare..StringTable.Localize("$"..CVars[i]..PresCVars[i]);
			else Compare = Compare..PresCVars[i];
			While(Compare.IndexOf("\c")>-1){
				Compare.Remove(Compare.IndexOf("\c"), 2);
			}
			if(SpaceLeng<Compare.CodePointCount())SpaceLeng = Compare.CodePointCount();
		}
		
		For(int i=0;i<PresCVars.Size();i++){
			Let CVa = CVar.FindCVar(CVars[i]);
			if(PresCVars[i]=="" || !CVa)Continue;
			
			Let Temp = New('OptionMenuItemCommand');
			Temp.mLabel = "\cg"..StringTable.Localize("$"..CVars[i])..": \c-";
			Temp.mLabel.Replace("\c-", "\cg");
			
			String Value;
			if(CVa.GetRealType()==CVar.CVar_Bool)Value = (PresCVars[i].ToInt()?StringTable.Localize("$TXT_YES"):StringTable.Localize("$TXT_NO"));
			else if(StringTable.Localize("$"..CVars[i]..PresCVars[i]) != CVars[i]..PresCVars[i])Value = StringTable.Localize("$"..CVars[i]..PresCVars[i]);
			else Value = PresCVars[i];
			
			String Len = Temp.mLabel..Value;
			While(Len.IndexOf("\c")>-1){
				Len.Remove(Len.IndexOf("\c"), 2);
			}
			For(int i1=Len.CodePointCount();i1<SpaceLeng;i1++){
				Temp.mLabel = Temp.mLabel.." ";
			}
			Temp.mLabel = Temp.mLabel.."\c-"..Value;
			
			Temp.mCentered = true;
			
			mDesc.mItems.Push(Temp);
		}
	}
}