Extend Class MRIntWeaps_Fist
{
	Bool Power2;
	
	Actor LineTarg;
	int TargLastHP, TargTargLastHP, Leading, Attacking, NoTargDelay;
	Vector2 FigOffset[2];
	
	Action Void A_CopyMaster(int Master, int Lay=0, Vector2 AddOffset=(0,0), Double AddAngle=0)
	{
		if(Lay==0)Lay = OverlayId();
		
		if(!Player.FindPSprite(Lay) || !Player.FindPSprite(Master))Return;
		
		Player.GetPSprite(Lay).X = Player.GetPSprite(Master).X + AddOffset.X;
		Player.GetPSprite(Lay).Y = Player.GetPSprite(Master).Y + AddOffset.Y;
		Player.GetPSprite(Lay).OldX = Player.GetPSprite(Master).OldX + AddOffset.X;
		Player.GetPSprite(Lay).OldY = Player.GetPSprite(Master).OldY + AddOffset.Y;
		
		if(Player.GetPSprite(Master).bFlip != Player.GetPSprite(Lay).bFlip)Player.GetPSprite(Lay).Rotation = -Player.GetPSprite(Master).Rotation - AddAngle;
		else Player.GetPSprite(Lay).Rotation = Player.GetPSprite(Master).Rotation + AddAngle;
		Player.GetPSprite(Lay).bInterpolate = Player.GetPSprite(Master).bInterpolate;
	}
	
	States
	{
		//Manual idle animations
		SecndHandCoolIdle:
			PUN1 A 1 {
				A_SetHandsSprite();
				A_OverlayPivot(OverlayId(), .5, .5);
				A_OverlayFlags(OverlayId(), PSPF_MIRROR|PSPF_FLIP, GetCVar("MRIntW_RightPunch"));
				Player.GetPSprite(OverlayId()).Translation = invoker.GlovesTrans;
				invoker.SecndHand = (0,0);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()).FirstTic);
				
				invoker.IdleState = 1;
			}
			#### # 0 {
				if(GetCVar("MRIntW_Braindead") && (Health==67 || (FindInventory("BasicArmor") && FindInventory("BasicArmor").Amount==67) || int(Level.Time/35)%67==0))Return ResolveState("SecndHandCoolIdle666");
				
				if(Health==69 || Health==169 || (FindInventory("BasicArmor") && (FindInventory("BasicArmor").Amount==69 || FindInventory("BasicArmor").Amount==169)) || int(Level.Time/35)%69==0)Return ResolveState("SecndHandCoolIdleRomero");
				
				A_ClearOverlays(MainLay+1, MainLay+10);
				invoker.LineTarg = Null;
				invoker.Leading = invoker.TargLastHP = invoker.TargTargLastHP = invoker.Attacking = 0;
				FLineTraceData CheckAct;
				Double PZ = height * .5 - floorclip + Player.mo.AttackZOffset*player.crouchFactor;
				LineTrace(Angle, 1500, Pitch, 0, PZ, 0, 0, CheckAct);
				
				if(CheckAct.HitActor != Null){
					if(CheckAct.HitActor.Target && CheckAct.HitActor.Target != Self)invoker.LineTarg = CheckAct.HitActor;
				
					if(invoker.LineTarg)Return ResolveState("SecndHandInfight");
				}
				
				if(Player.FindPSprite(MainLay))Player.SetPsprite(MainLay, invoker.FindState("MainHandCoolIdle"));
				else Player.SetPsprite(MainLay, invoker.FindState("MainHandCoolIdlePre"));
				/*Switch(CRandom(1, 1))
				{
					Case 1:
						Return ResolveState("SecndHandCoolIdle666");
				}*/
				Return ResolveState(Null);
			}
		//Fist bump
			#### E 1 {
				A_OverlayFlags(OverlayId(), PSPF_FLIP, !GetCVar("MRIntW_RightPunch"));
				A_OverlayScale(OverlayId(), 1.35, 1.35);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, false);
				Player.GetPSprite(OverlayId()).OldX = 260;
				Player.GetPSprite(OverlayId()).OldY = -10;
				
				Player.GetPSprite(OverlayId()).X = Player.GetPSprite(OverlayId()).OldX+CFRandom(9, 14);
				Player.GetPSprite(OverlayId()).Y = Player.GetPSprite(OverlayId()).OldY+CFRandom(-2, 2);
				invoker.Power2 = false;
			}
			#### # 1 {
				A_StartSound("MRIntW/FistSwing", CHAN_AUTO, CHANF_LOCAL, .5, pitch:CFRandom(.9, 1.1)*i_timescale);
				A_OverlayOffset(OverlayId(), 265+20, -10+CFRandom(-4, 4), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.31, 1.35, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), -30, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), 1.25, 1.3, WOF_INTERPOLATE);
			}
			#### # 0 A_JumpIf(!(Player.Cmd.Buttons&BT_ALTATTACK) && CRandom(0, 5)==0, "SecndHandCoolIdleAltEnd");
			#### # 1 {
				A_StartSound("MRIntW/FistPuch", CHAN_AUTO, CHANF_LOCAL, CFRandom(.5, .55), pitch: CFRandom(1.45, 1.55)*i_timescale);
				A_OverlayOffset(OverlayId(), 265 -50, -10+CFRandom(-2, 2), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.1, CFRandom(1.4, 1.45), WOF_INTERPOLATE);
			}
			#### # 0 A_JumpIf(Player.Cmd.Buttons&BT_ALTATTACK, "SecndHandCoolIdlePower");
			#### # 1 {
				A_OverlayOffset(OverlayId(), 265 -50, -10+CFRandom(-1, 1), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.17, 1.4, WOF_INTERPOLATE);
			}
			#### # 1 {
				invoker.Power2 = true;
				A_OverlayOffset(OverlayId(), 265 -50, -10, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.2, 1.37, WOF_INTERPOLATE);
			}
			#### # 2 {
				A_OverlayOffset(OverlayId(), 265 -50, -10, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.25, 1.35, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(6, 8), -3, WOF_ADD);
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
				A_OverlayRotate(OverlayId(), 2, WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(18, 24), -3, WOF_ADD);
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
				A_OverlayRotate(OverlayId(), 2, WOF_ADD);
			}
			#### # 2 {
				A_StartSound("MRIntW/FistSwing", CHAN_AUTO, CHANF_LOCAL, .5, pitch:CFRandom(.9, 1.1)*i_timescale);
				A_OverlayOffset(OverlayId(), 265+CFRandom(50, 63), -10-9, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), -CFRandom(28, 34), 3, WOF_ADD);
				A_OverlayScale(OverlayId(), CFRandom(.03, .05), -CFRandom(.01, .02), WOF_ADD);
				A_OverlayRotate(OverlayId(), -4, WOF_ADD);
			}
			#### # 0 A_JumpIf(!(Player.Cmd.Buttons&BT_ALTATTACK) && CRandom(0, 2)==0, "SecndHandCoolIdleAltEnd");
			#### # 1 {
				A_StartSound("MRIntW/FistPuch", CHAN_AUTO, CHANF_Local, CFRandom(.5, .55), pitch: CFRandom(1.45, 1.55)*i_timescale);
				A_OverlayOffset(OverlayId(), 265 -50, -10+CFRandom(-3, 3), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.08, 1.37, WOF_INTERPOLATE);
			}
			#### # 0 A_JumpIf(Player.Cmd.Buttons&BT_ALTATTACK, "SecndHandCoolIdlePower");
			#### # 1 {
				A_OverlayOffset(OverlayId(), 265 -50, -10+CFRandom(-1, 1), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.15, 1.36, WOF_INTERPOLATE);
			}
			#### # 4 {
				A_OverlayOffset(OverlayId(), 265 -50, -10, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.2, 1.35, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(6, 8), 4, WOF_ADD);
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId(), CFRandom(16, 19), 4, WOF_ADD);
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
			}
			#### # 0 {
					A_OverlayOffset(OverlayId(), 0, 0);
					A_OverlayScale(OverlayId(), 1, 1);
			}
			Goto SecndHandWait;
		SecndHandCoolIdleAltEnd:
			#### # 1 {
				Player.SetPsprite(MainLay, invoker.FindState("MainHandCoolIdleAltEnd"));
				A_StartSound("MRIntW/FistPuch", CHAN_AUTO, CHANF_Local, CFRandom(.5, .55), pitch: CFRandom(1.45, 1.55)*i_timescale);
				A_OverlayOffset(OverlayId(), 265 -55, -10+CFRandom(-3, 3), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.08, 1.37, WOF_INTERPOLATE);
			}
			#### # 2 {
				A_OverlayOffset(OverlayId(), 265 -75, -10+CFRandom(-1, 1), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.15, 1.36, WOF_INTERPOLATE);
			}
			#### #### 1 {
				A_OverlayOffset(OverlayId(), 5, (-10-Player.GetPSprite(OverlayId()).Y)*.6, WOF_ADD);
				A_OverlayScale(OverlayId(), .0125, -.0025, WOF_ADD);
			}
			#### # 4 {
				A_OverlayOffset(OverlayId(), 265 -50, -10, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.2, 1.35, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(6, 8), 4, WOF_ADD);
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
			}
			#### ## 1 {
				Player.GetPSprite(OverlayId()).X = 265+(Player.GetPSprite(OverlayId()).X-265)*.6;
				Player.GetPSprite(OverlayId()).Y += 4;
				A_OverlayScale(OverlayId(), -CFRandom(.01, .02), CFRandom(.005, .01), WOF_ADD);
			}
			#### # 0 {
					A_OverlayOffset(OverlayId(), 0, 0);
					A_OverlayScale(OverlayId(), 1, 1);
			}
			Goto SecndHandWait;
		SecndHandCoolIdlePower:
			#### # 1 {
				Player.SetPsprite(MainLay, invoker.FindState("MainHandCoolIdlePower"));
				A_OverlayOffset(OverlayId(), 265 -80, -10+CFRandom(-2, 2), WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), 1.1, CFRandom(1.4, 1.45), WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 15, -4, WOF_ADD);
				A_OverlayScale(OverlayId(), 1.15, 1.25, WOF_INTERPOLATE);
				A_OverlayRotate(OverlayId(), 1, WOF_ADD);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, true);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(35, 45)*(invoker.Power2+1), -CFRandom(6, 9)*(invoker.Power2+1), WOF_ADD);
				A_OverlayScale(OverlayId(), 1.3, 1.25, WOF_INTERPOLATE);
				A_OverlayRotate(OverlayId(), CFRandom(3, 5)*(invoker.Power2+1), WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 7*(invoker.Power2+1), -2*(invoker.Power2+1), WOF_ADD);
				A_OverlayScale(OverlayId(), 1.25, 1.3, WOF_INTERPOLATE);
				A_OverlayRotate(OverlayId(), 2, WOF_ADD);
			}
			#### # 2 {
				A_OverlayOffset(OverlayId(), 4*(invoker.Power2+1), -1*(invoker.Power2+1), WOF_ADD);
				A_OverlayScale(OverlayId(), 1.25, 1.35, WOF_INTERPOLATE);
				A_OverlayRotate(OverlayId(), 1, WOF_ADD);
			}
			#### #### 1 {
				Player.GetPSprite(OverlayId()).X = 265+(Player.GetPSprite(OverlayId()).X-265)*.7;
				Player.GetPSprite(OverlayId()).Y = -10+(Player.GetPSprite(OverlayId()).Y+10)*.7;
				Player.GetPSprite(OverlayId()).Rotation *= .7;
			}
			#### ## 1 {
				Player.GetPSprite(OverlayId()).X = 255+(Player.GetPSprite(OverlayId()).X-255)*.4;
				Player.GetPSprite(OverlayId()).Y *= .4;
				Player.GetPSprite(OverlayId()).Rotation *= .4;
			}
			#### # 0 {
					A_OverlayOffset(OverlayId(), 0, 0);
					A_OverlayScale(OverlayId(), 1, 1);
			}
			Goto SecndHandWait;
		//Fist bump second hand
		MainHandCoolIdle:
			PUN1 C 1 {
				A_OverlayOffset(OverlayId(), invoker.MainHand.X, invoker.MainHand.Y);
				A_SetHandsSprite();
				A_OverlayPivot(OverlayId(), 1, .5);
				A_OverlayFlags(OverlayId(), PSPF_MIRROR|PSPF_FLIP, GetCVar("MRIntW_RightPunch"));
				Player.GetPSprite(OverlayId()).Translation = invoker.GlovesTrans;
				invoker.MainHand = (0,0);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()).FirstTic);
			}
			#### H 1 {
				A_OverlayOffset(OverlayId(), CFRandom(5, 7), CFRandom(-1, 1), WOF_ADD);
				A_OverlayScale(OverlayId(), -.05, CFRandom(.01, .02), WOF_ADD);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()).FirstTic);
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId(), CFRandom(5, 7), CFRandom(-1, 1), WOF_ADD);
				A_OverlayScale(OverlayId(), -.05, CFRandom(.01, .02), WOF_ADD);
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()).FirstTic);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 30, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .75, 1.1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(29, 31), 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .7, 1.05, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(29, 31), 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .73, 1.075, WOF_INTERPOLATE);
			}
			#### # 2 {
				A_OverlayOffset(OverlayId(), 30, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .75, 1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), -.0001, CFRandom(.005, .01), WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), -.002, CFRandom(.005, .01), WOF_ADD);
			}
			#### # 2 {
				A_OverlayOffset(OverlayId(), 20, CFRandom(-2, 2), WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), CFRandom(.03, .05), -CFRandom(.01, .02), WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 30, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .67, 1.1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(29, 31), 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .7, 1.05, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), CFRandom(29, 31), 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .73, 1.075, WOF_INTERPOLATE);
			}
			#### # 5 {
				A_SetTics(CRandom(3, 5));
				A_OverlayOffset(OverlayId(), 30, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .75, 1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), .1, CFRandom(.005, .01), WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), .1, CFRandom(.005, .01), WOF_ADD);
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId(), -10, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), 1, 1, WOF_INTERPOLATE);
			}
			#### # 1 A_OverlayOffset(OverlayId(), 0, 0, WOF_INTERPOLATE);
			#### # 0 A_JumpIf(GetCVar("MRIntW_SecondFist")||(CountInv("PowerStrength") && GetCVar("MRIntW_BersShake")), "MainHandWait");
		MainHandCoolIdleEnd:
			#### ###### 1 A_OverlayOffset(OverlayId(), -10, 10, WOF_ADD);
			Stop;
		MainHandCoolIdleAltEnd:
			#### # 1 {
				A_OverlayOffset(OverlayId(), 25, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .67, 1.1, WOF_INTERPOLATE);
			}
			#### # 2 {
				A_OverlayOffset(OverlayId(), CFRandom(6, 7), 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .7, 1.05, WOF_INTERPOLATE);
			}
			#### #### 1 {
				A_OverlayOffset(OverlayId(), 5, 0, WOF_ADD);
				A_OverlayScale(OverlayId(), .0125, -.0125, WOF_ADD);
			}
			#### # 4 {
				A_SetTics(CRandom(4, 6));
				A_OverlayOffset(OverlayId(), 30, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .75, 1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), .1, CFRandom(.005, .01), WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), .1, CFRandom(.005, .01), WOF_ADD);
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId(), -10, CFRandom(-2, 2), WOF_ADD);
				A_OverlayScale(OverlayId(), 1, 1, WOF_INTERPOLATE);
			}
			#### # 1 A_OverlayOffset(OverlayId(), 0, 0, WOF_INTERPOLATE);
			#### # 0 A_JumpIf(GetCVar("MRIntW_SecondFist")||(CountInv("PowerStrength") && GetCVar("MRIntW_BersShake")), "MainHandWait");
			Goto MainHandCoolIdleEnd;
		MainHandCoolIdlePower:
			#### # 1 {
				A_OverlayOffset(OverlayId(), 10, 0, WOF_INTERPOLATE);
				A_OverlayScale(OverlayId(), .67, 1.1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), -30, -4, WOF_ADD);
				A_OverlayRotate(OverlayId(), 4, WOF_ADD);
				A_OverlayScale(OverlayId(), .75, 1, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), -60*(invoker.Power2+1), -7*(invoker.Power2+1), WOF_ADD);
				A_OverlayRotate(OverlayId(), 3*(invoker.Power2+1), WOF_ADD);
				A_OverlayScale(OverlayId(), .8, .9, WOF_INTERPOLATE);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), -14, -5, WOF_ADD);
				A_OverlayRotate(OverlayId(), 4, WOF_ADD);
				A_OverlayScale(OverlayId(), .77, .95, WOF_INTERPOLATE);
			}
			#### # 3 {
				A_OverlayOffset(OverlayId(), -5, -2, WOF_ADD);
				A_OverlayRotate(OverlayId(), 2, WOF_ADD);
				A_OverlayScale(OverlayId(), .75, 1, WOF_INTERPOLATE);
			}
			#### ####### 1 {
				Player.GetPSprite(OverlayId()).X *= .8;
				Player.GetPSprite(OverlayId()).Y *= .8;
				Player.GetPSprite(OverlayId()).Rotation *= .8;
			}
			#### # 1 {
				A_OverlayOffset(OverlayId(), 0, 0, WOF_INTERPOLATE);
				A_OverlayRotate(OverlayId(), 0, WOF_INTERPOLATE);
			}
			#### # 0 A_JumpIf(GetCVar("MRIntW_SecondFist")||(CountInv("PowerStrength") && GetCVar("MRIntW_BersShake")), "MainHandWait");
			Goto MainHandCoolIdleEnd;
			
			
			
		//Playing with demon toys
		MainHandInfightStart:
			#### # 1;
			Wait;
		SecndHandInfight:
			#### # 1 {
				Player.SetPsprite(MainLay, invoker.FindState("MainHandInfightStart"));
				A_OverlayOffset(SecndLay, 0, 5, WOF_ADD);
				A_OverlayOffset(MainLay, 0, 5, WOF_ADD);
			}
			#### #### 1 {
				A_OverlayOffset(SecndLay, 0, 12, WOF_ADD);
				A_OverlayOffset(MainLay, 0, 12, WOF_ADD);
			}
			#### # 2;
			PUN1 L 1 {
				A_OverlayFlags(OverlayId(), PSPF_MIRROR|PSPF_FLIP, GetCVar("MRIntW_RightPunch"));
				A_SetHandsSprite();
				Player.GetPSprite(SecndLay).Translation = invoker.GlovesTrans;
				A_OverlayPivot(OverlayId(), 1, .2);
				A_OverlayRotate(OverlayId(), 90);
				A_OverlayScale(OverlayId(), 1.2, 1.2);
				
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, false);
			}
			#### # 1 {
				invoker.NoTargDelay = 0;
				A_Overlay(MainLay+1, "SecndHandInfightOver");
				A_Overlay(MainLay, "InfightActor");
				
				A_Overlay(MainLay+2, "MainHandInfight");
				Player.GetPSprite(MainLay+2).X = Player.GetPSprite(SecndLay).X;
				Player.GetPSprite(MainLay+2).Y = Player.GetPSprite(SecndLay).Y;
				Player.GetPSprite(MainLay+2).OldX = Player.GetPSprite(SecndLay).OldX;
				Player.GetPSprite(MainLay+2).OldY = Player.GetPSprite(SecndLay).OldY;
				A_Overlay(MainLay+4, "SecndHandInfightOver");
				A_Overlay(MainLay+3, "InfightActor");
			}
			#### ########### 1 {
				Player.GetPSprite(SecndLay).Y = -40+(Player.GetPSprite(SecndLay).Y+40)*.8;
				Player.GetPSprite(MainLay+2).Y = -40+(Player.GetPSprite(SecndLay).Y+40)*.8;
			}
			#### # 1 {
				A_OverlayOffset(SecndLay, 0, -40, WOF_INTERPOLATE);
				A_OverlayOffset(MainLay+2, 0, -40, WOF_INTERPOLATE);
			}
		SecndHandInfightLoop:
			#### # 1{
				if(!invoker.LineTarg || invoker.LineTarg.Health<1 || invoker.NoTargDelay>35*8)
				{
					if(invoker.LineTarg && invoker.LineTarg.Health<1)Player.SetPsprite(OverlayId()+6, invoker.FindState("HandInfightDeath"));
					Player.SetPsprite(OverlayId(), invoker.FindState("SecndHandInfightEnd"));
				}
				
				if(!Player.FindPSprite(OverlayId()+6) && Player.GetPSprite(OverlayId()).Frame != 10 && 
					invoker.LineTarg.Target && invoker.LineTarg.Target != Self && Player.FindPSprite(MainLay+2) &&
					(InStateSequence(invoker.LineTarg.CurState, invoker.LineTarg.FindState("Missile"))||
					InStateSequence(invoker.LineTarg.CurState, invoker.LineTarg.FindState("Melee")))
				){
					Player.SetPsprite(OverlayId()+6, invoker.FindState("HandInfightAttack"));
					if(invoker.Leading==0)invoker.Leading = 1;
				}
				if(!Player.FindPSprite(OverlayId()+6) &&invoker.TargLastHP > invoker.LineTarg.Health)
				{
					Player.SetPsprite(OverlayId()+6, invoker.FindState("HandInfightPain"));
				}
				if(!Player.FindPSprite(OverlayId()+6) && invoker.Attacking < 0)
				{
					Player.SetPsprite(OverlayId()+6, invoker.FindState("HandInfightDodge"));
				}
				
				if(!Player.FindPSprite(MainLay+2) && invoker.LineTarg.Target && invoker.LineTarg.Target != Self){
					A_Overlay(MainLay+2, "MainHandInfight");
					Player.GetPSprite(MainLay+2).X = Player.GetPSprite(SecndLay).X;
					Player.GetPSprite(MainLay+2).Y = 100;
					Player.GetPSprite(MainLay+2).OldX = Player.GetPSprite(SecndLay).OldX;
					Player.GetPSprite(MainLay+2).OldY = Player.GetPSprite(MainLay+2).OldY;
					A_Overlay(MainLay+4, "SecndHandInfightOver");
					A_Overlay(MainLay+3, "InfightActor");
					A_Overlay(MainLay+2+6, "HandInfightRaise");
					invoker.NoTargDelay = 0;
					
					Return;
				}
				
				if(!Player.FindPSprite(MainLay+2)){
					invoker.NoTargDelay++;
					Return;
				}
				
				if(!invoker.LineTarg.Target || invoker.LineTarg.Target.Health<1){
					if(!Player.FindPSprite(MainLay+2+6) || !InStateSequence(Player.GetPSprite(MainLay+2+6).CurState, invoker.FindState("HandInfightDeath"))){
						Player.SetPsprite(MainLay+2+6, invoker.FindState("HandInfightDeath"));
						//if(CRandom(0,3)==1 && (!Player.FindPSprite(SecndLay+6) || !InStateSequence(Player.GetPSprite(SecndLay+6).CurState, invoker.FindState("HandInfightPraise"))))Player.SetPsprite(SecndLay+6, invoker.FindState("HandInfightPraise"));
					}
					Return;
				}
				
				if(!Player.FindPSprite(MainLay+2+6) && Player.GetPSprite(MainLay+2).Frame != 10 && invoker.LineTarg.Target &&
					invoker.LineTarg.Target.Target == invoker.LineTarg &&(
					InStateSequence(invoker.LineTarg.Target.CurState, invoker.LineTarg.Target.FindState("Missile"))||
					InStateSequence(invoker.LineTarg.Target.CurState, invoker.LineTarg.Target.FindState("Melee")))
				){
					Player.SetPsprite(MainLay+2+6, invoker.FindState("HandInfightAttack"));
					if(invoker.Leading == 0)invoker.Leading = -1;
				}
				if(!Player.FindPSprite(MainLay+2+6) && invoker.TargTargLastHP > invoker.LineTarg.Target.Health)
				{
					Player.SetPsprite(MainLay+2+6, invoker.FindState("HandInfightPain"));
				}
				if(!Player.FindPSprite(MainLay+2+6) && invoker.Attacking > 0)
				{
					Player.SetPsprite(MainLay+2+6, invoker.FindState("HandInfightDodge"));
				}
			}
			Wait;
		SecndHandInfightEnd:
			#### ################################### 1 {
				if(!Player.FindPSprite(OverlayId()+6)){
					A_OverlayOffset(SecndLay, 0, 7, WOF_ADD);
					if(invoker.LineTarg.Health<1)Player.GetPSprite(SecndLay).X = CFRandom(-4, 4)*(GetAge()%2==0?1:-1);
				}
				if(!Player.FindPSprite(MainLay+2+6)){
					A_OverlayOffset(MainLay+2, 0, 7, WOF_ADD);
					if(Player.GetPSprite(MainLay+2).Y < Player.GetPSprite(SecndLay).Y)
						Player.GetPSprite(MainLay+2).Y = Player.GetPSprite(SecndLay).Y+(Player.GetPSprite(MainLay+2).Y-Player.GetPSprite(SecndLay).Y)*.8;
					
					if(invoker.LineTarg.Health>0 || (invoker.LineTarg.Target && invoker.LineTarg.Target.Health<1))Player.GetPSprite(MainLay+2).X = CFRandom(-4, 4)*(GetAge()%2==0?1:-1);
				}
				
				A_CopyMaster(OverlayId(), MainLay, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId(), MainLay+1);
				
				A_CopyMaster(OverlayId(), MainLay+3, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId(), MainLay+4);
			}
			#### # 3 {
				A_ClearOverlays(MainLay, MainLay+8);
				A_OverlayScale(OverlayId(), 1, 1);
			}
			Goto SecndHandRaise+1;
			
		HandInfightAttack:
			#### # 0 {
				if(OverlayId()-6==SecndLay && invoker.LineTarg)A_StartSound(invoker.LineTarg.AttackSound, CHAN_VOICE, CHANF_LOCAL, .3, pitch:CFRandom(1.4, 1.45));
				else if(invoker.LineTarg && invoker.LineTarg.Target)A_StartSound(invoker.LineTarg.Target.AttackSound, CHAN_VOICE, CHANF_LOCAL, .3, pitch:CFRandom(1.4, 1.45));
			}
			#### ### 1 {
				A_OverlayOffset(OverlayId()-6, -20, -10, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, 1, WOF_ADD);
				
				A_OverlayFlags(OverlayId()-6, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-6).FirstTic);
				A_OverlayFlags(OverlayId()-4, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-4).FirstTic);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, -5, -4, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, .5, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 A_StartSound("MRIntW/FistSwing", CHAN_AUTO, CHANF_LOCAL, .4, pitch:CFRandom(2, 2.1)*i_timescale);
			#### ## 1 {
				A_OverlayOffset(OverlayId()-6, 90, 10, WOF_ADD);
				
				int Other = OverlayId()-6;
				if(Other==SecndLay)Other = MainLay+2;
				else Other = SecndLay;
				if((invoker.Leading<1 && Other==SecndLay) || (invoker.Leading>-1 && Other!=SecndLay)){
					Player.GetPSprite(OverlayId()-6).Y = Min(Player.GetPSprite(Other).Y, Player.GetPSprite(OverlayId()-6).Y);
					Player.GetPSprite(OverlayId()-6).X = Min(80-Player.GetPSprite(Other).X, Player.GetPSprite(OverlayId()-6).X);
				}
				
				if(other==SecndLay)invoker.Attacking = -1;
				else invoker.Attacking = 1;
				A_OverlayRotate(OverlayId()-6, -3, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, 5, 8, WOF_ADD);
				
				int Other = OverlayId()-6;
				if(Other==SecndLay)Other = MainLay+2;
				else Other = SecndLay;
				if((invoker.Leading<1 && Other==SecndLay) || (invoker.Leading>-1 && Other!=SecndLay)){
					Player.GetPSprite(OverlayId()-6).Y = Min(Player.GetPSprite(Other).Y, Player.GetPSprite(OverlayId()-6).Y);
					Player.GetPSprite(OverlayId()-6).X = Min(80-Player.GetPSprite(Other).X, Player.GetPSprite(OverlayId()-6).X);
				}
				A_OverlayRotate(OverlayId()-6, -2, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_StartSound("MRIntW/FistPuch", CHAN_AUTO, CHANF_LOCAL, CFRandom(.3, .35), pitch: CFRandom(1.2, 1.3)*i_timescale);
				A_OverlayOffset(OverlayId()-6, 2, 3, WOF_ADD);
				
				int Other = OverlayId()-6;
				if(Other==SecndLay)Other = MainLay+2;
				else Other = SecndLay;
				if((invoker.Leading<1 && Other==SecndLay) || (invoker.Leading>-1 && Other!=SecndLay)){
					Player.GetPSprite(OverlayId()-6).Y = Min(Player.GetPSprite(Other).Y, Player.GetPSprite(OverlayId()-6).Y);
					Player.GetPSprite(OverlayId()-6).X = Min(80-Player.GetPSprite(Other).X, Player.GetPSprite(OverlayId()-6).X);
				}
				A_OverlayRotate(OverlayId()-6, -1, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, -3, -2, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, -.1, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ##### 1 {
				Player.GetPSprite(OverlayId()-6).X *= CFRandom(.6, .7);
				Player.GetPSprite(OverlayId()-6).Y = -40+(Player.GetPSprite(OverlayId()-6).Y+40)*CFRandom(.6, .7);
				A_OverlayRotate(OverlayId()-6, 1, WOF_ADD);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
				invoker.Leading = invoker.Attacking = 0;
			}
			#### # 6 {
				A_OverlayRotate(OverlayId()-6, .6, WOF_ADD);
				A_OverlayOffseT(OverlayId()-6, 0, -40, WOF_INTERPOLATE);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			Stop;
		HandInfightDodge:
			#### ## 1 {
				A_OverlayOffset(OverlayId()-6, 9, CFRandom(13, 18), WOF_ADD);
				
				A_OverlayFlags(OverlayId()-6, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-6).FirstTic);
				A_OverlayFlags(OverlayId()-4, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-4).FirstTic);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
				
				if(OverlayId()-6==SecndLay && invoker.LineTarg && invoker.LineTarg.Health<invoker.TargLastHP)Player.SetPsprite(OverlayId(), invoker.FindState("HandInfightPain"));
				if(OverlayId()-6!=SecndLay && invoker.LineTarg && invoker.LineTarg.Target && invoker.LineTarg.Target.Health<invoker.TargTargLastHP)Player.SetPsprite(OverlayId(), invoker.FindState("HandInfightPain"));
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, 4, CFRandom(4, 7), WOF_ADD);
				
				A_OverlayFlags(OverlayId()-6, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-6).FirstTic);
				A_OverlayFlags(OverlayId()-4, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-4).FirstTic);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			
				if(OverlayId()-6==SecndLay && invoker.LineTarg && invoker.LineTarg.Health<invoker.TargLastHP)Player.SetPsprite(OverlayId(), invoker.FindState("HandInfightPain"));
				if(OverlayId()-6!=SecndLay && invoker.LineTarg && invoker.LineTarg.Target && invoker.LineTarg.Target.Health<invoker.TargTargLastHP)Player.SetPsprite(OverlayId(), invoker.FindState("HandInfightPain"));
			}
			#### #### 1{
				A_OverlayOffset(OverlayId()-6, CFRandom(-.1, .1), CFRandom(-.1, .1), WOF_ADD);
				
				A_OverlayFlags(OverlayId()-6, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-6).FirstTic);
				A_OverlayFlags(OverlayId()-4, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-4).FirstTic);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			
				if(OverlayId()-6==SecndLay && invoker.LineTarg && invoker.LineTarg.Health<invoker.TargLastHP)Player.SetPsprite(OverlayId(), invoker.FindState("HandInfightPain"));
				if(OverlayId()-6!=SecndLay && invoker.LineTarg && invoker.LineTarg.Target && invoker.LineTarg.Target.Health<invoker.TargTargLastHP)Player.SetPsprite(OverlayId(), invoker.FindState("HandInfightPain"));
			}
			#### ###### 1 {
				Player.GetPSprite(OverlayId()-6).X *= CFRandom(.6, .7);
				Player.GetPSprite(OverlayId()-6).Y = -40+(Player.GetPSprite(OverlayId()-6).Y+40)*CFRandom(.6, .7);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			
				if(OverlayId()-6==SecndLay && invoker.LineTarg && invoker.LineTarg.Health<invoker.TargLastHP)Player.SetPsprite(OverlayId(), invoker.FindState("HandInfightPain"));
				if(OverlayId()-6!=SecndLay && invoker.LineTarg && invoker.LineTarg.Target && invoker.LineTarg.Target.Health<invoker.TargTargLastHP)Player.SetPsprite(OverlayId(), invoker.FindState("HandInfightPain"));
			}
			#### # 1 {
				A_OverlayOffseT(OverlayId()-6, 0, -40, WOF_INTERPOLATE);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			Stop;
		HandInfightPain:
			#### # 0 {
				if(OverlayId()-6==SecndLay && invoker.LineTarg)A_StartSound(invoker.LineTarg.PainSound, CHAN_VOICE, CHANF_LOCAL, .3, pitch:CFRandom(1.4, 1.45));
				else if(invoker.LineTarg && invoker.LineTarg.Target)A_StartSound(invoker.LineTarg.Target.PainSound, CHAN_VOICE, CHANF_LOCAL, .3, pitch:CFRandom(1.4, 1.45));
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId()-6, -6, CFRandom(-4, 4), WOF_ADD);
				
				A_OverlayFlags(OverlayId()-6, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-6).FirstTic);
				A_OverlayFlags(OverlayId()-4, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-4).FirstTic);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, -2, CFRandom(-1, 1), WOF_ADD);
				
				A_OverlayFlags(OverlayId()-6, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-6).FirstTic);
				A_OverlayFlags(OverlayId()-4, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-4).FirstTic);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ## 1 {
				Player.GetPSprite(OverlayId()-6).X *= CFRandom(.8, .9);
				Player.GetPSprite(OverlayId()-6).Y = -40+(Player.GetPSprite(OverlayId()-6).Y+40)*CFRandom(.8, .9);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ### 1 {
				Player.GetPSprite(OverlayId()-6).X *= CFRandom(.6, .7);
				Player.GetPSprite(OverlayId()-6).Y = -40+(Player.GetPSprite(OverlayId()-6).Y+40)*CFRandom(.6, .7);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, 0, -40, WOF_INTERPOLATE);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			Stop;
		HandInfightDeath:
			#### # 0 {
				if(OverlayId()-6==SecndLay && invoker.LineTarg)A_StartSound(invoker.LineTarg.DeathSound, CHAN_VOICE, CHANF_LOCAL, .3, pitch:CFRandom(1.4, 1.45));
				else if(invoker.LineTarg && invoker.LineTarg.Target)A_StartSound(invoker.LineTarg.Target.DeathSound, CHAN_VOICE, CHANF_LOCAL, .3, pitch:CFRandom(1.4, 1.45));
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId()-6, -CFRandom(9, 14), -CFRandom(2, 4), WOF_ADD);
				A_OverlayRotate(OverlayId()-6, CFRandom(1, 2), WOF_ADD);
				
				A_OverlayFlags(OverlayId()-6, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-6).FirstTic);
				A_OverlayFlags(OverlayId()-4, PSPF_INTERPOLATE, !Player.GetPSprite(OverlayId()-4).FirstTic);
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ## 1 {
				A_OverlayOffset(OverlayId()-6, -CFRandom(6, 8), 1, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, CFRandom(.25, .7), WOF_ADD);

				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ##### 1 {
				A_OverlayOffset(OverlayId()-6, -CFRandom(6, 8) + (GetAge()%2==0?CFRandom(1, 3):-CFRandom(1, 3)), CFRandom(14, 20), WOF_ADD);
				A_OverlayRotate(OverlayId()-6, CFRandom(.25, .7), WOF_ADD);

				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, -CFRandom(6, 8)*5, CFRandom(14, 20)*5, WOF_ADD);
				A_OverlayRotate(OverlayId()-6, CFRandom(.25, .7)*5, WOF_ADD);

				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 0 {if(OverlayId()-6!=SecndLay)A_ClearOverlays(OverlayId()-6, OverlayId()-4);}
			Stop;
		HandInfightRaise:
			#### # 1;
			#### ######## 1 {
				Player.GetPSprite(OverlayId()-6).Y = -40+(Player.GetPSprite(OverlayId()-6).Y+40)*.8;

				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, 0, -40, WOF_INTERPOLATE);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			Stop;
		HandInfightPraise:
			#### ###### 1 {
				if(Player.GetPSprite(OverlayId()-6).Rotation>60){
					Player.GetPSprite(OverlayId()-6).Rotation = 90+(Player.GetPSprite(OverlayId()-6).Rotation-90)*.7;
				}
				else Player.GetPSprite(OverlayId()-6).Rotation *= .7;
				
				Player.GetPSprite(OverlayId()-6).X *= .8;
				Player.GetPSprite(OverlayId()-6).Y = -70+(Player.GetPSprite(OverlayId()-6).Y+70)*.8;
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				if(Player.GetPSprite(OverlayId()-6).Rotation>60)A_OverlayRotate(OverlayId()-6, 90, WOF_INTERPOLATE);
				else A_OverlayRotate(OverlayId()-6, 0, WOF_INTERPOLATE);
				
				A_OverlayOffset(OverlayId()-6, 0, -70, WOF_INTERPOLATE);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ### 1 {
				A_OverlayRotate(OverlayId()-6, -3, WOF_ADD);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ## 1 {
				A_OverlayRotate(OverlayId()-6, 6, WOF_ADD);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ## 1 {
				A_OverlayRotate(OverlayId()-6, 3, WOF_ADD);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ## 1 {
				A_OverlayRotate(OverlayId()-6, -6, WOF_ADD);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ## 1 {
				A_OverlayRotate(OverlayId()-6, -3, WOF_ADD);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ## 1 {
				A_OverlayRotate(OverlayId()-6, 6, WOF_ADD);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ## 1 {
				A_OverlayRotate(OverlayId()-6, 3, WOF_ADD);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ## 1 {
				A_OverlayRotate(OverlayId()-6, -6, WOF_ADD);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayRotate(OverlayId()-6, 3, WOF_ADD);
				Player.GetPSprite(OverlayId()-6).Y = -40+(Player.GetPSprite(OverlayId()-6).Y+40)*.85;
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### ###### 1 {
				Player.GetPSprite(OverlayId()-6).X *= .8;
				Player.GetPSprite(OverlayId()-6).Y = -40+(Player.GetPSprite(OverlayId()-6).Y+40)*.8;
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			#### # 1 {
				A_OverlayOffset(OverlayId()-6, 0, -40, WOF_INTERPOLATE);
				
				A_CopyMaster(OverlayId()-6, OverlayId()-5, (75, 165) + (invoker.FigOffset[OverlayId()>SecndLay+6?1:0].X, invoker.FigOffset[OverlayId()>SecndLay+6?1:0].Y*.5), -90);
				A_CopyMaster(OverlayId()-6, OverlayId()-4);
			}
			Stop;
			
		SecndHandInfightOver:
			TNT1 A 0;
			#### # 1{
				Player.GetPSprite(OverlayId()).Sprite = Player.GetPSprite(OverlayId()-2).Sprite;
				Player.GetPSprite(OverlayId()).Frame = Player.GetPSprite(OverlayId()-2).Frame - 3;
				Player.GetPSprite(OverlayId()).Translation = invoker.GlovesTrans;
				Player.GetPSprite(OverlayId()).Pivot = Player.GetPSprite(OverlayId()-2).Pivot;
				
				A_CopyMaster(OverlayId()-2);
				Player.GetPSprite(OverlayId()).bMirror = Player.GetPSprite(OverlayId()-2).bMirror;
				Player.GetPSprite(OverlayId()).bFlip = Player.GetPSprite(OverlayId()-2).bFlip;
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, false);
			}
			#### # 1 {
				int Lay = OverlayId();
				A_CopyMaster(Lay-2);
				Player.GetPSprite(Lay).bMirror = Player.GetPSprite(Lay-2).bMirror;
				Player.GetPSprite(Lay).bFlip = Player.GetPSprite(Lay-2).bFlip;
				Player.GetPSprite(Lay).Scale = Player.GetPSprite(Lay-2).Scale;
			}
			Wait;
		
		MainHandInfight:
			PUN1 M 0 {
				A_OverlayFlags(OverlayId(), PSPF_MIRROR|PSPF_FLIP, !GetCVar("MRIntW_RightPunch"));
				A_SetHandsSprite();
				Player.GetPSprite(OverlayId()).Translation = invoker.GlovesTrans;
				A_OverlayPivot(OverlayId(), 1, .2);
				A_OverlayRotate(OverlayId(), 90);
				A_OverlayScale(OverlayId(), 1.2, 1.2);
			}
			#### # 1;
			Wait;
		InfightActor:
			TNT1 A 0 {
				int Lay = OverlayId();
				
				Let Act = invoker.LineTarg;
				if(Lay>MainLay+1)Act = invoker.LineTarg.Target;
				
				if(!Act){
					A_ClearOverlays(Lay, Lay);
					Return;
				}
				Let Stayt = Act.FindState("Spawn");
				TextureId Sprit = Stayt.GetSpriteTexture(0);
				
				int Akhtung;
				While(!Sprit.IsValid() || Stayt.Sprite == GetSpriteIndex("TNT1A0")){
					Stayt = Stayt.NextState;
					Sprit = Stayt.GetSpriteTexture(0);
					Akhtung++;
					
					if(Akhtung>2500)Break;
				}
				
				if(!Sprit.IsValid()){
					A_ClearOverlays(Lay, Lay);
					Return;
				}
				
				Vector2 Scale = Texman.GetScaledSize(Sprit);
				Scale.Y = Texman.CheckRealHeight(Sprit);
				
				Double Fit;
				if(Scale.X*1.25>Scale.Y)Fit = 55/Scale.X;
				else Fit = 45/Scale.Y;
				
				Vector2 Offset = Texman.GetScaledOffset(Sprit)*Fit;
				
				if(Lay>MainLay+1)invoker.FigOffset[1] = Offset;
				else invoker.FigOffset[0] = Offset;
								
				Player.GetPSprite(Lay).Sprite = Stayt.Sprite;
				Player.GetPSprite(Lay).Frame = Stayt.Frame;
				Player.GetPSprite(Lay).Scale *= Fit;
				A_OverlayPivot(Lay, .5, 1);
				
				if(Scale.X*1.25>Scale.Y){
					A_ClearOverlays(Lay+1, Lay+1);
					Player.GetPSprite(Lay-1).Frame = 10;
					Player.GetPSprite(Lay-1).Scale = (1,1);
				}
				
				A_OverlayTranslation(OverlayId(), "MRIntWLowColors");
			}
			#### # 1{
				A_CopyMaster(OverlayId()-1, OverlayId(), (90, 190), -90);
				Player.GetPSprite(OverlayId()).bMirror = Player.GetPSprite(OverlayId()-1).bMirror;
				A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, false);
			}
			#### # 1{
				int Lay = OverlayId();
				
				if(Player.GetPSprite(Lay-1).Frame==10){
					Let Act = invoker.LineTarg;
					if(Lay>MainLay+1 && Act)Act = invoker.LineTarg.Target;
					
					if(!Act || Act == Self)Return;
					
					if((Act.Target && Act.Target != Self && InStateSequence(Act.CurState, Act.FindState("Missile"))) || 
						((Act == invoker.LineTarg && Act.Health<invoker.TargLastHP) || (Act != invoker.LineTarg && Act.Health<invoker.TargTargLastHP)))
					{
						if(Act.Tics<=1)A_StartSound(Act.AttackSound, CHAN_VOICE, CHANF_MAYBE_LOCAL, .3, pitch:CFRandom(1.4, 1.45));
						else if(((Act == invoker.LineTarg && Act.Health<invoker.TargLastHP) || (Act != invoker.LineTarg && Act.Health<invoker.TargTargLastHP)) && Act.Tics<=1)A_StartSound(Act.PainSound, CHAN_VOICE, CHANF_LOCAL, .3, pitch:CFRandom(1.4, 1.45));
						Player.GetPSprite(Lay).Sprite = Act.Sprite;
						Player.GetPSprite(Lay).Frame = Act.Frame;
						
						Double Height = CFRandom(-42, -32);
						Player.GetPSprite(Lay-1).Y = Height+(Player.GetPSprite(Lay-1).Y-Height)*.9;
						A_OverlayFlags(Lay-1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay-1).FirstTic);
						
						Vector2 Offset = Texman.GetScaledOffset(Act.CurState.GetSpriteTexture(0))*Player.GetPSprite(Lay).Scale.X;
						
						if(Lay>MainLay+1)invoker.FigOffset[1] = Offset;
						else invoker.FigOffset[0] = Offset;
					}
					else {
						Let Stayt = Act.FindState("Spawn");
						
						int Akhtung;
						While(!Stayt.GetSpriteTexture(0).IsValid()){
							Stayt = Stayt.NextState;
							Akhtung++;
							
							if(Akhtung>2500)Break;
						}
						
						if(!Stayt.GetSpriteTexture(0).IsValid())
						{
							Return;
						}
						
						Player.GetPSprite(Lay).Sprite = Stayt.Sprite;
						Player.GetPSprite(Lay).Frame = Stayt.Frame;
						
						Player.GetPSprite(Lay-1).Y = -40+(Player.GetPSprite(Lay-1).Y+40)*.9;
						A_OverlayFlags(Lay-1, PSPF_INTERPOLATE, !Player.GetPSprite(Lay-1).FirstTic);
						
						Vector2 Offset = Texman.GetScaledOffset(Stayt.GetSpriteTexture(0))*Player.GetPSprite(Lay).Scale.X;
						
						if(Lay>MainLay+1)invoker.FigOffset[1] = Offset;
						else invoker.FigOffset[0] = Offset;
					}
				}
								
				A_CopyMaster(Lay-1, Lay, (75, 165) + (invoker.FigOffset[Lay>MainLay+1?1:0].X, invoker.FigOffset[Lay>MainLay+1?1:0].Y*.5), -90);
				Player.GetPSprite(Lay).bMirror = Player.GetPSprite(Lay-1).bMirror;
				
				invoker.TargLastHP = invoker.LineTarg.Health;
				if(invoker.LineTarg.Target)invoker.TargTargLastHP = invoker.LineTarg.Target.Health;
			}
			Wait;
		
		
		//Nobody will like this one
		SecndHandCoolIdle666:
			#### # 0{
				if(Player.FindPSprite(MainLay))Player.SetPsprite(MainLay, invoker.FindState("MainHandWait"));
			}
			#### ######### 1 {
				A_OverlayOffset(SecndLay, -2, 5, WOF_ADD);
				A_OverlayOffset(MainLay, 2, 5, WOF_ADD);
			}
			TNT1 A 10 A_SetTics(CRandom(35, 40));
			MRD1 G 1 {
				A_Overlay(MainLay, "MainHandCoolIdle666");
				
				A_OverlayPivot(MainLay, .5, .5);
				Player.GetPSprite(MainLay).Translation = invoker.GlovesTrans;
				
				A_OverlayOffset(MainLay, 50, 68);
				A_OverlayFlags(MainLay, PSPF_MIRROR|PSPF_FLIP, GetCVar("MRIntW_RightPunch"));
				
				A_OverlayFlags(SecndLay, PSPF_FLIP, !GetCVar("MRIntW_RightPunch"));
				A_OverlayOffset(SecndLay, 200, 68);
				
				A_OverlayFlags(SecndLay, PSPF_INTERPOLATE, false);
				A_OverlayFlags(MainLay, PSPF_INTERPOLATE, false);
			}
			#### ############################ 1 {
				Player.GetPSprite(SecndLay).Y *= .9;
				Player.GetPSprite(MainLay).Y *= .9;
			}
			#### # 1 {
				A_SetTics(CRandom(6, 7));
				A_OverlayOffset(SecndLay, 200, 0, WOF_INTERPOLATE);
				A_OverlayOffset(MainLay, 50, 0, WOF_INTERPOLATE);
				invoker.IdleState = .99;
			}
		Hell:
			#### # 1 {
				Player.GetPSprite(SecndLay).Y = -50+(Player.GetPSprite(SecndLay).Y+50)*(1-invoker.IdleState);
				Player.GetPSprite(MainLay).Y = 20+(Player.GetPSprite(MainLay).Y-20)*(1-invoker.IdleState);
				if(Player.GetPSprite(MainLay).Y < 19.5*invoker.IdleState)Player.SetPsprite(SecndLay, Player.GetPSprite(SecndLay).CurState);
			}
			#### # 1;
			#### # 1 {
				Player.GetPSprite(MainLay).Y = -50+(Player.GetPSprite(MainLay).Y+50)*(1-invoker.IdleState);
				Player.GetPSprite(SecndLay).Y = 20+(Player.GetPSprite(SecndLay).Y-20)*(1-invoker.IdleState);
				if(Player.GetPSprite(SecndLay).Y < 19.5*invoker.IdleState)Player.SetPsprite(SecndLay, Player.GetPSprite(SecndLay).CurState);
			}
			#### # 1;
			#### # 0 {invoker.IdleState *= .9;}
			#### # 0 A_JumpIf(invoker.IdleState<.001, 1);
			Goto Hell;
			#### ### 1 {
				Player.GetPSprite(MainLay).Y *= .6;
				Player.GetPSprite(SecndLay).Y *= .6;
			}
			#### ###################### 1 {
				A_OverlayOffseT(SecndLay, 0, 5, WOF_ADD);
				A_OverlayOffseT(MainLay, 0, 5, WOF_ADD);
			}
			#### # 1 {
				A_OverlayOffseT(SecndLay, 0, 70, WOF_INTERPOLATE);
				A_OverlayOffseT(MainLay, 0, 70, WOF_INTERPOLATE);
			}
			TNT1 A 7 A_OverlayFlags(OverlayId(), PSPF_INTERPOLATE, false);
			Goto SecndHandRaise;
			
		MainHandCoolIdle666:
			MRD1 G 1;
			Wait;
	}
}