/*
	Handling animations activation, mod disabling or any other global actions/events
*/

Class MRIntWeaps_Handler: EventHandler
{
	Static Const String Weapons[] = {//Weapons to replace
		"Fist", "Chainsaw", "Pistol", "Shotgun", "SuperShotgun",
		"Chaingun", "RocketLauncher", "PlasmaRifle", "BFG9000"
		,"ID24Incinerator", "ID24CalamityBlade"
	};
	
	Array<Actor> Berserks;
	MRIntWeaps_Smoker Smokers[MAXPLAYERS];
	MRIntWeaps_WeaponChecker WeaponChecker[MAXPLAYERS];
		
	Override Void CheckReplacement(ReplaceEvent e)
	{
		if(!MRIntW_ReplaceWeapon)Return;
		
		if(!(e.Replacee is 'DoomWeapon'))Return;
		
		String ActName = e.Replacee.GetClassName();
		
		if(!((Class<Weapon>)("MRIntWeaps_"..ActName)))Return;
		
		if(ActName.IndexOf("ID24")>-1 && !MRIntW_LORWeaps)Return;
		
		e.Replacement = "MRIntWeaps_"..ActName;
	}
	
	Void GiveWeapons(Actor Plr)//Replace player's vanilla weapons with the mods'
	{
		if(!Plr)Return;
		
		if(!WeaponChecker[Plr.PlayerNumber()]){
			WeaponChecker[Plr.PlayerNumber()] = New('MRIntWeaps_WeaponChecker');
			WeaponChecker[Plr.PlayerNumber()].Master = Plr;
			Return;
		}
		
		String Select;
		if(Plr.Player.ReadyWeapon)Select = Plr.Player.ReadyWeapon.GetClassName();
		else if(Plr.Player.PendingWeapon is 'Weapon')Select = Plr.Player.PendingWeapon.GetClassName();
		
		Bool GotWeapon[11];
		
		int Weaps = Weapons.Size()-2;
		if(MRIntW_LoRWeaps)Weaps = Weapons.Size();
		
		Inventory Item = Plr.Inv;
		while(Item != Null){
			Let CurItem = Item;
			Item = Item.Inv;
			if(Weapon(CurItem)){
				For(int i=0;i<Weaps;i++){//Change Weaps to Weapons.Size()
					if(CurItem is Weapons[i])GotWeapon[i] = true;
				}
				Plr.RemoveInventory(CurItem);
			}
		}
		
		For(int i=0;i<Weaps;i++){
			if(!GotWeapon[i])Continue;
			
			if(!Plr.FindInventory("MRIntWeaps_"..Weapons[i])){
				int CurAmmo;
				Class<Ammo> Amo;
				if(GetDefaultByType((Class<Weapon>)(Weapons[i])).AmmoType1!=""){
					Amo = GetDefaultByType((Class<Weapon>)(Weapons[i])).AmmoType1;
					CurAmmo = Plr.CountInv(Amo);
				}
				Plr.GiveInventory("MRIntWeaps_"..Weapons[i], 1);
				if(Amo){
					Plr.SetInventory(Amo, CurAmmo, true);
				}
			}
		}
		
		if(Select!="")Plr.A_SelectWeapon("MRIntWeaps_"..Select);
		
		if(!Smokers[Plr.PlayerNumber()])
		{
			Smokers[Plr.PlayerNumber()] = New('MRIntWeaps_Smoker');
			Smokers[Plr.PlayerNumber()].Owner = Plr;
		}
	}
	
	Void TakeWeapons(Actor Plr, Bool Temp = false)//Replace player's weapons from the mod with vanilla ones
	{
		if(!Plr)Return;
		
		if(WeaponChecker[Plr.PlayerNumber()] && !Temp)WeaponChecker[Plr.PlayerNumber()].Destroy();
		
		String Select;
		if(Plr.Player.ReadyWeapon)Select = Plr.Player.ReadyWeapon.GetClassName();
		else if(Plr.Player.PendingWeapon is 'Weapon')Select = Plr.Player.PendingWeapon.GetClassName();
		
		For(int i=0;i<Weapons.Size();i++){
			Let Weap = Plr.FindInventory("MRIntWeaps_"..Weapons[i]);
			if(Weap){
				Weap.Destroy();
				
				if(!Plr.FindInventory(Weapons[i])){
					int CurAmmo;
					Class<Ammo> Amo;
					if(GetDefaultByType((Class<Weapon>)(Weapons[i])).AmmoType1!=""){
						Amo = GetDefaultByType((Class<Weapon>)(Weapons[i])).AmmoType1;
						CurAmmo = Plr.CountInv(Amo);
					}
					Plr.GiveInventory(Weapons[i], 1);
					if(Amo){
						Plr.SetInventory(Amo, CurAmmo, true);
					}
				}
			}
		}
		Select.Replace("MRIntWeaps_", "");
		if(Select!="")Plr.A_SelectWeapon(Select);
	}
	
	Void TakeOtherWeapons(Actor Plr)
	{
		if(!Plr)Return;
		
		Inventory Item = Plr.Inv;
		while(Item != Null){
			Let CurItem = Item;
			Item = Item.Inv;
			if(Weapon(CurItem)){
				String Naym = CurItem.GetClassName();
				if(Naym.IndexOf("MRIntWeaps_")<0)Plr.RemoveInventory(CurItem);
			}
		}
	}
	
	Void RemoveWeapons()//Replace mods weapons on the level with vanilla ones
	{
		Let iter = ThinkerIterator.Create("DoomWeapon");
		Inventory Weap;
		
		int Akhtung;
		While(Weap = Weapon(iter.Next())){
			Akhtung++;
			if(Akhtung>2000)Break;
			
			if(Weap.Owner)Continue;
			
			String ClassName = Weap.GetClassName();
			ClassName = ClassName.MakeLower();

			if(ClassName.IndexOf("mrintweaps_")>-1){
				ClassName.Replace("mrintweaps_", "");
				Let a = Weap.Spawn(ClassName, Weap.Pos);
				a.Vel = Weap.Vel;
				Weap.Destroy();
			}
		}
		
		foreach(Bers : Berserks)
			if(Bers)Bers.Destroy();
		//For(int i=0;i<Berserks.Size();i++){if(Berserks[i])Berserks[i].Destroy();}
		Berserks.Clear();
	}
	
	Void ReplaceWeapons()
	{
		Let iter = ThinkerIterator.Create("DoomWeapon");
		Inventory Weap;
		
		int Akhtung;
		While(Weap = Weapon(iter.Next())){
			Akhtung++;
			if(Akhtung>2000)Break;
			
			if(Weap.Owner)Continue;

			String ClassName = Weap.GetClassName();
			ClassName = ClassName.MakeLower();
			
			if(ClassName.IndexOf("mrintweaps_")>-1)Continue;
			
			Let MRWeap = (Class<Weapon>)("MRIntWeaps_"..ClassName);
			if(MRWeap){
				Let a = Weap.Spawn(MRWeap, Weap.Pos);
				a.Vel = Weap.Vel;
				Weap.Destroy();
			}
		}
	}
	
	Override Void PlayerSpawned(PlayerEvent e)
	{
		if(!MRIntW_ReplaceWeapon)Return;
		
		if(WeaponChecker[e.PlayerNumber])Return;

		GiveWeapons(Players[e.PlayerNumber].mo);
	}
	
	Override Void PlayerRespawned(PlayerEvent e)
	{
		if(!MRIntW_ReplaceWeapon)Return;
		
		if(WeaponChecker[e.PlayerNumber])Return;
		
		GiveWeapons(Players[e.PlayerNumber].mo);
	}
	
	Override Void WorldThingSpawned(WorldEvent e)
	{
		if(!e.Thing)Return;
		
		if((e.Thing is "BulletPuff" || Actor.GetReplacee(e.Thing.GetClass()) == "BulletPuff") &&
			MRIntW_PlayerWhichParticles&MRIWPP_Puff)
		{
			SpawnPuffParticles(e.Thing);
			Return;
		}
		
		if(e.Thing is 'TeleportFog' && MRIntW_TeleportParticles){
			Let a = New('MRIntWeaps_TeleportParticles');
			a.Master = e.Thing;
		}
		
		if(MRIntW_MonsterParticles)SpawnMonsterParticleEffects(e.Thing);
		
		if(e.Thing is 'Berserk' || Actor.GetReplacee('Berserk') == e.Thing.GetClass()){
			Let a = e.Thing.Spawn("MRIntWeaps_FistSelector", e.Thing.Pos);
			a.Master = e.Thing;
			Berserks.Push(a);
			
			Return;
		}
		
		if(Level.Time<2 && MRIntW_DecorationParticles)SpawnDecorationParticleEffects(e.Thing);
	}
	
	Override Void WorldTick()
	{
		ReduceCasingsCluster();
	}
		
	Override Void WorldThingDamaged(WorldEvent e)
	{
		if(!e.Thing || !e.Inflictor)Return;
		
		if(PlayerPawn(e.Thing) && e.Thing.FindInventory("MRIntWeaps_Fist") &&
			MRIntWeaps_Fist(e.Thing.FindInventory("MRIntWeaps_Fist")).GlovesColor == 13
		){
			MRIntWeaps_Fist(e.Thing.FindInventory("MRIntWeaps_Fist")).LastActor = e.DamageSource;
		}
		else if(PlayerPawn(e.DamageSource) && e.DamageSource.FindInventory("MRIntWeaps_Fist") &&
			(MRIntWeaps_Fist(e.DamageSource.FindInventory("MRIntWeaps_Fist")).GlovesColor == 14||
			MRIntWeaps_Fist(e.DamageSource.FindInventory("MRIntWeaps_Fist")).GlovesColor == 16)
		){
			MRIntWeaps_Fist(e.DamageSource.FindInventory("MRIntWeaps_Fist")).LastActor = e.Thing;
		}
	}
	
	Override Void NetworkProcess(ConsoleEvent e)
	{
		Let Plr = Players[e.Player].mo;
		if(!Plr)Return;
		
		if(e.name ~== "MRIntWeaps_LowerGun"){
			Let Handler = MRIntWeaps_Fist(Plr.FindInventory("MRIntWeaps_Fist"));
			if(Handler)Handler.LowerGun = !Handler.LowerGun;
		}
		
		if(e.name ~== "MRIntWeaps_Uninstall"){
			For(int i=0;i<MAXPLAYERS;i++){
				if(Players[i].mo)TakeWeapons(Players[i].mo);
			}
			RemoveWeapons();
			//Uninstalled = true;
			//Destroy();
			Return;
		}
		
		if(e.name ~== "MRIntWeaps_Give"){
			if(e.Args[0]>0){
				TakeWeapons(Plr, true);
				Return;
			}
			GiveWeapons(Plr);
			Return;
		}
		if(e.name ~== "MRIntWeaps_Take"){
			TakeWeapons(Plr);
			Return;
		}
		if(e.name ~== "MRIntWeaps_TakeOther"){
			TakeOtherWeapons(Plr);
			Return;
		}
		if(e.Name ~== "MRIntW_Casings")
		{
			Console.Printf("Casings: "..Casings.Size());
			Return;
		}
		if(e.name ~== "MRIntWeaps_ClearCasings")
		{
			foreach(Casing : Casings){
				if(Casing)Casing.Destroy();
			}
			Casings.Clear();
		}
		if(e.name ~== "MRIntWeaps_RandomGlovesColor"){
			Color Rand = Color(Random(0,255), Random(0,255), Random(0,255));
			
			CVar.FindCVar("MRIntW_GlovesColorTemp").SetInt(Rand);
			Return;
		}
		if(e.name ~== "MRIntWeaps_ApplyParticles"){
			UpdateOnStartupParticles();
			Return;
		}
		if(e.name ~== "MRIntWeaps_Crash"){
			Switch(e.Args[0])
			{
				Default:
					Console.Printf("Type \cgMRIntWeaps_Crash #\c- and replace \cg#\c- with followed number:\n(1-4 - \cvVM abort\c-, 5-6 - \crEngine crash\c-)\n1 - reading from null actor\n2 - division by 0\n3 - ThrowAbortException()\n4 - player actor destruction\n5 - infinite loop\n6 - abort_m engine crash");
					Return;
				//VM abort
				Case 1:
					Actor mo;
					mo.Target.GetClassName();
					Return;
				Case 2:
					int Zero = 0;
					5/Zero;
					Return;
				Case 3:
					ThrowAbortException("Crash.");
					Return;
				Case 4:
					Players[ConsolePlayer].mo.Destroy();
					Return;
				//Engine crash
				Case 5:
					While(true){}
				Case 6:
					Plr.CurSector = null;
					Plr.Tick();
					let a = 'fsdgshrehfgwgfheg';
					let o = new(a);
			}
		}
	}
	
	Void UpdateOnStartupParticles()
	{
		foreach(PartThink : PartThinkers)
			if(PartThink)PartThink.Destroy();
		PartThinkers.Clear();
		
		ThinkerIterator it = ThinkerIterator.Create();
		Actor mo;
		
		Bool Decorations, Monsters;
		Decorations = MRIntW_DecorationParticles;
		Monsters = MRIntW_MonsterParticles;
		
		int MonstSet = MRIntW_MonsterWhichParticles2;
		
		While(mo = Actor(it.Next()))
		{
			if(Monsters){
				if(mo.Health<1)Continue;
				if(mo is 'LostSoul')
				{
					if(!(MonstSet&MRIWMP_SoulSmoke||
						MonstSet&MRIWMP_SoulFire||
						MonstSet&MRIWMP_SoulSplash)
					)Continue;
					
					Let a = New('MRIntWeaps_MonsterProjectileParticles');
					a.Master = mo;
					a.Type = 7;
					PartThinkers.Push(a);
					Continue;
				}
				if(mo is 'PainElemental')
				{
					if(!(MonstSet&MRIWMP_PainSplash))Continue;
					
					Let a = New('MRIntWeaps_MonsterProjectileParticles');
					a.Master = mo;
					a.Type = 8;
					PartThinkers.Push(a);
					Continue;
				}
				if(mo is 'Cyberdemon')
				{
					if(!(MonstSet&MRIWMP_CyberSmoke||
						MonstSet&MRIWMP_CyberBlood||
						MonstSet&MRIWMP_CyberSplash)
					)Continue;
					
					Let a = New('MRIntWeaps_MonsterProjectileParticles');
					a.Master = mo;
					a.Type = 9;
					PartThinkers.Push(a);
					Continue;
				}
				if(mo is 'SpiderMastermind')
				{
					if(!(MonstSet&MRIWMP_SpiderSmoke||
						MonstSet&MRIWMP_SpiderBlood||
						MonstSet&MRIWMP_SpiderSplash)
					)Continue;
					
					Let a = New('MRIntWeaps_MonsterProjectileParticles');
					a.Master = mo;
					a.Type = 10;
					PartThinkers.Push(a);
					Continue;
				}
			}
			
			if(Decorations)SpawnDecorationParticleEffects(mo);
		}
	}
		
	Override Void WorldThingDestroyed(WorldEvent e)
	{
		if(e.Thing == Players[ConsolePlayer].Camera && GameState != 0)NotCrash = true;
	}
	
	Bool Uninstalled, NotCrash;
	Override Void OnDestroy()
	{
		if(GameState == GS_FullConsole && !NotCrash){
			S_StartSound("MRIntW/Crash", CHAN_AUTO, CHANF_UI, pitch:CFRandom(3.8, 4));
			Console.Printf(StringTable.Localize("$MRIntW_VMAbortMessage"), MRIntW_Version);
			Return;
		}
		if(Uninstalled)Console.Printf(StringTable.Localize("$MRIntWeaps_Uninstalled"));
	}
	
	Bool DifVersion;
	Override Void OnRegister()
	{
		if((MRIntW_Version!=CVar.GetCVar("MRIntW_Version").GetDefaultInt()))New('MRIntW_DifVersionMessage');
		CVar.GetCVar("MRIntW_Version").SetInt(CVar.GetCVar("MRIntW_Version").GetDefaultInt());
		//Console.Printf("Register");
	}
	
	Override Void WorldLoaded(WorldEvent e)
	{
		NotCrash = false;
		
		For(int i=0;i<MAXPLAYERS;i++){
			if(!Players[i].mo)Continue;
			
			if(Players[i].mo.FindInventory("MRIntWeaps_Fist")){
				MRIntWeaps_Fist(Players[i].mo.FindInventory("MRIntWeaps_Fist")).GlovesTrans = 0;
			}
		}
		//Console.Printf("World Loaded");
	}
}

Class MRIntWeaps_WeaponChecker: Thinker
{
	Actor Master;
	int Delay;
	
	Override Void Tick()
	{
		if(!Master)Return;
		Super.Tick();
		
		//Voodoo doll check (stolen from Hideous Destructor)
		if(PlayerPawn(Master)&& !!Master.player && !!Master.player.mo)Master = Master.Player.mo;
		
		if(!Master.FindInventory("MRIntWeaps_Fist"))GiveWeapons();
	}
	
	Void GiveWeapons()
	{
		Let Handler = MRIntWeaps_Handler(EventHandler.Find("MRIntWeaps_Handler"));
		
		if(!Handler)Return;
		
		Handler.GiveWeapons(Master);
	}
}

Class MRIntW_DifVersionMessage: Thinker
{
	Const Start = 6;
	Const Chan = 221;
	int Time;
	Float Pitch;
	Override Void Tick()
	{
		Super.Tick();
		
		Let Plr = Players[ConsolePlayer].Camera;
		
		if(!Plr)Return;
		
		Time++;
		Switch(Time)
		{
			Case Start:
				Console.Printf(StringTable.Localize("$MRIntW_VersionMessage"));
				Plr.A_StartSound("MRIntW/Message1", Chan, CHANF_LOOP, .05, pitch:Pitch = 4);
				Break;
				
			Default:
				Float Vol = Time-Start;
				if(Vol<8){
					Plr.A_SoundVolume(Chan, Vol/7.+.2);
				}
				else if(Vol>26){
					Plr.A_SoundVolume(Chan, 1.-((Vol-26)/9.)+.2);
				}
				else {
					Plr.A_SoundVolume(Chan, 1);
				}
				
				Float Pit = (Time%4)*.2;
				if(Vol<6){
					Plr.A_SoundPitch(Chan, Pitch+ (Pit/5.)*.2+Pit);
				}
				else if(Vol>14){
					Plr.A_SoundPitch(Chan, Pitch+ (1.-((Pit-14)/21.))*.2+Pit);
				}
				else {
					Plr.A_SoundPitch(Chan, Pitch+ .2+Pit);
				}
				Break;
				
			Case Start+35:
				Plr.A_StopSound(Chan);
				Destroy();
				Break;
		}
	}
}